### ISSUE TITLE
Special page to get list of what files are used on each wiki

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#107]
A special page that would get a list of files that have been uploaded to meta that are used on different wikis would be helpful. Not something like <a href="http://meta.brickimedia.org/index.php?title=Special%3AGlobalUsage&limit=50&target=Reviews-logo.png">Global usage</a>, but a special page where you select the wiki you want to see what images are being used, and it shows every image used on the specified wiki. I think a special page like this would be useful because I'm currently trying to see if there are any images from Brickipedia's file import being used on the wikis I've imported content from, because it'd be helpful ahead of time to know what files would be overwritten when cuusoo and stories file imports take place.

**Comment by georgebarnick** [comment]
Something to add to this is it'd be great if there was a way to get a list of files unused globally. Would make cleaning unused images out much easier.

**Comment by codynguyen1116** [comment]
wikis are going to be consolidated so closing
