### ISSUE TITLE
Renaming an Account Doesn't Move the Userpages Globally

### ISSUE THREAD

**Issue by Drewlzoo** [Brickimedia/brickimedia#168]
I just renamed Legoboy's account per his request, but when I renamed it, it only moved his userpage and talk page on meta. Any other wikis he was on still displayed his userpage under his old name. When you go to his new userpage, it does display the social profile header properly, but not the actually page.

**Comment by neoncitylights** [comment]
Superseded by https://phabricator.wikimedia.org/T104830
