### ISSUE TITLE
Link to user's blogs on their userpage

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#190]
Is there a chance of having a "Blogs" in the "personal tools" section which would list all your blogs, and/or in the profile section of another user next to their avatar with all the "Discussion", "Contributions", "Edit Count", etc have a list of their blogs as well?

A link to Special:Prefixindex/User_blog:$wgUserName should work

**Comment by neoncitylights** [comment]
Superseded by https://phabricator.wikimedia.org/T146588
