### ISSUE TITLE
Blocked adverts breaking CSS/JS

### ISSUE THREAD

**Issue by UltrasonicNXT** [Brickimedia/brickimedia#200]
![screenshot 214](https://f.cloud.github.com/assets/4870935/2087159/8a59185c-8e66-11e3-9513-e9245f63f655.png)
I have found that when using Brickimedia (on refreshed) through firewalls, the CSS/JS breaks, becuase the firewall replaces JS with [a html template](http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js)

**Comment by codynguyen1116** [comment]
**Requesting fo closure**  since this is old and refreshed is much newer (unless if this is still an issue?)

**Comment by codynguyen1116** [comment]
```Bump``` Still requesting for closure

**Comment by georgebarnick** [comment]
Waiting for confirmation that this is no longer an issue  with blocked adverts

**Comment by codynguyen1116** [comment]
pinging @UltrasonicNXT

**Comment by UltrasonicNXT** [comment]
Don't really know anymore, I'll just close
