### ISSUE TITLE
Lato fonts on Refreshed not working in IE

### ISSUE THREAD

**Issue by mary-kate** [Brickimedia/brickimedia#202]
Refreshed's main.css (skins/Refreshed/refreshed/main.css) loads the web fonts Lato Light, Lato Bold and Lato Regular from Google's servers (which, if I may note, is problematic for reasons unrelated to this ticket) in lines 1-20. This appears to be working in Firefox 26.0, but Internet Explorer 11 doesn't like this at all.
A (rather huge) screenshot illustrating IE11's and FF 26's renderings -- and therefore this issue -- of Meta's main page can be found on ticket #201.

For what it's worth: I've had similar issues with a custom skin that I wrote. My local development wiki is running with ResourceLoader in the debug mode (```$wgResourceLoaderDebug = true;```), because RL can be quite a pain to debug. The font-face stuff in the skin I'm talking about worked just fine, but when it was deployed to production, the custom fonts stopped working. I played around a bit and noticed that in ResourceLoader's "production mode" (on a production site), the fonts would be always broken, but in debug mode (appending ```debug=true``` to the request URL) they'd work -- as if the wiki's settings file had ```$wgResourceLoaderDebug = true;``` set!

I was, however, unable to find a real solution to the underlying issue. Any and all thoughts on the matter are more than welcome.

**Comment by MtMNC** [comment]
This seems related to https://github.com/Brickimedia/brickimedia/issues/382. We've had more discussion over there, so I'm going to close this.
