### ISSUE TITLE
Enhancements for VoteNY

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#207]
Just some ideas for the vote extension, I'm mainly thinking about Customs, and maybe also reviews to an extent. There are three things I'm thinking of, they all build on top of each other (it's probably not really worth the effort, I was going to try some stuff with it myself, but all the code seems to have disappeared, I can only see the readme's on here)
- [x] A magic word NUMBEROFVOTES, much like NUMBEROFCOMMENTS, where you can get the number of votes for a specified page would be great. This would have to function differently for when type="1", because that's a star rating (maybe show average star rating, with the number of voters?)
- [ ] A NUMBEROFVOTESSINCE, where you can specify the article and a date, and the result is the number of votes that have been made since that date.
- [ ] Some sort of transcludable special page, which shows the most voted on pages on the site, and also an option to show the most voted on articles since a particular date.

As I said, just some ideas, may not be worth doing though.

**Comment by neoncitylights** [comment]
NUMBEROFVOTESSINCE feature request moved upstream at https://phabricator.wikimedia.org/T146555

**Comment by neoncitylights** [comment]
Superseded by https://phabricator.wikimedia.org/T151432
