### ISSUE TITLE
Change anonymous user tools

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#210]
I think the user tools dropdown on Refreshed should be changed. It should put login/signup links first, and not have the IP address and talk page front and center (because it's less important to most visitors).

![screenshot from 2014-02-09 01 41 05](https://f.cloud.github.com/assets/3800972/2119250/1c4c55ac-9156-11e3-8a04-1d3199cebf95.png)

In the above screenshot, the left is what it currently is like, and the right is what I think it should be like (except I realise I made a slight mistake; the right side where it says "Log in" should say "Log in/sign up" and a log in link should be part of the dropdown).

**Comment by georgebarnick** [comment]
Perhaps we could also extend <a href="https://www.mediawiki.org/wiki/Extension:OOJsUIAjaxLogin">OOJsUIAjaxLogin</a> to also make it a more seamless login process?

**Comment by neoncitylights** [comment]
Moved to https://phabricator.wikimedia.org/T143510
