### ISSUE TITLE
USERNAME magic word doesn't work properly until purged

### ISSUE THREAD

**Issue by MtMNC** [Brickimedia/brickimedia#218]
When I wasn't logged in, I visited http://en.brickimedia.org/wiki/User:King_of_Nynrah and noticed the page began with "Hello Codyn329"; I looked at the source and the actual page's source contains "Hello {{USERNAME}}." When I logged in, the page still said I was Codyn329 until I purged the page, when it then said I was MtMNC, and then out of curiosity I logged out again, purged, and it displayed the IP address it normally does (which I presume belongs to CloudFlare).

Now, I can assure you that I am not Codyn329 and that Codyn329 has never been on my computer or network, which leads me to believe this might be a CloudFlare issue. I remember a while back issues regarding blocking came up because CloudFlare routes traffic through their servers; could this also be the reason usernames don't match up properly?

**Comment by neoncitylights** [comment]
_removed comment_
