### ISSUE TITLE
Automatically get number votes for a LEGO Ideas project

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#223]
I was wondering if it was possible to get the number of votes that a project has on http://lego.cuusoo.com and have that number show up a page?

CUUSOO does use some JSON (for example http://lego.cuusoo.com/api/participations/get/36088.json shows the number of votes for the Ghostbusters project that recently passed)

Apparently it's possible to do this as a WordPress plugin as evidenced at https://github.com/NateJacobs/cuusoo-project-embed , and I know MediaWiki can do a few JSON things, but I'm not sure if it could handle that.

I just thought this might be a helpful thing for the CUUSOO wiki (save them from updating the numbers all the time), but if they don't want it, it could possibly be useful for en as well (although there's limited use for en... maybe not worth making an extension for unless it's extremely easy to do)

**Comment by codyn329** [comment]
Glenbricker seems to have a way of retrieving data from LEGO Ideas projects which he calls the "Unofficial LEGO® Ideas Project Tracker (BETA)" . Can be checked out at http://blog.brick-hero.com/ and http://www.brick-hero.com/cdd.php. If someone has a way of contacting him about it so about how he does it, and/or if we could ask for the source code, that'd be pretty cool

**Comment by codynguyen1116** [comment]
Assigning this myself, I'll try my best to work on this

**Comment by codynguyen1116** [comment]
closing, LEGO Ideas Wiki is officially dead

**Comment by georgebarnick** [comment]
RIP :(

On Tue, Mar 29, 2016 at 5:53 PM Cody Nguyen <notifications@github.com>
wrote:

> closing, LEGO Ideas Wiki is officially dead
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brickimedia/brickimedia/issues/223#issuecomment-203127322>
>
-- 
George Barnick
https://www.georgebarnick.photo
