### ISSUE TITLE
Wikidata site for Brickimedia

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#225]
A Wikidata-like website on the Brickimedia network could be something that would make various things easier across our projects. Here are some examples of uses for a Wikidata-like project on Brickimedia:
- Global LEGO set data on projects as we open them in more languages (set number, prices, piece count, etc)
- Global statistics for CUUSOO projects and users (#223)
- Would allow for language links to be more-easily added in a central location

Further uses could be integrated. Having a Wikidata-like project on the Brickimedia network would serve useful especially when we open Brickipedia projects in non-English languages.

**Comment by neoncitylights** [comment]
Superseded by https://phabricator.wikimedia.org/T151431
