### ISSUE TITLE
Separate "Smileys" page for word filter

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#262]
It'd be useful for a list-like page like MediaWiki:Smileys were made that could list filtered/censored words such as swears or other inappropriate remarks.

Such messages to be included in this feature could be:
- ```chat-filter``` - bulleted list of words to filter out in chat
- ```chat-filter-image``` - image (like an emote) or text (like "####" censored text) to display instead of the filtered word
- A chat preference to disable the filter, for example so that administrators could see what word was used if it were censored

**Comment by codynguyen1116** [comment]
https://github.com/Brickimedia/brickimedia/issues/262
