### ISSUE TITLE
ARE issues

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#270]
* Rating doesn't move when a page is moved (see http://en.brickimedia.org/wiki/Part_89669 for example, it was rated C2 previously)
* Scrolling through pages on Special:MassRatings doesn't work. Eg, the "next 250" link at http://en.brickimedia.org/wiki/Special:MassRatings?C2=true goes to http://en.brickimedia.org/index.php?title=Special:MassRatings&limit=250&offset=250 when it should go to http://en.brickimedia.org/index.php?title=Special:MassRatings&C2=true&limit=250&offset=250
* Was the ability to add a category ever done? It's in the JSON, but it doesn't appear to work, and I can't find anything in the code that mentions a category.

**Comment by UltrasonicNXT** [comment]
Gonna close this, everything that can be done has, if we still need some sort of transclusion system go for it in a new issue :)
