### ISSUE TITLE
Redesign Refreshed

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#274]
### Mobile ###
- [x] Move search bar to a more accessible location in the header
- [x] Search cannot be closed, it reopens every time the X is pressed (doesn't occur on desktop browsers)
- [ ] Have the header categories moved to the left side menu (#367)
- [ ] Display MultimediaViewer information better on narrow screens (<a href="https://bugzilla.wikimedia.org/show_bug.cgi?id=71423">Bugzilla 71423</a>)
- [x] Fix text overflow issues on Special pages
- [x] Needs some form of Echo notifications
- [x] Page status indicators
- [x] Logo on default view?

### Desktop ###
- [x] Move page actions below page title
- [x] Add customizable header categories
- [x] Relocate TOC
- [ ] VisualEditor support (#368)
- [x] Typography refresh
- [x] Re-organize header
- [x] Change two sidebars to one
- [ ] Icons for page actions (edit, discussion, etc.) (#369)
- [x] Fix Special:Search (search is crammed into the lower left corner of the page)
- [x] Page action bar doesn't fixate after scrolling in Internet Explorer or Firefox
- [x] Echo's flyout box is stuck at the top of the page and doesn't scroll with the header
- [x] Page status indicators
- [ ] Integrate #210?

## Original post ##
First and foremost, Refreshed is one of my favourite MediaWiki skins out there. I've seen a lot of complaints about it, however. In this enhancement ticket, I will outline solutions to them to redesign Refreshed while keeping its general interface the same. These can be implemented as Refreshed's next major update, 3.0. Maybe this can be a "refresh" to Refreshed. :-)

### Sidebars ###
First of all, I've heard that the two sidebars is confusing. Over time, it's pretty simple to get used to, but it's confusing for the average reader or a new user. To remedy this, I've found it would be simple to move the MediaWiki:Sidebar content that is currently in the ```#rightbar``` to the ```#leftbar```. In the left bar, page actions (edit, watch, discussion, delete, etc) should be removed (I'll elaborate on this later). The Table of Contents also could be removed, but I have another idea for it below. The entire ```#rightbar``` should be removed. I realise this is a drastic change to the skin, but it is important for its usability to our visitors and users.

Sidebar modules should also be made collapsible, like they are on Vector, so that it's easy to hide different modules that you don't care to see/need to see.

### Page actions ###
![screenshot from 2014-04-12 16 39 33](https://cloud.githubusercontent.com/assets/3800972/2688108/cedde1ba-c282-11e3-80e9-36678d9f1a83.png)
Another change should be where the page actions (edit, delete, move, etc) should be in a more central location, inside the ```#content``` area. Refreshed is loosely based on Wikia's skin, and Wikia's skin has an edit button inside the content near where our ```#maintitle``` would be. In other skins, such as Vector, the page actions are directly above the content section in tabs off of the ```#bodyContent``` area. In Wikimedia's current skin redesign concept for Vector, codenamed <a href="http://unicorn.wmflabs.org/winter/">Winter</a>, the page actions are directly below underneath the ```#firstHeading```. We should put our page actions underneath our ```#maintitle``` like that, since it is a convenient location, doesn't obstruct reading, but is also more prominent.

### User tools ###
![screenshot from 2014-04-12 16 41 39](https://cloud.githubusercontent.com/assets/3800972/2688110/f59d3f76-c282-11e3-8e4e-8e1bc8b3bd58.png)

![screenshot from 2014-04-12 16 43 22](https://cloud.githubusercontent.com/assets/3800972/2688111/37ffbd58-c283-11e3-8b82-d95f6ae463e5.png)
I got a complaint a day or so ago that the user tools (login and whatnot) weren't in a good location, as a friend of mine couldn't find where to sign up quickly. My suggestion to fix this would be to move the user tools from the left-hand side to the right-hand side. In most interfaces, user tools such as the user's name and their settings links are on the right instead of the left (<i>e.g.</i> Wikia, Facebook, Twitter, Google, and even skins such as Monobook and Vector).

### Header ###
![screenshot from 2014-04-12 16 30 23](https://cloud.githubusercontent.com/assets/3800972/2688092/d606fbe4-c281-11e3-8a1c-a88988bb9d56.png)
As for the header, like said above, the user tools should be moved to the right. The search bar I'm thinking could be changed a bit. I'm kind of thinking that the wiki wordmark/logo should be left-aligned. This is how Facebook has done it in the past, as does Google and various other interfaces with header bars like Refreshed has (even Wikia's is left-aligned). The center-aligned logo is something I don't see too often, and the only place I can think of right now that has it like that is Twitter, but their header bar is a lot different than ours (theirs is more like Wikia's with major links in the header, which our skin doesn't have). For the search, I think a mere search button that drops down a search bar would work, near the user tools in the right-hand side. An example of a site that has it like this is <a href="http://mashable.com/">Mashable</a>, where their search method not only works well on desktop but on mobile as well. Our current search bar on mobile is a hassle from my experience.

#### Header dropdown/browse links ####
![screenshot from 2014-04-12 16 27 34](https://cloud.githubusercontent.com/assets/3800972/2688088/a3c54adc-c281-11e3-9f38-e69d8d868b57.png)

![screenshot from 2014-04-12 16 33 24](https://cloud.githubusercontent.com/assets/3800972/2688106/a5f81d7e-c282-11e3-8c63-4830bbcafc75.png)
What my above idea for the header offers is a simpler, more familiar interface like other sites have. It also offers a <i>lot</i> of free space, which I think we could take advantage of by allowing wikis to customise links/hover-dropdowns across the header so that navigation is easier. This makes our site easier to browse altogether. Take a look at Wikia and Mashable. On their headers, they have important navigation links on their header. Wikia has dropdowns for their different wiki categories (Lifestyle, Entertainment, Video Games) and navigation inside those dropdowns to various wikis.  Mashable has hover-dropdowns on their header for their various news categories featuring popular, new stories inside the dropdown. We should be able to do that with Refreshed, and allow wikis to customise that through a page similar to MediaWiki:Sidebar so that they can add useful browsing links and dropdowns for their visitors. Examples I can think of would be that it could allow Brickipedia to have links to new themes for visitors to browse through, and it could allow CUUSOO Wiki to have links to most supported projects, new projects, etc.

### Table of Contents ###
As for the Table of Contents, I personally don't find it useful in its position on Refreshed. If it were in the content section like other skins have, it'd be easier for me to use.

### Mobile ###
Currently, Refreshed has a really nice mobile interface. A good change to add with this redesign would be collapsible sections though. If you look at Wikia and Wikimedia's mobile interfaces, the sections are collapsible/expandable so that you don't have to scroll through giant sections to get to content you're looking for. This would make Refreshed more like other mobile-supported wikis, which is a good step forward.

====
This enhancement ticket includes a lot of changes, but I think they would all be useful and important to our usability and ease-of-browsing our wiki. I've heard complaints that it's hard to browse the wikis, actually from members of the LEGO Group themselves. Obviously there is room for major improvement. I've marked this as something to be done by Q3 2014, but by then I'd at least want to see this new skin interface in a BetaFeature. Please leave any other ideas or comments below.

A page can be found on Meta documenting all the expected changes through <a href="http://meta.brickimedia.org/wiki/Usability_initiative/Refreshed_redesign">this link</a>.

Here is a screenshot of an interface similar to what I've described that I put together with Web Inspector:
![screenshot from 2014-04-12 17 46 41](https://cloud.githubusercontent.com/assets/3800972/2688206/f6003992-c28b-11e3-86ff-10f7b9a958ef.png)

**Comment by georgebarnick** [comment]
Looks pretty cool. I'd say for medium do it like how it is on large. The only things I have left to suggest for notifications on small is that when clicking the user menu, maybe highlight the Notifications link in the menu in case someone doesn't know what the red notification next to their avatar means. Also can we get rid of or adjust the "You have new messages" Echo thingy to work better or just be gone from Refreshed?
![image](https://cloud.githubusercontent.com/assets/3800972/5591271/ab82b15c-911f-11e4-9eeb-ca8d26e42820.png)

**Comment by UltrasonicNXT** [comment]
Maybe just "new messages". That can probably be done by just adjusting a translation message.

**Comment by georgebarnick** [comment]
Only thing about adjusting the translation message is that would change it
for all skins. Really we just need it smaller or gone in Refreshed.

>

**Comment by UltrasonicNXT** [comment]
Then just create a new message for refreshed

**Comment by MtMNC** [comment]
The problem with changing the message or removing it altogether is that it would require a good deal of
 changes either way: if we changed a translation message it would carry across all skins and we'd need to translate the new message as well, and removing it would require tampering with Echo.

As of the latest commit the words wrap at least:
![2](https://cloud.githubusercontent.com/assets/5515877/5593066/a71f0790-91a7-11e4-841b-9c1dd9035d75.png)
And with notifications on small:
![1](https://cloud.githubusercontent.com/assets/5515877/5593075/4d07b288-91a8-11e4-9539-7f40a7c3a8e0.png)

It's certainly not the ideal solution but I think it's all we can reasonably do.

**Comment by UltrasonicNXT** [comment]
that'll do fine.

**Comment by georgebarnick** [comment]
Looks great

**Comment by MtMNC** [comment]
Alright.

We're (hopefully) on the home stretch and I'd like to clean up the code to get that out of the way. I'm working on the PHP now, and it turns out we've been using 3 different ways to embed PHP variables into HTML, but I think we should stick with one. Here are the three ways:

`<?php echo '<a href=' . $blah . '>hi</a>'; ?>`
`<?php echo "<a href=$blah>hi</a>"; ?>`
`<a href="<?php echo $blah ?>">hi</a>`

IMO the second and third methods are definitely better than the first. As you can see, the third one is shortest if you need to embed one variable but the second one is shortest if you embed multiple. Also, if it makes a difference, VectorTemplate.php uses the third method.

Which do you think we should use?

**Comment by georgebarnick** [comment]
Personally I think the third is most favourable, because as you mentioned it's what is used in VectorTemplate.php.

**Comment by MtMNC** [comment]
Sounds good.

Also, going through we were (read: I was :P) pretty inconsistent with naming elements. Sometimes elements with names made of multiple words are combined (#searchcloser), sometimes they have dashes (.small-icon), and sometimes both (#siteinfo-mobile). I've noticed MW itself can be pretty inconsistent but I think we should just stick with one style. Which do you think we should use?

Also, on the topic of renaming things, #search is used in both the header and on Special:Search. What would be a better name for it?

**Comment by UltrasonicNXT** [comment]
All MW code should be lowerCamelCase, so #searchCloser, .smallIcon, #siteInfoMobile

**Comment by MtMNC** [comment]
Wait never mind, I just found the [CSS style guide](https://www.mediawiki.org/wiki/Manual:Coding_conventions/CSS#Naming) and it says to use lowercase. But at the same time some of the elements use camelcase anyway... \*shrug\* I'm thinking I'll use camelcase for the ones listed [here](https://www.mediawiki.org/wiki/VisualEditor/Skin_requirements) so we have VisualEditor support but have all the other ones use lowercase.

**Comment by UltrasonicNXT** [comment]
Oh my mistake I was looking at the javascript one.

**Comment by georgebarnick** [comment]
Once we have coding conventions done, is this skin about ready to deploy to Brickimedia? I'll test it later tonight on Brickimedia's server to make sure it's compatible for easy deployment, but I would like this rolled out soon. The rest of the items in TODO are minor and can be added in a subrelease of 3.0 later.

**Comment by georgebarnick** [comment]
http://en.brickimedia.org/wiki/User_blog:ToaMeiko/A_look_at_the_upcoming_version_of_Refreshed

**Comment by georgebarnick** [comment]
One thing to consider would be some Android 5.0 Material Design support. I added a little script <a href="http://en.brickimedia.org/wiki/User:ToaMeiko/refreshed.js">here</a> that worked and looks kind of good in my opinion. Here's sort of what it looks like (on old refreshed):

![screenshot_2015-01-07-20-47-25_framed](https://cloud.githubusercontent.com/assets/3800972/5656718/11dbfcf8-96af-11e4-8ef6-217bec6c4ea7.png)

Should we add this to the TODO or is it not necessary you don't think? If we added it to the skin, would it make it difficult to change on a per-wiki basis (because not all wikis are blue)?

**Comment by mary-kate** [comment]
@georgebarnick: This is a rather annoyingly common problem with custom skins since MW 1.22 (IIRC), which is when the login form was redesigned. I'm confident there oughta be a proper, CSS-only solution for this which doesn't require hacking core (and if someone knows what this solution is, I'm all ears!).
On ShoutWiki we've had this particular problem with several of our custom skins, including, but not limited to Aurora, our default skin, and [Bouquet, a skin ported from WordPress](https://www.mediawiki.org/wiki/Skin:Bouquet). Better yet, these two aforementioned skins require fixes only for the signup page, but some skins require fixes for both the login page *and* the signup page.

The way how I hackily fixed this for ShoutWiki:
1. In `LoginForm::mainLoginForm` (file `includes/special/SpecialUserlogin.php`), there is the line `$out->addTemplate( $template )` which needs to be removed...
2. ...because we need to manually get the HTML provided by QuickTemplate, like this: `$html = $template->getHTML();`
3. And now we'll need to get the name of the skin class of the current user's skin: `$skinClass = get_class( $this->getUser()->getSkin() );`
4. Now we can conditionally inject more HTML into the string (`$html`) which contains the login/signup page HTML. Say we'd want to add our fancy, necessary div only for Refreshed and on the signup page:
```php
if ( $this->mType == 'signup' && $skinClass == 'SkinRefreshed' ) {
$html .= '<div class="cleared"></div>';
}
```
  5. Finally remember to output the HTML we just stiched together: `$out->addHTML( $html );`

This generally speaking works as intended, but it's hardly future-proof since it's a core hack, and as such, someone needs to remember to reapply it during/after each MW upgrade.

**Comment by UltrasonicNXT** [comment]
Should a ticket for this as a bug be submitted to wikimedia?

**Comment by georgebarnick** [comment]
Before we put a core hack in is there any CSS solutions that could be done until Wikimedia fixes it? I'd rather fix it just for this skin for the time being so we can deploy it and not have people think our signup feature is broken? Even if it includes just making ```#content``` have enough padding-bottom to contain the form, that'd be enough to satisfy me for the time being.

**Comment by georgebarnick** [comment]
@MtMNC: Can you join Brickipedia chat? I'm trying to roll out refreshed 3.0 but there are some weird things going on that weren't present on the test site.

**Comment by georgebarnick** [comment]
Refreshed 3.* has been rolled out. All remaining items on the TODO have their own issues open now.
