### ISSUE TITLE
Rewrite comments

### ISSUE THREAD

**Issue by UltrasonicNXT** [Brickimedia/brickimedia#280]
IMO, the comments extension needs a rewrite. This will remind me to do it, but probably after exams.

Including our mods, upstream.

Related bugs: #53, #66, #257

**Comment by UltrasonicNXT** [comment]
Merged

**Comment by georgebarnick** [comment]
Was #257 integrated in the Comments rewrite?

**Comment by UltrasonicNXT** [comment]
no
