### ISSUE TITLE
Editcount transclusion inaccurate

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#285]
When transcluding ```{{Special:Editcount/username}}```, it shows an inaccurate number compared to a user's ```[[Special:Editcount/username]]```. The problem lies in the fact that the transclusion of Editcount uses data from the ```user.user_editcount``` table. Since our ```user``` table is in the ```shared``` database, that column's data is inaccurate everywhere, since whenever a user edits on any wiki, it increments the ```user.user_editcount``` value globally. Due to the ```user``` table being in the ```shared``` database, this ```user.user_editcount``` issue not only affects Extension:Editcount but also Special:Preferences and any other feature that uses an editcount value.

My suggested solution to fix this would be to make the ```user``` table <i>not</i> shared, and instead use <a href="//www.mediawiki.org/wiki/Extension:CentralAuth">CentralAuth</a> to unify each account globally, while keeping a separate ```user``` tables, preventing messed up data in that table like we're seeing now.

**Comment by neoncitylights** [comment]
superseded by https://phabricator.wikimedia.org/T12452
