### ISSUE TITLE
Unable to delete threads in wikiforum

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#287]
Hitting the "delete thread" button results in a blank screen, and the thread does not delete.

**Comment by NovaFlare** [comment]
This problem is definitely still happening, I was actually just about to open a new issue before I saw this. It's not just me, CJC has also tried to delete a thread a couple of months ago and was unable to. 

However, I was under the impression that it was working a long time ago.

(also, this is very insignificant, but I've just noticed that deleted users who had posts in the wikiforum no longer have their name, but your current IP address, example [here] (http://en.brickimedia.org/wiki/Special:WikiForum/Star_Wars_Episode_VII:_The_Force_Awakens)

**Comment by UltrasonicNXT** [comment]
Fixed.
