### ISSUE TITLE
There needs to be some form of global new messages

### ISSUE THREAD

**Issue by UltrasonicNXT** [Brickimedia/brickimedia#288]
Per #254

**Comment by codynguyen1116** [comment]
Here are some references relating to this for those of you (such as @georgebarnick and @UltrasonicNXT) interested
 - Phabricator issue on Echo  https://phabricator.wikimedia.org/T108190
 - Mediawiki article on Echo and global notifications https://www.mediawiki.org/wiki/Requests_for_comment/Cross-wiki_notifications
 - CrossWatch extension with [source code available](https://git.wikimedia.org/summary/labs%2Ftools%2Fcrosswatch) but probably *too* wikimedia-specific to be modified for our project - https://meta.wikimedia.org/wiki/Crosswatch
  - https://phabricator.wikimedia.org/tag/crosswatch/

**Comment by codynguyen1116** [comment]
@UltrasonicNXT @georgebarnick 

The cross-wiki notification feature is now available to test as a beta feature on MediaWiki, it can be changed at https://www.mediawiki.org/wiki/Special:Preferences#mw-prefsection-betafeatures. Announcement is at: https://www.mediawiki.org/wiki/Topic:Syid85gemzstn58o

**Comment by neoncitylights** [comment]
Superseded by https://phabricator.wikimedia.org/T143512
