### ISSUE TITLE
1px gap in Refreshed on mobile devices after scrolling the page down

### ISSUE THREAD

**Issue by mary-kate** [Brickimedia/brickimedia#291]
See screenshot. To reproduce:
1. Open a page with the Refreshed skin (I used meta's main page)
2. Scroll down a bit
3. Look at the gap.

Tested on a Nokia X, in its default browser.

**Comment by MtMNC** [comment]
@seaside98 @mary-kate Now that we're on Refreshed 3.* has this issue been resolved?

**Comment by mary-kate** [comment]
Mostly so, yes; not fully, but I'd be willing to bet we have other, higher-priority graphical glitches to work on. In any case, here are the test results (on Nokia X):

* default browser, portrait mode -- gap is present only after scrolling to the bottom of the page and then starting to scroll (I guess "swipe" would be a more appropriate verb to use here, eh?) back up
* default browser, landscape mode -- all good here
* Firefox (v. 29.0.1...yes, I know I should upgrade), landscape -- right after you start scrolling down, there's that 1px gap...on the right side of the magnifying glass icon (!). Wtf Firefox?!

** actually this just seems to be happening on [[en:Main Page]], but not on [[en:Brickipedia:Official Friends/Requests]], for example. Maybe the MP has some buggy, page-specific CSS or something?
* Firefox, portrait -- all good here

**Comment by codynguyen1116** [comment]
Going with last two comment posted at https://github.com/Brickimedia/brickimedia/issues/295 by @mary-kate , closing this
