### ISSUE TITLE
Minor Refreshed CSS bugs on MicroB on Maemo 5 (Fremantle)

### ISSUE THREAD

**Issue by mary-kate** [Brickimedia/brickimedia#295]
Now continuing our ever-popular series of "Obscure, obsolete or otherwise odd mobile platforms that you've never heard of but that still exist and render the Refreshed skin somewhat poorly".
Device: Nokia N900
Browser: MicroB, the stock browser (based on Firefox 3.5, if memory serves me correct)

Despite that the Nokia N900 is soon almost five years old, it's a remarkable device due to many reasons. It ships with a sorta-but-not-totally-proprietary browser called MicroB, and while plenty of other browsers exist for Maemo 5 (Fremantle), many -- yours truly included -- remain loyal to MicroB.

In landscape mode -- N900 is landscape-only everywhere but in the phone app if not running the Community Seamless Software Upgrade (CSSU), a collection of patches maintained by the Maemo community -- , there are some things wrong with the div#header element.
My desktop Firefox (version 30.0 on Windows XP, 1440x1050px screen) says that ``#rightbar .shower`` has a ``background-size`` of ``48px 48px``. Maemo's MicroB on the other hand claims that it's ``auto auto``, which does not produce the correct rendering; manually setting ``background-size`` to ``48px 48px`` via jQuery by abusing the browser's address bar fixes this issue.

The Universal Language Selector is placed "behind" (!) the site drop-down menu and it's missing the background image...and, as a matter of fact, .uls-trigger has plenty of inline styles in desktop Firefox 30.0, but none under MicroB; not even the padding-left one! I'm not sure what is causing this; according to desktop Firefox 30.0, the source image is a(n) .svg one (and MicroB apparently doesn't support the .svg file format, if the Wikipedia page's anything to go by), but than again it renders in Internet Explorer 8, and as we all all know all too well, IE8 most certainly doesn't support .svgs.

Finally, ``div#siteinfo-main a.arrow-link`` appears to be misplaced. This has something to do with its ``padding``, but I wasn't able to figure out exactly what...

A screenshot from my N900, illustrating all the described defects, can be found at http://images.brickimedia.org/a/a3/Refreshed_on_Maemo_5_MicroB_browser.png

**Comment by MtMNC** [comment]
Currently menus that overflow are hidden--maybe we can change it so there's a "more" link at some point but I don't think that's very high priority.

@mary-kate How does Refreshed look in MicroB currently?

**Comment by mary-kate** [comment]
@MtMNC Funny should you ask, because I just took a screenshot earlier today and was intending on sharing it with y'all here. ;-)
![screenshot-20150612-183940](https://cloud.githubusercontent.com/assets/2213994/8140176/e0448682-1161-11e5-8d0c-08a8985a5fc0.png)

* Ideas' and GBC's logos don't seem to be showing up
* The little "down" arrows aren't showing up either (just like on IE11 under Win7 on desktop)
* The three "major" menus (Current themes x2 + Community) aren't showing up either; it's due to the low resolution, no doubt, but I'd assume that at least *one* of 'em would fit in the available screen real estate?
* The magnifying glass icon isn't showing up either

**Comment by MtMNC** [comment]
Ew. :P Looks like it doesn't even support border-radius! And according to Wikipedia it doesn't support SVGs either, but it seems to be working with some of them... weird. As with IE (https://github.com/Brickimedia/brickimedia/issues/382), it seems fonts are a big issue here.

**Comment by codynguyen1116** [comment]
@mary-kate Is this still an issue?

**Comment by mary-kate** [comment]
@codynguyen1116 Likely, yes. I tried testing this but good ol' N900 wouldn't even load Brickimedia this time around. As much as I love the Nokia N900 and the Maemo OS, the sad truth is that the platform is beginning to show its age ([Wikipedia](https://en.wikipedia.org/wiki/Nokia_N900) notes that the N900 was launched in late 2009, which is an eternity ago by Internet standards) not to mention that Maemo was _always_ somewhat of a niche OS. Over six years later, Nokia isn't even in the smartphone business anymore and while Maemo still has a small but active community, it's hard to work around certain artificial limitations (namely that many important modules and other parts of the OS are closed-source and need to be reverse-engineered, but only a handful of people understand the OS and/or the hardware well enough to be able to do that).
The [Neo900](http://neo900.org/specs), which is essentially a hardware refresh of the Nokia N900 "by geeks, for geeks" is an interesting project, but at the same time it retains many of the N900's faults (namely the WVGA screen, low-end cameras to name a few) and combined with a hefty price tag...you gotta be a rich geek to buy that thing, as interesting as it might be.

As much as I hate saying this, we probably should focus our limited resources on the more "commercially viable" platforms, i.e. Android/iOS/Windows Phone + whatever niche platforms we can support and which still have vendor support ([Jolla's](https://en.wikipedia.org/wiki/Jolla) [Sailfish OS](https://en.wikipedia.org/wiki/Sailfish_OS) comes to mind for one)...

**Comment by codynguyen1116** [comment]
Yeah, hate to say it too but I have to agree. :( I'm going to close this
