### ISSUE TITLE
Splash page avatar check doesn't fail gracefully

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#296]
The method of retrieving avatars on the splash page, implemented it Brickimedia/splash#16, does not fail gracefully and throws up an error on every failed avatar extension check. I think a cleaner way to do this would be to use JavaScript's <a href="//developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch">try...catch</a> statement.

**Comment by MtMNC** [comment]
Something to look at in https://github.com/Brickimedia/brickimedia/issues/415
