### ISSUE TITLE
Search bar vertical margin looks wrong

### ISSUE THREAD

**Issue by lachlanshanks** [Brickimedia/brickimedia#304]
With the update to Google Chrome 38, the search bar now appears off-center vertically. I had noticed this bug in Firefox and Internet Explorer earlier but now I see it in Google Chrome too.

Interestingly, the search bar looks fine in Opera desktop.

**Comment by MtMNC** [comment]
Way late, but as of the latest commit the search seems centered properly on Chrome 41, Firefox 36, and Safari 8. Anyone mind if I close this?

**Comment by codyn329** [comment]
I don't mind, go ahead (unless if there's anyone else out there that wants to)

**Comment by MtMNC** [comment]
Alright, apparently there's a distinction between locking and closing issues. Let's see if this does it: fixed https://github.com/Brickimedia/Refreshed/commit/1687371ade0a05b825c755c40d4517247e972e89

**Comment by georgebarnick** [comment]
There should be a "Close issue" button next to the comment.

**Comment by MtMNC** [comment]
Ugh, of course it was right there in front of me. :P Thanks.
