### ISSUE TITLE
Removing the Lia Skin

### ISSUE THREAD

**Issue by Drewlzoo** [Brickimedia/brickimedia#305]
Hello everyone, sorry I haven't been around lately. I've had a busy summer, and I don't know that I'll have enough time to be of much help anymore. One thing I just wanted to quickly recommend, though, is that the Lia skin be removed. It uses the old skin detection tool, so if it needs deleted to be removed, feel free to do so. The skin hasn't functioned properly since the original Brickimedia in 2013, and it hasn't functioned at all since around the start of this year. I doubt anyone has much interest in using it, and I don't have any interest in maintaining it, so it's pretty much completely useless.

**Comment by MtMNC** [comment]
Lia's been removed, so closing.
