### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by SirKnight1234** [Brickimedia/brickimedia#306]
So my old computer broke and I had to change. I forgot my password for 'Media, but remembered my email's password and changed it. But I'm only logged in a few wikis. When I change wikis, it logs me out, and my password doesn't work on every wiki.

**Comment by codynguyen1116** [comment]
@SirKnight1234, @Seahorseruler Is this still a problem?

**Comment by codynguyen1116** [comment]
```
04:04, 6 February 2016 Awesomeknight (Talk | contribs): nope not a problem anymore
04:06, 6 February 2016 Awesomeknight (Talk | contribs): thanks for responding after 4 months
```

no problemo
