### ISSUE TITLE
Add desktop notifications to chat

### ISSUE THREAD

**Issue by UltrasonicNXT** [Brickimedia/brickimedia#313]
http://stackoverflow.com/questions/2271156/chrome-desktop-notification-example

**Comment by georgebarnick** [comment]
Thanks. :)

**Comment by UltrasonicNXT** [comment]
https://gerrit.wikimedia.org/r/#/c/184227/

**Comment by UltrasonicNXT** [comment]
Done

**Comment by georgebarnick** [comment]
Can we have "Show a notification receiving normal messages" unset by default? It's rather annoying in an active chat and some people don't know that that preference is set by default.

**Comment by UltrasonicNXT** [comment]
Done.

**Comment by codyn329** [comment]
Whenever someone joins it says "undefined" instead of "<username> has joined chat".

**Comment by UltrasonicNXT** [comment]
Ooh does it, I'll have an investigate

**Comment by UltrasonicNXT** [comment]
FIxed.
