### ISSUE TITLE
NumerAlpha extension

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#314]
Would it be possible to install [Extension:NumerAlpha] (http://www.mediawiki.org/wiki/Extension:NumerAlpha) on en? I'm reworking the way we do inventory and parts pages at the moment to make things much easier. Basically unless I drastically change the way we currently make inventories right now, I need to generate unique identifiers to group sets of related data into Semantic MediaWiki subobjects. @Ajraddatz has said that the extension's still in a beta phase, I don't know if that's a problem at all.

**Comment by UltrasonicNXT** [comment]
Done.
