### ISSUE TITLE
Monobook broken

### ISSUE THREAD

**Issue by ALittleSlow** [Brickimedia/brickimedia#315]
Just logged in to Brickimedia after a long time away. But when I use the Monobook skin, only the background image and banner appear. Tested in IE and Firefox on Windows 8.1. I added ?useskin=vector to the end of all my URLs just to get to my user preferences to change my skin. ALittleSlow (talk) 01:45, 9 January 2015 (UTC) 

ToaMeiko responds: Pretty sure it'd have to do with the recent MediaWiki 1.24 update rather then the yet-to-be-deployed Refreshed update. Can you report it at github:new so that the sysadmins will see it? --ToaMeiko (talk) 01:48, 9 January 2015 (UTC)

**Comment by UltrasonicNXT** [comment]
Fixed. Monobook was on a 1.25 dev version, which is not compatible with our 1.24 release version of MW core.
