### ISSUE TITLE
Unable to leave notes on ArticleFeedback

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#317]
Leaving notes through the article feedback extension no longer seems to work, it's been broken for the last month or so.

**Comment by Brikkyy13** [comment]
This is still broken (bump)

**Comment by UltrasonicNXT** [comment]
I just managed this: http://en.brickimedia.org/index.php?title=Special:ArticleFeedbackv5/76039_Ant-Man_Final_Battle&ref=cta#0531942d873197e9ad01f902f6477168. Is that what we are talking about?

**Comment by Brikkyy13** [comment]
No. After you mark the feedback you can click "add note" to add a comment to let people know stuff. You used do be able to do it up until around November 2014

**Comment by UltrasonicNXT** [comment]
Okay I see

**Comment by UltrasonicNXT** [comment]
JS error: ```Error: Syntax error, unrecognized expression: #articleFeedbackv5-filter-select option[value=]```

**Comment by Brikkyy13** [comment]
In addition to this issue, the unreviewed section of this page is inaccessible. 
http://en.brickimedia.org/wiki/Special:ArticleFeedbackv5

**Comment by UltrasonicNXT** [comment]
```Error: Syntax error, unrecognized expression: #articleFeedbackv5-filter-select option[value=]``` same error.

**Comment by UltrasonicNXT** [comment]
https://gerrit.wikimedia.org/r/#/c/200518/ patch submitted

**Comment by UltrasonicNXT** [comment]
Right, the unreviewed section not working is fixed.

**Comment by UltrasonicNXT** [comment]
Adding notes patch submitted: https://gerrit.wikimedia.org/r/#/c/200638/

**Comment by UltrasonicNXT** [comment]
Done.
