### ISSUE TITLE
Website down/offline

### ISSUE THREAD

**Issue by Brikkyy13** [Brickimedia/brickimedia#318]
At around 12pm Jan 14 2015 while trying to access the website I was given the "Error 502 - Bad gateway" message. This is not the first time it has happened.

**Comment by MtMNC** [comment]
FWIW I'm getting this right now.

**Comment by MtMNC** [comment]
Everything's fine now.

**Comment by codyn329** [comment]
Old issue and already fixed, suggest this should be closed
