### ISSUE TITLE
LEGO Ideas Wiki logo won't appear on Refreshed

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#319]
It won't appear for some reason, I don't know why.

![image](https://cloud.githubusercontent.com/assets/4723983/5788245/b24a55bc-9def-11e4-97a8-ba3999472a14.png)

**Comment by georgebarnick** [comment]
Because http://en.brickimedia.org/skins/Refreshed/refreshed/images/ideas.svg and http://en.brickimedia.org/skins/Refreshed/refreshed/images/ideas.png are missing on ```refreshed-beta``` branch.

**Comment by mary-kate** [comment]
This is fixed in git (see https://github.com/Brickimedia/Refreshed/commit/d5aad0257121626849fd4cc7d1ebaf8d7b5d7e44), although the fix isn't live yet.

**Comment by codyn329** [comment]
OK, thanks Kate! I was just wondering though since it's been 2 days - is this fix actually functional because it's been 2 days and I'm not sure if it's just a slow cache or it just plain out not working?

**Comment by codyn329** [comment]
Error relating to image via console: "Failed to load resource: the server responded with a status of 404 (Not Found)" http://ideas.brickimedia.org/skins/Refreshed/refreshed/images/ideas.svg

**Comment by georgebarnick** [comment]
Because @mary-kate's change was never pulled to the server. Anyways, I've gone ahead and done that so it'll be fixed now. I shouldn't be doing this since I've stepped down from sysadmin and all my other positions...
