### ISSUE TITLE
Echo messages appear white on refreshed

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#322]
They're appearing white via code <code>.header-dropdown-item a { color: #fff; }</code> because the text is under the parent <code><a class="mw-echo-notification-wrapper"></code>. I would fix it but I don't know where the refreshed-beta branch (nor do I have access to it I think?) is so I was hoping someone who has access to it could fix it.

![image](https://cloud.githubusercontent.com/assets/4723983/5791145/d41bc9c0-9e83-11e4-8dd0-58da06dece3a.png)

Here with the declaration disabled:

![image](https://cloud.githubusercontent.com/assets/4723983/5791148/fbbf797c-9e83-11e4-843c-7d23a1c07283.png)

**Comment by georgebarnick** [comment]
You'll have access to the ```refreshed-beta``` branch if you have access to any other branches on the Refreshed repository. You can get the ```refreshed-beta``` branch by running ```git clone -b refreshed-beta https://github.com/Brickimedia/Refreshed.git``` or if you already have it cloned you can run ```git checkout refreshed-beta```. The ```refreshed-beta``` branch is accessible at https://github.com/Brickimedia/Refreshed/tree/refreshed-beta

**Comment by UltrasonicNXT** [comment]
Hmm it looks like Echo needs some more work, the arrow (between the echo box and the notifications number) doesn't align with the box, that doesn't look great.

**Comment by codyn329** [comment]
Also Special:Notifications is broken (somewhat at the very top)

![image](https://cloud.githubusercontent.com/assets/4723983/5848633/4556d5a2-a1a0-11e4-9579-88cf40ccc268.png)

**Comment by MtMNC** [comment]
The dropdown has been fixed per https://github.com/Brickimedia/brickimedia/issues/396#issuecomment-109324265. Regarding Special:Notifications, I'm closing this in favor of https://github.com/Brickimedia/brickimedia/issues/395.
