### ISSUE TITLE
Wikiforum formatting problems

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#323]
It seems in the last 24 hours, some formatting problems have come up in the wikiforum, see [here] (http://en.brickimedia.org/wiki/Special:WikiForum/Super_Heroes_2015) for an example- instead of headers, it's just text surrounded by equals signs, and sometimes there's the odd box that looks like a pre tag is used.

**Comment by UltrasonicNXT** [comment]
hmm this is strange

**Comment by UltrasonicNXT** [comment]
Fixed,
