### ISSUE TITLE
skins not showing in gbc.brickimedia.org

### ISSUE THREAD

**Issue by ALittleSlow** [Brickimedia/brickimedia#328]
In the new developmental gbc site, skins are not showing in Firefox, ~~but they are in IE~~ nor IE. ?useskin=monobook works in Firefox, however. Guessing it's related to [Class_SkinStandard_not_found] (http://www.mediawiki.org/wiki/Manual:Errors_and_symptoms#Class_SkinStandard_not_found.3B_skipped_loading ) ?

**Comment by UltrasonicNXT** [comment]
Refreshed is working for me on both Chrome and IE.

**Comment by ALittleSlow** [comment]
All but DeepSea are now working for me.

**Comment by UltrasonicNXT** [comment]
Fixed. Go for adding site CSS to MediaWiki:Deepsea.css. (The current system is old and outdated, I'm going to remove it.)
