### ISSUE TITLE
Brickipedia's down

### ISSUE THREAD

**Issue by SirKnight1234** [Brickimedia/brickimedia#330]
What happened?

**Comment by codyn329** [comment]
It's the Brickimedia network as a whole; the server is down.

**Comment by SirKnight1234** [comment]
Why's the server down?

**Comment by codyn329** [comment]
https://support.cloudflare.com/hc/en-us/articles/200171846-Why-am-I-getting-a-cloudflare-nginx-502-or-504-gateway-error-

**Comment by SirKnight1234** [comment]
Who owns the server?

**Comment by UltrasonicNXT** [comment]
Nah http://brickimedia.org/ is up, meaning it's something wrong with PHP somewhere I think, @lewiscawte might know more.

**Comment by lewiscawte** [comment]
Sorted. Next time, a Skype message or IRC ping really would of been
preferred, luckily I was looking at my emails and saw this...

**Comment by UltrasonicNXT** [comment]
Ok sure, @lewiscawte what do you have to do to fix? Is it tricky?
