### ISSUE TITLE
Change cache time of MediaWiki:Refreshed-navigation

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#331]
I made a change at http://en.brickimedia.org/index.php?title=MediaWiki:Refreshed-navigation&diff=956783&oldid=956143 on Mediawiki:Refreshed-navigation about a week ago, and it still hasn't gone through- Meiko said on the Refreshed forum on Bricki it was due to caching, so is there any chance of making the cache a little shorter?

**Comment by codyn329** [comment]
Yes please, it's happening the same at LEGO Ideas Wiki and it's been about 10 days. http://ideas.brickimedia.org/index.php?diff=18229

**Comment by UltrasonicNXT** [comment]
Hmm, the code is copied from Wikia...!!! I'll have a look.

**Comment by georgebarnick** [comment]
The code is actually adapted from ShoutWiki which was adapted from Wikia.

**Comment by UltrasonicNXT** [comment]
urgh I might just delete it all and write new code, there's nothing worse than code that was written years ago

**Comment by UltrasonicNXT** [comment]
Done, much better code now.
