### ISSUE TITLE
Re-disable article feedback in "Brickipedia news:" namespace

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#332]
The article feedback tool seems to be running again in the news namespace on the news namespace when it shouldn't be. Would someone please be able to disable it again?

**Comment by georgebarnick** [comment]
Just add a ```display:none``` line for the namespace and the article feedback element in <a href="http://en.brickimedia.org/wiki/MediaWiki:Common.css">MediaWiki:Common.css</a> like you see for the Review namespace.
