### ISSUE TITLE
Clicking "Projects" doesn't open up sub-menu on LEGO Ideas Wiki

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#333]
Clicking the "Projects" category on the refreshed menu won't open up a sub-menu on LEGO Ideas Wiki. The current diff on MediaWiki:Refreshed-navigation is 18299. http://ideas.brickimedia.org/index.php?diff=18229

![image](https://cloud.githubusercontent.com/assets/4723983/6012176/a0b7f430-ab0a-11e4-9b96-df5ca27b40e5.png)

**Comment by georgebarnick** [comment]
You need to pipe each entry. ```$1|$2``` = ```link|text```, so it's only understanding the link and doesn't have text to display in a dropdown. Needs UX enhancement so that this is more intuitive and doesn't require piping, but for now if you pipe it ```Current Projects|Current Projects``` it'll work.

**Comment by UltrasonicNXT** [comment]
You do not need to pipe each element, I made the code much more sensible a few days ago so this is no longer necessary. I'll look into it.
