### ISSUE TITLE
Change access of nuke

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#335]
(sorry if this shouldn't go here, I'm not sure where I'm meant to request this)

As per a recent forum on Bricki, would someone mind changing it so that admins on en no longer have the "nuke" user right, but instead give it to functionaries?

**Comment by UltrasonicNXT** [comment]
Done

**Comment by georgebarnick** [comment]
This request was to make this change on en.brickimedia.org only. Other projects haven't had any vote on this user rights change so it shouldn't be changed for all projects.

**Comment by mary-kate** [comment]
Code change done, not deployed yet.
