### ISSUE TITLE
Refreshed user submenu messed up

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#336]
Language list item doesn't appear on the menu, rather on the side
![image](https://cloud.githubusercontent.com/assets/4723983/6090953/38a89b78-ae58-11e4-981c-a47bd89841fe.png)

**Comment by mary-kate** [comment]
The ``#pt-uls`` element had ``position: absolute`` -- no idea where that's coming from, but I changed it to ``position: static`` locally (see http://meta.brickimedia.org/index.php?title=MediaWiki%3ARefreshed.css&diff=208408&oldid=174914) and that seems to have fixed it.
