### ISSUE TITLE
inputbox breaks pages

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#337]
Inputbox tags will screw up pages and make the page blank.

**Comment by UltrasonicNXT** [comment]
Have you got a link? Working (here)[http://dev.brickimedia.org/wiki/Inputbox]

**Comment by codyn329** [comment]
Actually no, but I think it might just be because I'm using <code>type=search</code>. That's what type I tried while I was attempting to use inputbox.

**Comment by UltrasonicNXT** [comment]
Fixed.
