### ISSUE TITLE
Buttons not working on mobile 

### ISSUE THREAD

**Issue by lachlanshanks** [Brickimedia/brickimedia#338]
In the refreshed skin the buttons (edit,  talk etc)  aren't reacting on Brickipedia.  Im using Chrome 40 on a motorola moto g 2014.

**Comment by codynguyen1116** [comment]
@lachlanshanks Is this still an issue?

**Comment by chriscook18** [comment]
Work fine on Chrome 47 Android 4.3 on S3

**Comment by lachlanshanks** [comment]
They're working fine now (same device as before). I can't remember what was happening beforehand but now they're fine.

**Comment by codynguyen1116** [comment]
Ah good! I'll close this issue then
