### ISSUE TITLE
UploadWizard has no content on learn tab

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#339]
UploadWizard has no content for the Learn tab. There should be something so it actually has use, and could help newer users who don't know how to use it.

![image](https://cloud.githubusercontent.com/assets/4723983/6204710/7838e956-b519-11e4-8210-5238f3e618a3.png)

**Comment by Edward-Nigma** [comment]
I agree. This has been an issue for over a year, actually. Not sure why it was never brought up.

**Comment by georgebarnick** [comment]
UploadWizard is very WMF specific, and no longer benefits users now that MultiUpload has been redeveloped. I'd suggest we just remove UploadWizard altogether...

**Comment by UltrasonicNXT** [comment]
Right the docs are poor, but I'm on this

**Comment by UltrasonicNXT** [comment]
auurhghd it's messy

**Comment by georgebarnick** [comment]
...or can we just remove UploadWizard?

**Comment by UltrasonicNXT** [comment]
yeah this is what I'm implying

**Comment by UltrasonicNXT** [comment]
But MultipleUpload isn't working?

**Comment by codynguyen1116** [comment]
UploadWizard was uninstalled in https://github.com/Brickimedia/LocalSettings/commit/b23d5fe14efa7fb138e8ef2b339ea2a5fa62e36c
