### ISSUE TITLE
greatballcontraption.com returns "technical problems"

### ISSUE THREAD

**Issue by ALittleSlow** [Brickimedia/brickimedia#340]
I think someone is working on mapping greatballcontraption.com to gbc.brickimedia.com, but I thought I should follow the process and file an issue.

Pointing my browser to http://www.greatballcontraption.com or http://greatballcontraption.com currently returns the page "Brickimedia is currently experiencing technical problems".

**Comment by UltrasonicNXT** [comment]
Yeah, I've seen this, no clue where it's coming from though :/

**Comment by ALittleSlow** [comment]
I don't think it's getting as far as LocalSettings.php. Maybe it's happening before it gets to PHP. Might be a clue in the httpd log.

**Comment by UltrasonicNXT** [comment]
There's nothing in nginx's error log

**Comment by ALittleSlow** [comment]
It's a minor data point, but foo.greatballcontraption.com returns the same message. I know I'm grasping, but could it be at the name server?

**Comment by lewiscawte** [comment]
Give me a couple of days and I'll take a look.

**Comment by ALittleSlow** [comment]
Any news? Anything I can do? Willing to pay somebody if it helps.

**Comment by lewiscawte** [comment]
Did I say a couple of days? Uhh... same again. This weekend (providing I remember)

**Comment by lewiscawte** [comment]
Scratch that. Just sorted it. If you have money to spare, I'll name a charity or two that you can make a donation to instead for the work. We're all volunteers here :)

**Comment by georgebarnick** [comment]
All seems to be working now!

**Comment by ALittleSlow** [comment]
@lewiscawte , perhaps I fall into the "more money than sense" category, but NAME YOUR CHARITY!

**Comment by georgebarnick** [comment]
Help me pay for my car! ^_^ lol jk

**Comment by ALittleSlow** [comment]
@georgebarnick is it made of LEGO bricks? I have a budget for that...

**Comment by georgebarnick** [comment]
Unfortunately not :(
