### ISSUE TITLE
Chat not scrolling at new messages

### ISSUE THREAD

**Issue by LK901** [Brickimedia/brickimedia#343]
Title says it all.
DETAILS:
Firefox 35.0
Ubuntu 12.04

Source inspector message:

"Use of "addOnloadHook" is deprecated. Use jQuery instead." load.php:17
console.trace(): load.php:17
mw.log</log.warn() load.php:17
mw.log</log.deprecate</<.get() load.php:17
<anonymous> load.php:1

**Comment by georgebarnick** [comment]
I can confirm this is also happening in Chrome 40 on Windows 7 in Refreshed skin. I'd assume it was caused by something in wikimedia/mediawiki-extensions-MediaWikiChat@df52ea8 because it seemed to work fine until Brickimedia/extensions@84e6d42.

**Comment by UltrasonicNXT** [comment]
Fixed.

**Comment by codyn329** [comment]
Someone reopoen please

**Comment by UltrasonicNXT** [comment]
Give me more details if you are experiencing this please?

**Comment by georgebarnick** [comment]
For me, it seems to only autoscroll rarely in Chrome (latest). Don't really have any other details.

**Comment by UltrasonicNXT** [comment]
Okay this just hit me, after a while inactive in the chat, no JS errors

**Comment by georgebarnick** [comment]
For what it's worth, I don't think it was ever fixed for anyone even after this was closed.

**Comment by UltrasonicNXT** [comment]
yeah looks like it. I've got a fix coming

**Comment by UltrasonicNXT** [comment]
Right running out of time now, I'll have to finish this tommorrow

**Comment by UltrasonicNXT** [comment]
Right, this should be sorted now
