### ISSUE TITLE
Stored ratings

### ISSUE THREAD

**Issue by VWBeetle** [Brickimedia/brickimedia#345]
Despite the fact that [this disambiguation page](http://customs.brickimedia.org/wiki/Venom) lacks a rating tag, it shows up as unrated [here](http://customs.brickimedia.org/wiki/Special:MassRatings?un=true). Apparently it stored data from [this](http://customs.brickimedia.org/index.php?title=Special:Log&page=Venom).

**Comment by codynguyen1116** [comment]
Uh, is this still an issue? Is there a way to test this, since Customs have been moved to the fan namespace?

**Comment by georgebarnick** [comment]
Yes this is still an issue and it's not specific to Customs.

**Comment by neoncitylights** [comment]
Brickimedia no longer uses GitHub as an issue tracker.
