### ISSUE TITLE
Comments say they're mine when they aren't

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#346]
I looked at some comments today on a blog where user 1999bug commented, but on the "vote" area of the comment, it says it's my comment.

![image](https://cloud.githubusercontent.com/assets/3800972/6549102/7e2ae726-c5e3-11e4-8658-604971ff84ed.png)

**Comment by UltrasonicNXT** [comment]
Can I get a link to this blog?

**Comment by georgebarnick** [comment]
http://en.brickimedia.org/wiki/User_blog:Ichindar/Tell_LEGO_to_cut_ties_with_Shell!#comment-3665

and it's not doing it anymore... Issue should stay open though until we know what caused this and fix it

**Comment by NovaFlare** [comment]
This has been happening for a long time on all blogs, not just the one mentioned above. The person that shows up as "You" is the person who was the last to make a comment.

**Comment by mary-kate** [comment]
Can confirm, too; on http://en.brickimedia.org/wiki/Brickipedia_News:Disney_purchases_The_LEGO_Group the newest comment, posted 1h15mins ago by MtMNC ("I for one welcome our new mouse-eared overlords.") is marked as my comment, meaning that I can't vote for it.

**Comment by MtMNC** [comment]
Yup. Newest comment (no longer by me) says it's by me. I was able to vote for myself too (is that normal?), and when I did it said the comment had two votes but I'm pretty sure it said zero before.

**Comment by codynguyen1116** [comment]
@georgebarnick Can you check if this still an issue, or is it safe to close this?

**Comment by georgebarnick** [comment]
It is. Comments are cached too aggressively and only are reset once someone comments. So until someone else comments, any comments made by the last commenter are labeled as "You" for anyone who views them.

**Comment by UltrasonicNXT** [comment]
I seem to remember I put a patch into this, not sure what happened
