### ISSUE TITLE
category text overflowing

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#349]
![image](https://cloud.githubusercontent.com/assets/4723983/6630143/9a14294a-c8e3-11e4-9711-116db27e05b4.png)

Category text is overflowing on this page.

**Comment by MtMNC** [comment]
The catlinks element is normally rendered inside the content element but it's not on Camotoy's page, which means there's an extra closing tag somewhere. I see two tables on the page but only one of them is closed; methinks that's the problem. ;)

That means it's an issue with page content, not with Refreshed. That said, it looks fine in Vector, so I'm gonna leave this open until we get it to render categories correctly even with bad content.

**Comment by MtMNC** [comment]
I've left Camotoy a message on how to fix the category overflow.

Also, I've taken a closer look at the page source, and even though the categories look fine on Vector, the HTML has the same issues in both skins. Forgetting to close tags (or closing too many) can break pages regardless of what skin you use; maybe it'd be better to leave the skin as-is as opposed to letting users use improper HTML without there being any consequences. Thoughts?

**Comment by UltrasonicNXT** [comment]
Yeah this should be fixed in the wikitext.
