### ISSUE TITLE
MultimediaViewer won't load thumbnail data

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#350]
![image](https://cloud.githubusercontent.com/assets/4723983/6631241/c85326dc-c8f0-11e4-87c8-c4118de65447.png)

**Comment by georgebarnick** [comment]
Is this a recurring problem for you? I'm not able to reproduce this. It's likely it just failed on your end that onetime, which isn't really a bug.

**Comment by codyn329** [comment]
Nevermind, yeah, it's working on all wikis this time.
