### ISSUE TITLE
Better print-friendly articles

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#353]
Remove user avatar, sidebar, and wiki logo for printing (on refreshed)
![image](https://cloud.githubusercontent.com/assets/4723983/6658390/b1feca84-cb35-11e4-9601-e28134770fd7.png)

Remove search area and get content to move under infobox (deepsea)
![image](https://cloud.githubusercontent.com/assets/4723983/6658408/8db2f834-cb36-11e4-8174-4d4e851cbe56.png)
![image](https://cloud.githubusercontent.com/assets/4723983/6658426/dba80aca-cb36-11e4-92db-84d4eccc629e.png)

**Comment by codyn329** [comment]
Should be fixed now via http://meta.brickimedia.org/wiki/MediaWiki:Print.css (Then the other wikis can just import the stylesheet from meta), will close

**Comment by UltrasonicNXT** [comment]
Ah didn't know Print.css was a thing, nice one
