### ISSUE TITLE
Have WikiForum support Echo notifications

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#355]
WikiForum should support Echo notifications such as when a user replies to the thread that another user is following or have previously posted in.

**Comment by georgebarnick** [comment]
See #257 and https://phabricator.wikimedia.org/T64520

**Comment by ALittleSlow** [comment]
Would this enhancement enable subscription to E-mail notification of new posts to a forum? I would really like this feature or an equivalent.

**Comment by georgebarnick** [comment]
@ALittleSlow: Possibly.

**Comment by UltrasonicNXT** [comment]
Yeah, Echo has handling for emails, if this does happen emails will go with it.

**Comment by UltrasonicNXT** [comment]
Right I started work here: https://gerrit.wikimedia.org/r/#/c/215107/, but with very poor docs this is gonna be a long process

**Comment by UltrasonicNXT** [comment]
Do we think these should be opt-in or opt-out?

**Comment by ALittleSlow** [comment]
Personal preference is opt-out. Preference as a sysadmin would be to give me the choice in LocalSettings.ini.

**Comment by UltrasonicNXT** [comment]
It will definitely be a preference in your user preferences (I don't have control over that). I'm leaning towards opt-out, although the MW docs recommend being opt-in (I might just ignore them though XD).

**Comment by georgebarnick** [comment]
I'd suggest have them opt-in, but if possible, we should configure it so that it's opt-out in LocalSettings_gbc.php since that's a wiki that's primarily WikiForum-based. Any other wikis I think should be opt-in though.

**Comment by UltrasonicNXT** [comment]
Only problem is, I think if it is opt-in, very few people will actually know it exists

**Comment by UltrasonicNXT** [comment]
(That config should be possible though)

**Comment by codyn329** [comment]
closing because duplicate of https://github.com/Brickimedia/brickimedia/issues/257
