### ISSUE TITLE
Chat iOS push notifications

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#358]
Just an idea, this would be pretty neat since I do use chat sometimes on a phone. It would work pretty similarly to desktop notifications, except this it's a push notification.

**Comment by georgebarnick** [comment]
I'm fairly certain this isn't possible.

**Comment by UltrasonicNXT** [comment]
What exactly are iOS push notifications?

**Comment by georgebarnick** [comment]
https://developer.apple.com/notifications/

**Comment by UltrasonicNXT** [comment]
hmm sounds like they can only be done for apps?

**Comment by georgebarnick** [comment]
Yeah, that's what I was fairly certain of.
