### ISSUE TITLE
meta throws fatal errors on every page

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#359]
![image](https://cloud.githubusercontent.com/assets/4723983/6877937/56d0d95e-d4a4-11e4-82fd-01142fd846e3.png)

**Comment by UltrasonicNXT** [comment]
It's extension:translate again, which I've disabled for the mo, to fix meta https://github.com/Brickimedia/LocalSettings/commit/7450f5a725e75ca45584420b1e3936fad806b737

**Comment by SirComputer1** [comment]
Forum:Index is still broken - probably other custom namespaced pages too. Other pages seem fine.

**Comment by codyn329** [comment]
@SirComputer1 looks like it's working, so I'm closing
