### ISSUE TITLE
Problems with echo

### ISSUE THREAD

**Issue by UltrasonicNXT** [Brickimedia/brickimedia#362]
I still see a red 1 next to my username, indicating I have a notification, but I haven't received a notification for about a month. When I open the dropdown, all of the notifications are marked as read (not bold).

**Comment by georgebarnick** [comment]
If you visit Special:Notifications it should go away. But it should go away when clicking, but appears to have not performed this correct behavior since Refreshed 3.0 was rolled out.

**Comment by codynguyen1116** [comment]
Echo has updated so I assume this isn't an issue anymore, can this be closed? (trying to help clean out old issues that aren't relevant anymore)
