### ISSUE TITLE
Can't access WikiForum threads with special characters in title

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#363]
The "Help ! 8 Year old very interested in building GBC but mom knows nothing about them" thread is inaccessible. http://greatballcontraption.com/index.php?title=Special:WikiForum&forum=3

**Comment by mary-kate** [comment]
Apparently WikiForum fails to `trim()` the user-supplied input when inserting it into the database...so the DB entry has a trailing space, but MW is smart and trims such things from the URL and thinks you're trying to access a thread called `"Help ! 8 Year old very interested in building GBC but mom knows nothing about them"` even though its name in the database is `"Help ! 8 Year old very interested in building GBC but mom knows nothing about them "` (note the trailing space after the word "them").

I fixed this particular thread with a simple SQL query (thanks @skizzerz for teaching me that MySQL has a `TRIM()` function, too :-), `UPDATE wikiforum_threads SET wft_thread_name = TRIM(wft_thread_name) WHERE wft_thread = 23;`, but we still need to fix the underlying cause.

**Comment by UltrasonicNXT** [comment]
@mary-kate do you think literally just a ```trim()``` will do? Possibly alarmingly, it looks like there isn't any preprocessing on the title at all..!

**Comment by mary-kate** [comment]
@UltrasonicNXT A literal `trim()` on the right place should do the trick for *this* particular issue, but we'll want to be smart and take other edge cases into consideration...the `Title` class has a static `legalChars` method (which is just a wrapper around the global `$wgLegalTitleChars`, but in some magic, distant future MediaWiki will support a database-backed configuration system and globals will cease to exist as we know them); should probably use that method + some regex magic...although looking at `WFThread::add()` (http://git.wikimedia.org/blob/mediawiki%2Fextensions%2FWikiForum/96fe03c22ba4fd1480ff1cfa113461b4d66b9ca0/Thread.php#L793) it seems to make use of that already, so I'm not sure what's going on here.

**Comment by UltrasonicNXT** [comment]
Done. Yeah, I remember now, at the mo, it blocks the creation of any title containing any character not in LegalTitleChars
