### ISSUE TITLE
data on circles of splash page won't display

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#364]
I'm thinking because it's something related to this 3rd error in the console (just a wild guess)
![image](https://cloud.githubusercontent.com/assets/4723983/6994263/39e089ae-dad8-11e4-91e1-051e150fb287.png)

**Comment by MtMNC** [comment]
I think it doesn't like that we're running API calls on a site from another domain (i.e., greatballcontraption.com instead of brickimedia.org). I'm not sure how we could fix that though.

**Comment by codyn329** [comment]
Is there a different method we could possibly use that we don't know of / not thinking of yet?

**Comment by seaside98** [comment]
greatballcontraption needs to whitelist our domain in their local settings for it to work.
```$wgCrossSiteAJAXdomains = array( 'brickimedia.org', 'www.brickimedia.org' );```

**Comment by codyn329** [comment]
What about http://brickimedia.org/?

**Comment by seaside98** [comment]
Turned out to just be an issue with the redirect from ```gbc.brickimedia.org```.

**Comment by codyn329** [comment]
Can this be reopened? It's working on http://www.brickimedia.org/ but not on http://brickimedia.org/

**Comment by codyn329** [comment]
bump

**Comment by seaside98** [comment]
It's just a caching issue, the second one only updates like once a year or something absurd like that. We had that problem with earlier versions.

**Comment by seaside98** [comment]
If @georgebarnick is OK with it, we *can* override Cloudflare's (not the client's) cache...

**Comment by georgebarnick** [comment]
You'd have to ask @lewiscawte or @UltrasonicNXT

**Comment by seaside98** [comment]
It's just a matter of changing the URL to http://brickimedia.org/splash.js?=

**Comment by lewiscawte** [comment]
No it's not. I'm pretty sure that's cached as well.

**Comment by seaside98** [comment]
According to [CloudFlare support](https://support.cloudflare.com/hc/en-us/articles/200169556-How-can-I-tell-if-CloudFlare-is-caching-my-site-or-a-specific-file-), ```CF-Cache-Status: HIT ``` means the file is cached and ```CF-Cache-Status: MISS ``` means it is not.

![image](https://cloud.githubusercontent.com/assets/6372893/7115442/6296d2c2-e1ae-11e4-8530-5794b4e21248.jpg)
