### ISSUE TITLE
Some registered users' usernames are showing up as my IP address on WikiForum

### ISSUE THREAD

**Issue by mary-kate** [Brickimedia/brickimedia#365]
On http://en.brickimedia.org/wiki/Special:WikiForum/Brickipedia_has_launched! the two messages posted between @UltrasonicNXT 's and @georgebarnick 's are showing up as being posted by my current IP address, even though they're obviously not, as witnessed by the custom avatars.

Judging by avatar file names, the user who posted right below UltrasonicNXT is UID 77 and the one who posted right above Meiko is UID 1994; IIRC avatars won't show up unless the post in question has the correct user ID data...so I guess the _user_text field is messed up/empty/something else for those two posts?

**Comment by UltrasonicNXT** [comment]
Hmmm, I'm not sure. In the WikiForum rewrite I removed the ```_user_text``` field, so that shouldn't affect anything, and I can't see anything else up in the DB

**Comment by UltrasonicNXT** [comment]
Ah found it. Those UIDs don't exist..!

**Comment by NovaFlare** [comment]
Yeah, this happens after there's user merge, I noticed this a few months ago after Soupperson1 and I were both having password problems and Meiko got us to make new accounts so he could merge our old accounts with new ones to preserve edit histories/edit counts, etc. All the missing IDs can probably be seen [here] (http://en.brickimedia.org/index.php?title=Special%3ALog&type=usermerge&user=&page=&year=&month=-1&tagfilter=).

**Comment by UltrasonicNXT** [comment]
Hmm, I've found where to handle it, but I'm not sure what to put in place of it? We need to return some user object, but there's no way of finding the user it should be AFAIK

**Comment by UltrasonicNXT** [comment]
https://gerrit.wikimedia.org/r/#/c/203653/

**Comment by codynguyen1116** [comment]
@UltrasonicNXT Did that commit you pushed to Gerrit fix this bug?

**Comment by UltrasonicNXT** [comment]
Don't really know to be honest

**Comment by UltrasonicNXT** [comment]
No, that commit has not actually been merged. Per my comments above, I found the source of the issue, but didn't know how to fix it.

**Comment by neoncitylights** [comment]
Brickimedia no longer uses GitHub as an issue tracker.
