### ISSUE TITLE
Drop down menus

### ISSUE THREAD

**Issue by Berrybrick** [Brickimedia/brickimedia#366]
Sorry if this has been brought up already, but drop down menus seem to be acting funny for me....

![dropit](https://cloud.githubusercontent.com/assets/5835029/7054905/e02fbaae-de0d-11e4-8f3f-03d8e6df88c2.png)

They show up on the page already opened and don't seem to close. It's kind of frustrating. :P

Edit: The "more" menu does close if I scroll to the bottom of the page, but then it doesn't seem to reopen.

**Comment by codyn329** [comment]
@Berrybrick - Looked at it, looks like it's the same issue at Meta, and LEGO Ideas Wiki, but not Dev, Admin, GBCWiki, or Customs. *Refreshing* the page however seems to fix the issue, so try that.

**Comment by Berrybrick** [comment]
What a good idea. Wish I thought of that. :P

I've switched to deepsea in the meantime.

**Comment by codyn329** [comment]
OK, if it's fixed on Refreshed then for you then you can close the issue

**Comment by MtMNC** [comment]
That's a caching issue. I changed the JS for the dropdowns in the latest commit. Clearing your cache (or maybe purging the page as suggested above) should fix the issue.

**Comment by Berrybrick** [comment]
Okay, it's fixed. Thanks.
