### ISSUE TITLE
Refreshed header categories should appear in sidebar on mobile

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#367]
![image](https://cloud.githubusercontent.com/assets/3800972/4415945/9c3d5d4a-4535-11e4-8c9b-3a03d9208c6e.png)

Via #274

**Comment by MtMNC** [comment]
Maybe the (currently disabled) mobile logo could open up a dropdown that has the header categories and links to other wikis?

Also see https://github.com/Brickimedia/brickimedia/issues/371.

**Comment by neoncitylights** [comment]
Superseded by https://phabricator.wikimedia.org/T151430
