### ISSUE TITLE
VisualEditor support for Refreshed

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#368]
Refreshed should be able to support VisualEditor.

Via #274

**Comment by UltrasonicNXT** [comment]
Is VisualEditor enabled?

**Comment by georgebarnick** [comment]
On Brickimedia, no

**Comment by MtMNC** [comment]
I just installed VisualEditor on my local clone and it actually works surprisingly well. To be sure there's a fair bit of CSS/especially PHP changes to be made, but it actually doesn't look like it'll be as hard as you might think. Real life should calm down for me over the next week or so, hopefully then I can get to work on this.

**Comment by georgebarnick** [comment]
Does it function properly (besides just displaying properly)?

**Comment by MtMNC** [comment]
When I save, I get an "unknown error," but the page still saves properly. This also happens with Vector though, so I probably messed something up in the installation. So whatever issues there are have nothing to do with Refreshed.

**Comment by georgebarnick** [comment]
Hmm okay. I might install VisualEditor on devwiki if I can get it running decently on our server.

**Comment by georgebarnick** [comment]
@MtMNC: Is your local clone on MediaWiki 1.24 or 1.25 (or other)?

**Comment by MtMNC** [comment]
First I had the VisualEditor master installed on MW 1.26alpha, then I went back VisualEditor for 1.25 on MW 1.25. The error has happened on both.

**Comment by georgebarnick** [comment]
I have VisualEditor installed on dev. I can't get parsoid to run on our server and I think it's because nodejs is retarded for us. Did you have any issues getting Parsoid set up @MtMNC?

![image](https://cloud.githubusercontent.com/assets/3800972/7904592/3f511898-07d0-11e5-9c6b-c49b775a816f.png)

<small>FWIW I had parsoid working on our server several months ago but I've just pulled it and nodejs to be up to date and can't get it to work.</small>

**Comment by MtMNC** [comment]
No, I didn't get anything like that.... That's Linux, no? Are all the [JS dependencies](https://www.mediawiki.org/wiki/Parsoid/Developer_Setup#JS_dependencies) installed? Otherwise I'm not sure what the problem might be.

**Comment by georgebarnick** [comment]
Nevermind, I did a lot of work with node and finally got it working and parsoid is running for devwiki. I tested VisualEditor and it worked perfectly in Vector. It isn't initiating in Refreshed though.

**Comment by MtMNC** [comment]
Did you add `refreshed

**Comment by georgebarnick** [comment]
Ah I forgot that... I saw "edit" and "edit source" tabs in Refreshed though.

**Comment by georgebarnick** [comment]
Yeah, adding ```$wgVisualEditorSupportedSkins``` didn't change anything.

**Comment by MtMNC** [comment]
Weird... I'll try moving my local clone to MW 1.24 along with VisualEditor to see if that's the problem.

**Comment by MtMNC** [comment]
Sorry that took a while, there was a database issue that update.php didn't fix. Anyway, works fine on my clone running 1.24....

**Comment by MtMNC** [comment]
VisualEditor seems to load properly in Refreshed now, but it looks like Parsoid isn't on so we can't test editing yet.

**Comment by georgebarnick** [comment]
Oh yeah, with all the server reboots lately it's been stopped.

**Comment by georgebarnick** [comment]
![image](https://cloud.githubusercontent.com/assets/3800972/8050365/e1d58882-0e39-11e5-8c33-d3e898db66f4.png)
Needs some formatting work.

**Comment by codynguyen1116** [comment]
Closing per https://phabricator.wikimedia.org/T134668
