### ISSUE TITLE
Interwiki redirects in the blog namespace break BlogPage

### ISSUE THREAD

**Issue by mary-kate** [Brickimedia/brickimedia#370]
stories.brickimedia.org has a page called `User blog:SirComputer/Announcing my resignation`, which breaks BlogPage with this error message:

PHP message: PHP Catchable fatal error:  Argument 1 passed to Article::__construct() must be an instance of Title, string given, called in /var/www/core/extensions/BlogPage/BlogPage.php on line 30 and defined in /var/www/core/includes/page/Article.php on line 84

So I tried the obvious solution:
```php
	if ( !$target instanceof Title ) {
		$target = Title::newFromText( $target );
	}
```
Which, much to my surprise, didn't work. ?action=edit won't work either (because the BlogPage class is invoked whenever pages in the blog NS are being handled -- be it action=view, action=edit or probably even for action=someinvalidaction), but Special:Export does. It revealed that the page contains the following text:
```html
<vote /> <!--start text--> #REDIRECT [[m:User blog:SirComputer/Announcing my resignation]] <comments /> __NOEDITSECTION__
```

m: exists in the interwiki table so it's correctly treated as an interwiki prefix, and BlogPage does have some code related to handling redirects, but I guess the original developers didn't think that interwiki redirects are a thing.

**Comment by codynguyen1116** [comment]
@mary-kate Did your pushed commit fix this issue?

**Comment by mary-kate** [comment]
Aye, it's once again possible to [view](http://stories.brickimedia.org/wiki/User_blog:SirComputer/Announcing_my_resignation?redirect=no) and [edit](http://stories.brickimedia.org/index.php?title=User_blog:SirComputer/Announcing_my_resignation&action=edit) the aforementioned `User_blog` page.
