### ISSUE TITLE
Easier wiki navigation through mobile

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#371]
On mobile, for whatever wiki you're on, it'll just show the logo but it doesn't support a drop down menu to check out the other wikis easily. 
![test](https://cloud.githubusercontent.com/assets/4723983/7101956/5a2f4ca0-e036-11e4-86a3-d111940c6057.png)

**Comment by MtMNC** [comment]
Definitely needs to be implemented. Having to expand a dropdown inside a slide-out sidebar is kind of clunky though IMO, does anyone have other ideas? Maybe the (currently disabled) mobile logo that sits in the header could reveal a dropdown?

**Comment by codynguyen1116** [comment]
Closing because duplicate of #367
