### ISSUE TITLE
Mobile search broken

### ISSUE THREAD

**Issue by lachlanshanks** [Brickimedia/brickimedia#373]
On Brickipedia, the search isn't working. When I click the icon, the bar and keyboard appear (the bar appears under the hamburger icon) ten disappear again.

I'm using Chrome 41 on a 2014 Moto G.

**Comment by mary-kate** [comment]
Yep, I can confirm this, too; tested with a few different Android devices under Firefox. This seems to be an issue only when the screen resolution is low enough (most (low-end) smartphones, and certain tablets -- like mine, which has a screen resolution of 1280×800 px -- in portrait mode).

**Comment by MtMNC** [comment]
Just thinking out loud here--the search button is an anchor tag, so maybe the normal click event and the jQuery Mobile tap event both fire and cancel each other out? I'll look into this when I have time (hopefully this weekend).

**Comment by MtMNC** [comment]
Are you seeing any issues after the latest commit?

**Comment by MtMNC** [comment]
Right, it's been a while so I'm assuming everything's all good. If there are still any issues left over we can reopen this.

**Comment by MtMNC** [comment]
...and reopening. The solution I used prevents the logo button from working. [Philip Walton was right.](https://css-tricks.com/dangers-stopping-event-propagation/) -_-
