### ISSUE TITLE
Chat starts out with empty message

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#376]
Not an error or bug that makes chat dysfunctional, although the very first message starts out as empty. The mwchat-table should be completely empty until a message is submitted. 

![image](https://cloud.githubusercontent.com/assets/4723983/7218053/55844f0c-e61c-11e4-9360-381f3be8ba4a.png)

**Comment by UltrasonicNXT** [comment]
This is intended, I did this for a reason. Can't quite remember why now, but this is meant to be.
