### ISSUE TITLE
Special:ArticlesHome is blank

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#377]
I forgot what this special page was for..I think it was for something related to lists of blogs perhaps? But anyways, its broken (comes up blank) and the error given in the console was "Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

![image](https://cloud.githubusercontent.com/assets/4723983/7242671/4f02c784-e78a-11e4-92d8-3748349351e3.png)

**Comment by mary-kate** [comment]
This is caused by a fatal typo in `/extensions/BlogPage/SpecialArticlesHome.php`, which was fixed early January on upstream; see https://gerrit.wikimedia.org/r/#/c/182559/ for more info. No clue why it isn't live on Brickimedia...maybe @UltrasonicNXT knows more?

**Comment by UltrasonicNXT** [comment]
Fixed.
