### ISSUE TITLE
Unnecessary third scrollbar on article

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#378]
On the article, 'Creator', there's a third scrollbar, even though there shouldn't be. 

![image](https://cloud.githubusercontent.com/assets/4723983/7264089/51d2615e-e84d-11e4-8117-a254d60d3358.png)

**Comment by georgebarnick** [comment]
Probably caused by a template on the page that's being floated or something

**Comment by MtMNC** [comment]
There was a `&nbsp;` in [Template:Navbar](http://en.brickimedia.org/wiki/Template:Navbar) for some reason (and Template:Navbar is used in [Template:Creativity](http://en.brickimedia.org/wiki/Template:Creativity), which is on the Creator page). Other pages that use templates derived from Template:Navbar, such as [Basic](http://en.brickimedia.org/wiki/Basic), also had an extra scrollbar. [Getting rid of the `&nbsp;`](http://en.brickimedia.org/index.php?title=Template:Navbar&curid=21090&diff=973120&oldid=612643) seems to have fixed the issue.
