### ISSUE TITLE
Search suggestions incorrectly positioned

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#379]
While the page is scrolled down, and something is typed in the search bar and then scrolled up, the suggestions don't move with it. 

![image](https://cloud.githubusercontent.com/assets/4723983/7267086/a8e786ae-e87a-11e4-9631-04663a0fdd8a.png)

**Comment by georgebarnick** [comment]
I'm unable to reproduce this.

**Comment by mary-kate** [comment]
I can confirm this on Windows 7/Internet Explorer 11. (I also found another, possibly related issue: div.suggestions needs a z-index higher than div.fixed-toolbox so that the latter doesn't overlap the former. Maybe that'll mysteriously be fixed once this bug is fixed, too.)

**Comment by codyn329** [comment]
Ah, I'm using Windows 8.1 and Google Chrome 42.0.3, if that info helps.

**Comment by NovaFlare** [comment]
No problem in Safari or Firefox as far as I can tell, tested on Deep Sea and Refreshed.

**Comment by codyn329** [comment]
Tested on other wikis, this seems to be only a problem on Brickipedia(?)

**Comment by codynguyen1116** [comment]
Tested again, doesn't seem to happen anymore so closing issue
