### ISSUE TITLE
Searching in a Page's History

### ISSUE THREAD

**Issue by Brickfilmer** [Brickimedia/brickimedia#381]
Earlier today, I was looking through an article's history to see when a particular addition to said article was made, hoping to find the edit summary that went with the addition and, hopefully, would explain it. However, there were several dozen different revisions to look through, which, while certainly possible, was frustrating, and with pages that have had hundreds of revisions, it would be even worse. As such, I was wondering if a feature that allows one to search a page's history for a word or set of characters, only turning up revisions featuring the searched characters, is possible. It's not an urgent enhancement, but it is one that I feel would be quite useful.

**Comment by georgebarnick** [comment]
This isn't something I know of any ability to do in MediaWiki, but perhaps could be suggested for MediaWiki core.

**Comment by UltrasonicNXT** [comment]
You're not the first person to ask for this - so much so that an external tool was developed for Wikipedia: [wikiblame](http://wikipedia.ramselehof.de/wikiblame.php?lang=en&article=Knife_Fight)

**Comment by codynguyen1116** [comment]
Closed and posted on Phabricator: https://phabricator.wikimedia.org/T126105
