### ISSUE TITLE
Unable to edit social profile

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#383]
When I attempted to update my social profile, it tells me I can't do so until I have at least 5 edits. I certainly have over 5 edits (at the time of this writing I have 8,491 edits) so this is apparently bugged.

![image](https://cloud.githubusercontent.com/assets/3800972/7397888/4ff0c43e-ee79-11e4-8c52-8764a5dbf22f.png)

**Comment by mary-kate** [comment]
@UltrasonicNXT Can you review the patch for this issue, please? It's https://gerrit.wikimedia.org/r/#/c/207701/ (and there are the related three patches which oughta be merged after this one's been merged, https://gerrit.wikimedia.org/r/#/c/207706/, https://gerrit.wikimedia.org/r/#/c/207709/ and https://gerrit.wikimedia.org/r/#/c/207719/). Thanks!

**Comment by codynguyen1116** [comment]
Looks like those commits fixed this issue so closing
