### ISSUE TITLE
Rate limiter in private messages

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#384]
I know MediaWikiChat has a rate limiter built in with ```$wgChatFloodMessages```, but was wondering if this affected private messages. The documentation doesn't specify.

**Comment by UltrasonicNXT** [comment]
It doesn't affect private messages as it is.

**Comment by georgebarnick** [comment]
Perhaps it should (or be able to be configured to do so)? I realize the primary intention of the rate limiter is to prevent flooding chat with spam, but since chat uses SQL, wouldn't an influx of flooding messages in private messages lead to a large number of SQL writes which could potentially lead to a crash or just slow SQL server? Just hypothesizing.

**Comment by UltrasonicNXT** [comment]
Yeah it might as well.

**Comment by UltrasonicNXT** [comment]
Done.
