### ISSUE TITLE
#cvn-brickimedia readiness

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#385]
Does anyone think #cvn-brickimedia will still be too resource-intensive for our server to handle with the recentchanges scripts running? We've started getting more and more newbie members as well as spambots from time to time, especially on some projects that people don't check daily (like Customs and Ideas), so it would be good to have a CVN channel again.

**Comment by Ajraddatz** [comment]
I'd say it's too resource-intensive. Considering we already routinely use too much of the cores / memory... :S

**Comment by lewiscawte** [comment]
Why is it resource intensive? What bots were you using on the server?

**Comment by georgebarnick** [comment]
@lewiscawte: It sent every recent change for every wiki to a UDP port via LocalSettings and then a Python (or Perl when the Python script wouldn't work at times) script would feed that information to different IRC channels (information at [[<a href="http://meta.brickimedia.org/wiki/IRC">meta:IRC</a>]]). That was everything that took place on our server. From there everything was done by CVN bots which would read the RecentChanges channels and then feed it into #cvn-brickimedia. However, for each one of the Python scripts, they ran under ```screen``` all the time which is one process per wiki. I don't know how much resources that used, but we cut back on them at some point and stopped using the CVN channel to save resources on our server.

**Comment by lewiscawte** [comment]
That's not what I wanted to know. Where can I find a copy of the scripts?

**Comment by georgebarnick** [comment]
<a href="//github.com/Brickimedia/generalscripts">Where all our other scripts are found</a>

**Comment by codynguyen1116** [comment]
Putting this on low-to-mid priority - I've been leaving up KVIRC on my computer running these past few days and it looks like (besides me), there's only about 4 active users on it consistently while the rest are bots. Until more users from our community use IRC, this will stay open and stay at the low-to-mid priority.

**Comment by neoncitylights** [comment]
Moved to https://phabricator.wikimedia.org/T151139
