### ISSUE TITLE
Special pages not updating automatically

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#386]
Special pages such as `Special:DoubleRedirects` don't update automatically without running `updateSpecialPages.php` in the backend. This is inconvenient and has been this way for around a year.

**Comment by UltrasonicNXT** [comment]
I would have thought core MW would put that sort of stuff in the job queue

**Comment by LegoFan4000** [comment]
Its because miser mode is enabled in LocalSettings.php. We can create a cron job to automatically update them for us.

**Comment by neoncitylights** [comment]
Brickimedia no longer uses GitHub as an issue tracker.
