### ISSUE TITLE
Merge refreshed-beta branch into master

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#387]
Refreshed 3.0 is currently a stable release, so it's about time to merge ```refreshed-beta``` into ```master```. I don't believe I'll be able to correctly do this, so someone who can is more than welcome to do it at any time.

**Comment by seaside98** [comment]
Challenge accepted. I'll clone it and give it a try sometime tomorrow.

**Comment by UltrasonicNXT** [comment]
When you say merge, I assume you just mean totally overwrite what's already there and replace it with refreshed-beta?

**Comment by seaside98** [comment]
I think some of the commits to master may be important... I'm going to attempt an actual merge on a clone.

**Comment by seaside98** [comment]
After merging the branches, and favoring refreshed-beta for all conflicts, **[here is the difference](https://github.com/Brickimedia/Refreshed/compare/refreshed-beta...seaside98:master)**. If someone familiar with Refreshed could look it over and clone it to make sure it isn't all messed up... @MtMNC

**Comment by MtMNC** [comment]
@seaside98 Everything looks the way it should visually. The only real things I see are that we don't need the Brickidata and LMO logos anymore (as far as I know at least) and I think script.sh got added in along the way. Otherwise, I think everything's good to go.

**Comment by seaside98** [comment]
@georgebarnick @UltrasonicNXT Branches merged! I didn't delete the refreshed-beta branch in case you still use it on the server, so you are free to delete it whenever.
