### ISSUE TITLE
Install and configure SpamBlacklist

### ISSUE THREAD

**Issue by mary-kate** [Brickimedia/brickimedia#389]
[SpamBlacklist] (https://www.mediawiki.org/wiki/Extension:SpamBlacklist) is not currently enabled on Brickimedia. It should be installed and an additional configuration line should be added to LocalSettings.php so that we can blacklist emails on a global scale:
`$wgBlacklistSettings['email']['files'] = array( 'http://meta.brickimedia.org/index.php?title=MediaWiki:Email-blacklist&action=raw&sb_ver=1' );`

SpamBlacklist's default configuration pulls the list of known link spam domains from [Wikimedia's Meta-Wiki] (https://meta.wikimedia.org/wiki/Spam_blacklist), which generally speaking is sufficient. There are sometimes -- although very rarely -- false positives, but that's nothing local whitelisting couldn't fix.

**Comment by UltrasonicNXT** [comment]
Done

**Comment by UltrasonicNXT** [comment]
(as long as we don't need any other configuration)
