### ISSUE TITLE
Namespaces appear blank in Special:GlobalEditcount

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#391]
![image](https://cloud.githubusercontent.com/assets/4723983/7557283/09d80ee2-f754-11e4-9837-210ed7e91418.png)

**Comment by georgebarnick** [comment]
These would be namespaces that aren't present on the current wiki you're viewing. There's nothing that can be done to fix this. They aren't defined on that wiki, so there's no name for it to display.
