### ISSUE TITLE
"more..." toolbox link doesn't work when editing

### ISSUE THREAD

**Issue by onei** [Brickimedia/brickimedia#392]
Spotted this while having a quiet look through the skin, sample URL: http://en.brickimedia.org/index.php?title=Tahu&action=edit

I'm using Chrome 42 and I'm logged out. Not seeing any errors in my console, so I suspect it's a case of the js not loading.

**Comment by UltrasonicNXT** [comment]
Good spot, yeah, it doesn't work when the toolbar is 'docked' below the title. If you scroll down on the page (not the edit textarea), so the toolbar starts floating, it works then.

**Comment by MtMNC** [comment]
I'm sure this is an issue from when I cleaned up the JS.

Actually, this is be a good opportunity to change how the toolbar is generated. Currently the toolbar is duplicated with JS and the duplicate flies down when the user scrolls to a certain point. The alternative would be having just one toolbar that gets fixed to the top when the user scrolls to a certain point. That would require less JS and would fix this issue. I'll get on it.

**Comment by MtMNC** [comment]
Should be good as of https://github.com/Brickimedia/Refreshed/commit/dc0f87ced5fa0c62a0b8f9e5280dd1be1089e810. I'll keep this open until the commit gets pushed to the site to make sure.

**Comment by onei** [comment]
Do you guys not have a development environment, e.g. vagrant, to test changes on?

**Comment by georgebarnick** [comment]
Most of us have local servers to develop on and we also have dev.brickimedia.org..

**Comment by MtMNC** [comment]
I have a local copy of MediaWiki and it's working there, yeah. Sometimes unforeseen issues pop up on the actual site though (or I just miss something :P), so I like to keep issues open until changes get deployed just in case.
