### ISSUE TITLE
Pages fail to load

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#393]
Some pages are failing to load, and often just result in a white blank page. It's been noted by @NovaFlare at Meta that it could possibly be the recent SMW software update?

**Comment by UltrasonicNXT** [comment]
Got a link?

**Comment by codyn329** [comment]
http://en.brickimedia.org/wiki/Classic

**Comment by UltrasonicNXT** [comment]
Yup, SMW, but also getting some Parser errors, it's messy:
````
2015/05/24 17:37:49 [error] 1478#0: *1004572 FastCGI sent in stderr: "re/includes/parser/Parser.php:3471
PHP message: PHP  41. call_user_func_array:{/var/www/core/includes/parser/Parser.php:3753}() /var/www/core/includes/parser/Parser.php:3753
PHP message: PHP  42. ExtParserFunctions::ifObj() /var/www/core/includes/parser/Parser.php:3753
PHP message: PHP  43. PPFrame_DOM->expand() /var/www/core/extensions/ParserFunctions/ParserFunctions_body.php:139
PHP message: PHP  44. Parser->braceSubstitution() /var/www/core/includes/parser/Preprocessor_DOM.php:1179
PHP message: PHP  45. PPFrame_DOM->expand() /var/www/core/includes/parser/Parser.php:3384
PHP message: PHP  46. Parser->braceSubstitution() /var/www/core/includes/parser/Preprocessor_DOM.php:1179
PHP message: PHP  47. PPFrame_DOM->expand() /var/www/core/includes/parser/Parser.php:3623
PHP message: PHP  48. Parser->braceSubstitution() /var/www/core/includes/parser/Preprocessor_DOM.php:1179
PHP message: PHP  49. PPFrame_DOM->expand() /var/www/core/includes/parser/Parser.php:3384
PHP message: PHP  50. Parser->braceSubstitution() /var/www/core/includes/parser/Preprocessor_DOM.php:1179
PHP message: PHP  51. PPFrame_DOM->expand() /var/www/core/includes/parser/Parser.php:3384
PHP message: PHP  52. Parser->braceSubstitution() /var/www/core/includes/parser/Preprocessor_DOM.php:1179
PHP message: PHP  53. PPFrame_DOM->expand() /var/www/core/includes/parser/Parser.php:3384
PHP message: PHP  54. Parser->braceSubstitution() /var/www/core/includes/parser/Preprocessor_DOM.php:1179
PHP message: PHP  55. PPFrame_DOM->expand() /var/www/core/includes/parser/Parser.php:3384
PHP message: PHP  56. Parser->braceSubstitution() /var/www/core/includes/parser/Preprocessor_DOM.php:1179
PHP message: PHP  57. PPFrame_DOM->expand() /var/www/core/includes/parser/Parser.php:3384
PHP message: PHP  58. Parser->braceSubstitution() /var/www/core/includes/parser/Preprocessor_DOM.php:1179
PHP message: PHP  59. PPFrame_DOM->expand() /var/www/core/includes/parser/Parser.php:3384
PHP message: PHP  60. Par
2015/05/24 17:37:49 [error] 1478#0: *1004572 FastCGI sent in stderr: ": PHP  79. SMWQueryProcessor::getResultFromQuery() /var/www/core/extensions/SemanticMediaWiki/includes/parserhooks/AskParserFunction.php:154
PHP message: PHP  80. SMW\ResultPrinter->getResult() /var/www/core/extensions/SemanticMediaWiki/includes/query/SMW_QueryProcessor.php:514
PHP message: PHP  81. SMW\ResultPrinter->buildResult() /var/www/core/extensions/SemanticMediaWiki/includes/queryprinters/ResultPrinter.php:215
PHP message: PHP  82. SMW\ListResultPrinter->getResultText() /var/www/core/extensions/SemanticMediaWiki/includes/queryprinters/ResultPrinter.php:250
PHP message: PHP  83. SMW\ListResultPrinter->getRowText() /var/www/core/extensions/SemanticMediaWiki/includes/queryprinters/ListResultPrinter.php:170
PHP message: PHP  84. SMW\ListResultPrinter->getRowListContent() /var/www/core/extensions/SemanticMediaWiki/includes/queryprinters/ListResultPrinter.php:286
PHP message: PHP  85. SMWResultArray->getNextDataValue() /var/www/core/extensions/SemanticMediaWiki/includes/queryprinters/ListResultPrinter.php:343
PHP message: PHP  86. SMWResultArray->getNextDataItem() /var/www/core/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php:139
PHP message: PHP  87. SMWResultArray->loadContent() /var/www/core/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php:110
PHP message: PHP  88. SMWSQLStore3->getPropertyValues() /var/www/core/extensions/SemanticMediaWiki/includes/storage/SMW_ResultArray.php:219
PHP message: PHP  89. SMWSQLStore3Readers->getPropertyValues() /var/www/core/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php:234
PHP message: PHP  90. SMWSQLStore3->findPropertyTableID() /var/www/core/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Readers.php:204
PHP message: PHP  91. SMW\SQLStore\PropertyTableInfoFetcher->findTableIdForProperty() /var/www/core/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php:661
PHP message: PHP  92. SMW\DIProperty->findProp
````

**Comment by Edward-Nigma** [comment]
Hopefully this can be fixed soon, because the error is also occurring on templates that are used in many articles, causing errors in them as well. It's annoying, and the only way I can read the article is in source.

**Comment by Edward-Nigma** [comment]
Ah, it looks like Template:ThemeTable/renovations is causing the articles not to load.

**Comment by mary-kate** [comment]
http://en.brickimedia.org/index.php?title=Template:ThemeTable&action=edit is, to put it _very_ nicely, a disaster. It **needs** to be rewritten, either in Lua or in PHP (the latter would obviously require editing the pages in question) and ASAP; I'm not able to edit the page in question because every edit fails due to fatals (OOM, I guess). I tried toning down the calls to the ThemeSet template first from 999 to 100, and again from 999 to 50, but it's still OOM'ing.

**Comment by georgebarnick** [comment]
Could also be because of SMW. Tried updating the server yesterday to MediaWiki 1.25 but it failed because of something SMW-related. Tried updating SMW, don't know if it changed anything, but ended up rolling back to MediaWiki 1.24. Don't know if SMW is still the same as it was before I attempted the MediaWiki update or not because frankly I don't understand composer and think it's stupid that it's required to be used for SMW.

**Comment by lewiscawte** [comment]
Oh, SMW. Yeah, well, @legoktm noted at the Hackathon in Lyon that SMW doesn't actually work with 1.25 yet (iirc)

**Comment by Edward-Nigma** [comment]
Template:ThemeTable should be deleted for the time being, it's making every theme article with it unreadable, and it's been this way for about two weeks.

**Comment by georgebarnick** [comment]
http://en.brickimedia.org/index.php?title=Review:Liam

Review pages also don't seem to want to work (accidentally clicked that link but discovered the issue)

**Comment by mary-kate** [comment]
tl,dr: bumping `xdebug.max_nesting_level` in `php.ini` might (or might not!) solve this issue and #394, or at least partially. Quick googling suggests that the PHP XDebug extension should not be enabled on production, though, so maybe we should disable it altogether and see what that does?

**Comment by UltrasonicNXT** [comment]
@mary-kate I installed XDebug a little while ago, didn't (on purpose) activate it in php.ini. (At least I'm fairly sure I didn't)

**Comment by UltrasonicNXT** [comment]
Okay, looks like I did activate it in php.ini, my apologies, I meant to only enable it temporarily. http://en.brickimedia.org/wiki/Classic is now showing

**Comment by georgebarnick** [comment]
http://greatballcontraption.com/wiki/Special:WikiForum/Ask_questions_here

**Comment by UltrasonicNXT** [comment]
I have for once and for all uninstalled xdebug. I thought I had before, but I definitely have now

**Comment by codynguyen1116** [comment]
fixed long time ago

**Comment by georgebarnick** [comment]
Well, not really... just avoided... no fix was ever made.

**Comment by codynguyen1116** [comment]
Oh woops didn't know that, reopening

**Comment by georgebarnick** [comment]
Pretty sure we've fixed config to resolve this now
