### ISSUE TITLE
Customs fatal error

### ISSUE THREAD

**Issue by kingcjc95** [Brickimedia/brickimedia#394]
https://twitter.com/ChakorChanning/status/605337319722373120

Sibo said he sometimes had issues with loading stuff at Customs, next time I see him I'll ask if its like that. 

Looks just like when a page doesn't load properly to me.

**Comment by MtMNC** [comment]
Happening on en too: http://en.brickimedia.org/wiki/Xalax

**Comment by codyn329** [comment]
This has to do with issue #393 since it also has Template:ThemeTable included in the article (and the fact that the page doesn't load)

**Comment by georgebarnick** [comment]
I don't think this dude's custom would be using the ThemeTable template (don't even think that exists on Customs Wiki). Sounds like a broader SMW issue or possibly just an unrelated fatal error that should be investigated.

**Comment by UltrasonicNXT** [comment]
I'm unable to replicate this.

**Comment by mary-kate** [comment]
Nothing unusual to see here, carry on folks:

PHP message: PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /var/www/core/extensions/SemanticMediaWiki/src/PropertyLabelFinder.php on line 230

**Comment by UltrasonicNXT** [comment]
He's not using any templates or queries, so I discounted SMW.

**Comment by UltrasonicNXT** [comment]
This is the error:
````
2015/06/04 15:21:51 [error] 1342#0: *9722 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /var/www/core/extensions/AbuseFilter/AbuseFilter.parser.php on line 1158" while reading response header from upstream, client: 70.20.37.42, server: *.brickimedia.org, request: "POST /index.php?title=The_Queen_Cobra&action=submit HTTP/1.1", upstream: "fastcgi://unix:/tmp/php5-fpm.sock:", host: "customs.brickimedia.org", referrer: "http://customs.brickimedia.org/index.php?title=The_Queen_Cobra&action=edit"
````

**Comment by codynguyen1116** [comment]
**Request for closure** shouldn't be an issue anymore
