### ISSUE TITLE
Notifications bubble (flyout) formatting broken

### ISSUE THREAD

**Issue by UltrasonicNXT** [Brickimedia/brickimedia#396]
![image](https://cloud.githubusercontent.com/assets/4870935/7958112/438af684-09e4-11e5-81bd-6dac952caf2d.png)
 Overlapping text, no font/white font?

**Comment by UltrasonicNXT** [comment]
That's fonts fixed.

**Comment by georgebarnick** [comment]
It's because in Refreshed the element is being moved to a different parent with JavaScript and some of the CSS is being lost (or extra unwanted CSS from the new parent being added).

**Comment by UltrasonicNXT** [comment]
I've updated Echo, it's fixed this one.
