### ISSUE TITLE
WikiFont not included in Refreshed ZIP download

### ISSUE THREAD

**Issue by MtMNC** [Brickimedia/brickimedia#397]
GitHub doesn't include any dependencies when you download using the "ZIP download" button. This means that WikiFont doesn't get included in the download, and the skin is broken when it's installed. We should either find a better way to integrate WikiFont into Refreshed so this doesn't happen or we should come up with some better documentation so it's clear to users that WikiFont needs to be downloaded separately.

(Per @lachlanshanks)

**Comment by codynguyen1116** [comment]
closing per https://phabricator.wikimedia.org/T134683
