### ISSUE TITLE
Refreshed logo not working in desktop

### ISSUE THREAD

**Issue by lachlanshanks** [Brickimedia/brickimedia#398]
The logo is not appearing on desktop mode (it works fine on mobile). Here's a link: http://gazelle.arvixe.com/~shanksi/w-new/index.php?title=Special:RecentChanges

**Comment by MtMNC** [comment]
A missing `echo` was the problem. Should be good as of the next commit. If you don't want to download the whole skin again, just find the following line (line 127) in Refreshed.skin.php:

`<a class="main header-button" href="<?php echo $wgRefreshedHeader['url'] ?>"><?php $wgRefreshedHeader['img'] ?></a>`

and replace it with with this:

`<a class="main header-button" href="<?php echo $wgRefreshedHeader['url'] ?>"><?php echo $wgRefreshedHeader['img'] ?></a>`
