### ISSUE TITLE
WikiLove doesn't work

### ISSUE THREAD

**Issue by MtMNC** [Brickimedia/brickimedia#400]
From [BrickfilmNut on en](http://en.brickimedia.org/index.php?title=User_talk:MtMNC&oldid=974304):

>My problem is just that, after I get past the "Preview" stage and want to submit, it says "Something went wrong when sending the message. Please try again." I know WikiLove used to work, though even back then it had a different issue of adding the code to the talk page twice. Now it doesn't seem to work at all.

I tried to send WikiLove on devwiki and had the same issue.

**Comment by codynguyen1116** [comment]
Tested today and is not an issue anymore. Assuming because WikiLove extension got updated in one of the commits at brickimedia/extensions repo
