### ISSUE TITLE
Database error on LSW

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#401]
There's a database error on LSW - (I know no one else uses this site anymore but I still do, and want to look over the articles  so that maybe that merge could happen /someday/ ) Anyways, here's the error:

![image](https://cloud.githubusercontent.com/assets/4723983/8509880/947c93c6-2286-11e5-81b4-eb1bba6cc668.png)

**Comment by UltrasonicNXT** [comment]
Update.php fixed it.
