### ISSUE TITLE
Active developers?

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#403]
It's kind of an issue but I guess more of a question. Is there anyone here in the community who is still active and interested in developing? I don't know if people don't check GitHub at all/anymore or just busy.

**Comment by MtMNC** [comment]
Yep I'm around.

**Comment by UltrasonicNXT** [comment]
I do check github, although life is getting busier I'll still be here to maintain things I've written at least.

**Comment by georgebarnick** [comment]
I rarely have time online when I'm not preoccupied with work but I still get email notifications for GitHub and the wikis.

**Comment by mary-kate** [comment]
@codyn329 I'm around and can be contacted via email or on IRC, though I do attempt to check Brickipedia's chat and GitHub regularly, too.
