### ISSUE TITLE
Speed up Semantic MediaWiki

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#405]
Following on from some things Cody said in #402, would someone please be able to check if $smwgQEqualitySupport is set to SMW_EQ_NONE in LocalSettings.php? It's meant to have a significant improvement on SMW searches with subqueries, and it might help the server out a bit.

**Comment by codyn329** [comment]
OK, well I just made a commit to that file, then if it gets pushed we're ready to go
