### ISSUE TITLE
Send ARE extension to translatewiki.net 

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#406]
This would be a step forward to help make the Article Rating Extension (ARE) more internationalised

**Comment by UltrasonicNXT** [comment]
True, this means switching it to MW hosting, which is fine, although I don't personally think anyone apart from us is likely to use it, which just makes it a hassle...

**Comment by codynguyen1116** [comment]
Relates to #454

**Comment by codynguyen1116** [comment]
https://phabricator.wikimedia.org/T136526
