### ISSUE TITLE
Fonts broken in Microsoft Edge

### ISSUE THREAD

**Issue by lachlanshanks** [Brickimedia/brickimedia#408]
Just got the W10 update and trying out Microsoft Edge, and discovered the fonts are broken again. This includes the icons in the header which aren't displaying at all.

**Comment by codyn329** [comment]
Can confirm this -->
![image](https://cloud.githubusercontent.com/assets/4723983/9157968/70f19752-3ed4-11e5-8225-55145901e013.png)

**Comment by MtMNC** [comment]
Does WikiFont show up if you try the latest commit in your local clone? (It hasn't been deployed to the actual site yet.)

**Comment by codyn329** [comment]
Sorry, can't test it since I don't have a local clone site to test on. Unless you meant to clone the repository?

**Comment by MtMNC** [comment]
Yeah I just meant a local clone site, sorry. Hopefully once the commit gets pushed (and the site comes back online :P) we can see what's going on.

**Comment by codyn329** [comment]
Ah, got it. :P Yeah, hopefully. Once I figure out how to create a local clone I'll try and see

**Comment by codyn329** [comment]
No console errors, although maybe it doesn't support one of the file types (woff/woff2/ttf/eot)? Wild guess here

**Comment by mary-kate** [comment]
For what it's worth, fonts have been broken in my IE11 (under Windows 7) for a looooooong time...this is just wild speculation, but I'd guess that whatever fixes one fixes the other, too.

**Comment by codyn329** [comment]
Instead of trying to fix the issue, why don't we use a different icon font instead? The problem with wikifont currently is that it's not being actively maintained by anyone - the last commit was in November 2014, that's about 9 months ago. There are other icon fonts like FontAwesome which are actually active projects, so what we can do is explore our options, test them out, and push it upstream

**Comment by mary-kate** [comment]
+2 for the idea of using a different icon font. I know for a fact that wikiHow at least makes use of FontAwesome, so if it works for a top 500 web property, I'm sure it'll work for our purposes, too. :-)

**Comment by georgebarnick** [comment]
The icon font seems to be working for me..

![image](https://cloud.githubusercontent.com/assets/3800972/9348064/bb0d4070-45ff-11e5-9031-e3c1c20b89b1.png)

**Comment by MtMNC** [comment]
The @ font-face in iefontfix.css and main.css don't match, maybe that has to do with it? Worth a shot at least.

**Comment by MtMNC** [comment]
So apparently IE doesn't like loading the fonts over HTTPS: https://stackoverflow.com/questions/7748140/font-face-eot-not-loading-over-https

I think that's the problem... the question becomes how to solve the issue. I'm guessing if we do a straight-up Google Fonts @ import it'd work, but that would slow down load time. We could load the fonts exclusively over HTTP, but then we would never load the fonts over HTTPS even when the browser could, plus it could lead to vulnerabilities if Refreshed is ever installed on a site that uses HTTPS. According to [this](http://www.paulirish.com/2010/the-protocol-relative-url/), protocol-independent URLs should be avoided too. So what do you think we should do?

**Comment by codyn329** [comment]
Security is important, and even though HTTP would be a solution it's not worth it. I still think that using another option would be better, unless if we want to fork the wikifont project and update it ourselves. Oh and it also says the project is inactive too at https://www.mediawiki.org/wiki/Design/WikiFont. I submitted a ticket at [munmay/WikiFont/issues/30](https://github.com/munmay/WikiFont/issues/30), maybe @munmay will notice this?

**Comment by MtMNC** [comment]
@codyn329 Great, thanks for doing that.

Dropping this here: https://connect.microsoft.com/IE/feedbackdetail/view/992569/font-face-not-working-with-internet-explorer-and-http-header-pragma-no-cache

And `pragma=no-cache` and `cache-control=no-cache` are both in the WikiFont request headers:

<img width="521" alt="blah" src="https://cloud.githubusercontent.com/assets/5515877/9392551/b4738166-473a-11e5-9f53-fb85a7ba9a39.png">

**Comment by lachlanshanks** [comment]
Hi, sorry to stir things up but the fonts have been broken on my site as well and I don't have HTTPS so I don't think HTTPS is the problem (or maybe it's just part of the problem).

**Comment by MtMNC** [comment]
@lachlanshanks Hmm, that might not be the problem for WikiFont then, but Lato is definitely being pulled from Google Fonts over HTTPS... so yeah, maybe there are multiple issues there preventing Lato from displaying.

**Comment by codyn329** [comment]
@MtMNC I thought we were pulling the Lato font we self-hosted from [Brickimedia/splash/resources/fonts](https://github.com/Brickimedia/splash/tree/master/resources/fonts) instead of using Google Font's CDN?

**Comment by MtMNC** [comment]
@codyn329 Nope, we're pulling it from Google. We could host the fonts within the Refreshed directory itself, but since other sites use the skin too, we shouldn't be pulling the fonts from another directory on our own site.

**Comment by munmay** [comment]
@codyn329 strange how I'm seeing the issue on brickimedia.org, but on [this test site,](http://munmay.com/wikifont_test) the font is rendering fine. Can you try adding this to the head: <meta http-equiv="X-UA-Compatible" content="IE=edge">

**Comment by codyn329** [comment]
@munmay Can you edit the comment please? I can't see anything after the colon. Thanks :)

**Comment by munmay** [comment]
Yikes, updated!

**Comment by Volker-E** [comment]
Just to rule out other (maybe related) things first: Do you get a 404 (XHR) on WikiFontLoader.css as well? Tested in Firefox and IE Edge 20.

**Comment by munmay** [comment]
If it wasn't clear before, I meant [this test site,](http://munmay.com/wikifont_test) is running on Edge with no issues.

**Comment by Volker-E** [comment]
@codyn329 @MtMNC **#382** has very high chances to be **the source of this issue**.
Make sure you're putting `?debug=true&action=purge` at the end of your URL in order to [get the most recent code version of the page](https://www.mediawiki.org/wiki/Manual:Purge) and not a cached one.

It's definitely *not* (in order of appearance in this thread):
 - missing support of webfonts in IE Edge
 - the mismatch of `@font-face` in iefontfix.css and main.css, as Edge and all other IE >= 10 are ignoring conditional comments
 - HTTP vs HTTPS, because the error also occurs if you just load http://en.brickimedia.org/wiki/Main_Page -- HTTP only

**Comment by codyn329** [comment]
@Volker-E  Yep, I tried adding the meta element using Microsoft Edge v20 but only an error was returned in the console. As for Firefox v38, it worked perfectly fine actually. Weird huh? Here's a screenshot for both browsers:
# Edge
![image](https://cloud.githubusercontent.com/assets/4723983/9701845/9afffd86-5405-11e5-8169-aa1596707100.png)
# Firefox
![image](https://cloud.githubusercontent.com/assets/4723983/9701862/d4df9790-5406-11e5-8877-b46cc03f0238.png)

**Comment by codyn329** [comment]
@mary-kate @MtMNC TBH I still think we really could just use a different Icon Font, and Font Awesome is a great project to use! It's checked daily by the developers and always respond to the issues opened up. Not only is it checked daily though but it's updated often too. Their is a huge span of different icons, so if we ever need a certain icon there's a really good chance it'll exist for usage.

**Comment by levi-w** [comment]
@MtMNC Stumbled upon this thread while trying to discern whether newer IE versions do any sort of "font security", but I digress...
For future reference, you can allow the browser to choose which protocol (HTTP/S) to use by omitting the `http(s):` part from your import, such as:

````css
@import  url(//fonts.googleapis.com/css?family=some-font-library-example)
````

So you load HTTPS when available, HTTP when HTTPS is unavailable.

[This](http://www.paulirish.com/2010/the-protocol-relative-url/) blog post calls it "protocol-relative-URL", though I'm not sure what the official term is for it.

Not sure if this will help y'all but figured I'd share because it's saved me a lot of headache in the past.

Cheers!
--lw

**Comment by codynguyen1116** [comment]
@levi-w, Just pushed a commit but please feel free to look over it. Thanks for the suggestion, hopefully this works :+1:

**Comment by levi-w** [comment]
@codynguyen1116 Please let me know if it was of any help! It was pure chance I found this thread but hopefully the CSS modification will fix your problem.

I'd like to know if the "font security" rumors I've heard are true. I haven't been successful in finding anything concrete, but if you continue to experience problems in MS Edge with your fonts, I'd have to guess something like that is going on...very curious indeed.

**Comment by codynguyen1116** [comment]
@levi-w Nope, no results. *shrugs* I think the 'font security rumors' you mention of could be true though. 

![image](https://cloud.githubusercontent.com/assets/4723983/12697845/9c26dab6-c752-11e5-854d-63be5c0e01d7.png)

**Comment by codynguyen1116** [comment]
Just added the priority to mid level, since from what I seen we don't have much traffic from MS Edge but, this is still something we should fix

**Comment by levi-w** [comment]
@codynguyen1116 Bummer, sorry that didn't work, I was sure I had your answer! :stuck_out_tongue_winking_eye: 

If you find anything out about the fonts blocking, please tag me and let me know as I'm very interested in this issue.

Thanks and good luck y'all.

**Comment by codynguyen1116** [comment]
Closing, now at https://phabricator.wikimedia.org/T134653

@levi-w We're moving issue platforms from Github to Phabricator, so if you're still interested you can check it up above ;)
