### ISSUE TITLE
Deepsea no longer maintained?

### ISSUE THREAD

**Issue by codyn329** [Brickimedia/brickimedia#410]
Since I'm assuming DeepSea skin is no longer maintained by others, would I be allowed to adopt it and have commit access to brickimedia/deepsea ?

**Comment by codyn329** [comment]
Woops sorry, putting this on http://meta.brickimedia.org/wiki/Access_Requests instead

**Comment by codyn329** [comment]
Sorry, I had to reopen this since there hasn't been a comment on it in a while D: and pinging @UltrasonicNXT since he was the creator of DeepSea

**Comment by mary-kate** [comment]
No objections from me -- I'm always happy to see more people involved in skinning. :) Looking at the commit history, it's been a while since there have been substantial changes to DeepSea, so this access request should be rather trivial.

**Comment by georgebarnick** [comment]
Pinging @lewiscawte to do this as he is the only owner of the Brickimedia GitHub account other than @UltrasonicNXT. I don't seem to have ownership of the account anymore so he'll have to be the one to do it if @UltrasonicNXT is inactive.

**Comment by lewiscawte** [comment]
Done.

**Comment by UltrasonicNXT** [comment]
Sorry guys, been on holiday, but sure, go for it
