### ISSUE TITLE
Update MediaWiki version from 1.24.2 to 1.25.2 

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#411]
Pretty self-explanatory - this version is newer and more up to date, so why not?

**Comment by georgebarnick** [comment]
Because last time we tried to update to MediaWiki 1.25, it was a disaster because Semantic MediaWiki did not work on MediaWiki 1.25.* at the time. If compatibility with Semantic MediaWiki has been fixed, then yes.

**Comment by codyn329** [comment]
Oh yeah, I remember that. Looked it up and the latest version of SMW is [2.2.2](https://semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.2.2) which is only compatible up to MW v1.24.x. We'll just have to wait for [2.3.0](https://semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.3.0), not sure how long that will be though.

**Comment by codynguyen1116** [comment]
@georgebarnick OK it's been updated and SMW is said to be compatible with MW for versions 1.25.x (source: https://www.semantic-mediawiki.org/wiki/Semantic_MediaWiki_2.3.0). Is it worth another try?

**Comment by georgebarnick** [comment]
Doesn't work, tried it a long time ago. Been trying to get @lewiscawte on it especially considering our MW version is now 2 releases behind and Brickipedia is still waiting on the ability to use new features in 1.25 before we can start using articleratings again...

**Comment by UltrasonicNXT** [comment]
Okay something's screwed up in the setup, I was just upgrading through composer and it's deleted the extension files of all of the composer extensions.

**Comment by UltrasonicNXT** [comment]
Okay that's all fixed. SMW is now at 2.3.1

**Comment by UltrasonicNXT** [comment]
Our PHP is only at 5.3.29 but it needs to be at 5.5.3 for MW 1.25/6

**Comment by UltrasonicNXT** [comment]
@chriscook18 yeah that would have been while SMW was temporarily disabled :)

**Comment by georgebarnick** [comment]
@UltrasonicNXT can we update our PHP version

**Comment by UltrasonicNXT** [comment]
I'm looking into it

**Comment by UltrasonicNXT** [comment]
It means updating debian

**Comment by UltrasonicNXT** [comment]
Which I will do, but I'm just checking the backups are all good first

**Comment by georgebarnick** [comment]
Alright sounds good

**Comment by UltrasonicNXT** [comment]
Done :D some issues have come up though, namely refreshed's dropdowns not always working

**Comment by UltrasonicNXT** [comment]
that's #428

**Comment by UltrasonicNXT** [comment]
Now done :D
