### ISSUE TITLE
Someone killed Deep Sea

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#413]
Nothing will load on Deep Sea- it just loads a white page, as if there's a PHP error there or something. Everything still seems to work fine in other skins (just spent most of the day thinking the site was down until I used another browser and determined it was the skin)

**Comment by georgebarnick** [comment]
@codyn329

**Comment by lewiscawte** [comment]
I see why :/

**Comment by codyn329** [comment]
Crap, sorry guys :/ Should've looked over the code another time before submitting
