### ISSUE TITLE
Link titles gone in top-left navbar

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#414]
The RecentChanges/Forum/Chat links that drop down when you hover over a wiki name in the menubar on the top left are working, but the forum and chat links aren't displaying any text (the "Recent changes" text still shows up though)

**Comment by codyn329** [comment]
Although a few weeks ago I became the new maintainer of this skin I currently don't have access to a laptop, only a phone, so I'll ping @UltrasonicNXT.
