### ISSUE TITLE
Redo splash

### ISSUE THREAD

**Issue by MtMNC** [Brickimedia/brickimedia#415]
I think the splash page should be redone--the JS could use some cleanup (especially the parts I wrote :P) and the page has a low FPS on scroll because the browser is constantly repainting a bunch of big background images. I'm not sure if a visual overhaul is necessary, but certainly it needs cleaning up on the backend. Could also use some better social media integration I suppose. What are your thoughts?

**Comment by georgebarnick** [comment]
I'm always willing to try a new change. More social integration would be great. More wiki integration would also be good, perhaps throw in some featured content from Bricki and other wikis or something. That'd be a lot of API work, but would probably be a positive change for the front page of the network. @MtMNC: Do you want to draw up a prototype layout for whatever you have in mind as far as front-end changes go, or would you like me to mess around with some design ideas?

**Comment by MtMNC** [comment]
@georgebarnick I don't have any layout ideas in particular... I was originally going to make a quick commit to fix the background lag, but that looks to be a bigger challenge than I first thought, so we might as well go all out. So yeah, if you have any ideas go ahead and mess around.

**Comment by MtMNC** [comment]
Well, I ended up starting a new design concept after all... :P Not sure what to put in terms of actual content though. Any feedback and ideas appreciated, and feel free to fork [MtMNC/splash](https://github.com/MtMNC/splash) and make changes.
<img width="1157" alt="blah" src="https://cloud.githubusercontent.com/assets/5515877/10533632/e4fece4a-7380-11e5-8c77-4980874403c4.png">

**Comment by georgebarnick** [comment]
Looks nice. Definitely needs a carousel or something else interactive and with motion there. If we could figure a way to have Great Ball Contraption spelled out (without being unreasonably large or word-wrapping too much) that could  potentially be a good idea. And while we're on the idea of making that site nav bigger and clearer, we should probably have something that summarizes each site's scope/purpose. At face value, "Customs" and "Ideas" don't really mean anything without clarification, and not everyone will know what GBC/Great Ball Contraption is until they navigate to the site (which admittedly greatballcontraption.com does do a good job explaining the topic to newcomers on their front page).

**Comment by codyn329** [comment]
![](http://i.imgur.com/eKdDpRu.jpg)
Here's a quick design concept I made in Adobe Comp for the main page, the idea is that it could be a carousel perhaps? Will add on more later but feedback would be great :D

**Comment by georgebarnick** [comment]
@codyn329: Nice! I love the geometry and the color palette for that. :smile:

**Comment by MtMNC** [comment]
@codyn329: That looks great! Go for it, I'd love to see it as a real page.

**Comment by codyn329** [comment]
thanks George and MtMNC, I'll try to code it when I have the time!
