### ISSUE TITLE
MediaWikiChat sidebar portlet fataling without wAvatar

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#416]
With MediaWikiChat's sidebar portlet enabled on a wiki without SocialProfile's ```wAvatar``` class, a fatal error occurs breaking every page that the sidebar portlet would appear on (so every page except Special:Chat when other users are in chat). Since ```$wgChatSidebarPortlet``` is ```true``` by default, this is a flaw that will break any wiki using the extension without SocialProfile. The error specifically as it occurred on http://biosector01.com is:

```
Fatal error: Class 'wAvatar' not found in /home/swert/biosector01.com/wiki/extensions/MediaWikiChat/MediaWikiChatClass.php on line 37
```

The only way to fix it without installing and setting up SocialProfile is to set ```$wgChatSidebarPortlet``` to ```false```, which is a suitable fix, however ideally that variable should not be able to cause a fatal error and that feature should work without avatars if necessary.

**Comment by mary-kate** [comment]
Proposed fix: https://gerrit.wikimedia.org/r/#/c/251707/
