### ISSUE TITLE
Without avatars, Chat PMs are disorganized

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#417]
Without SocialProfile avatars, distinguishing who sent which messages in PM is almost impossible.

![image](https://cloud.githubusercontent.com/assets/3800972/11023602/06253eaa-864c-11e5-9a6e-fbbf4e3f029e.png)

Any ideas for an enhancement to fix this for those who don't want SocialProfile on their wiki?

CC: @MtMNC

**Comment by MtMNC** [comment]
IIRC [https://www.mediawiki.org/wiki/Skin:Metrolook Metrolook] displays users' Gravatars (based on email, presumably). Might something like that work? The problem then would be if users registered with an email they don't want publicly associated with their account (like if a user signed up for the wiki with an email associated with a gravatar of their face, but they don't want their face associated with their account).

**Comment by UltrasonicNXT** [comment]
hmm. I deliberately didn't put a username in PMs because the field is normally very small, for me it's about half the size of your screenshot, so putting in usernames would use up all the space, especially with long usernames... I guess the obvious is if there's no avatar, taking an abbreviation of the username.

**Comment by georgebarnick** [comment]
Yeah I definitely don't think fitting a whole username in there would work very well. Perhaps do what Google does with default avatars nowadays: Just put a first letter inside an Avatar space with a colored background. 

![image](https://cloud.githubusercontent.com/assets/3800972/11074465/b9cead2a-87bd-11e5-8fa5-7141a63b64a7.png)

The colors and the letter helps distinguish who is who in long lists of contacts if they don't have a picture by their name. This could be an approach to take in private chat messages and even public chat if SocialProfile avatars don't exist.

Also, not related to this issue but something I want to ask you for @UltrasonicNXT: On each ```.mwchat-item-user``` in public chat, could that ```<td>``` also have a class based on the user ID of the user sending the message? So like if I sent a message it'd have ```<td class="mwchat-item-user mwchat-user-4"</td>``` or something like that (my Brickimedia user ID is 4)? That way CSS can be configured to change the colors of certain users names in chat like many wikis do on Recent Changes to distinguish admins from regular users.

**Comment by UltrasonicNXT** [comment]
Ah yeah that's a nice solution. Yeah guess so.

**Comment by UltrasonicNXT** [comment]
Right, I've had ago. This feature will need refining I think, but I have nowhere to properly test with lots of different users, so if you could update me (or show me that wiki) that would be cool :)

**Comment by georgebarnick** [comment]
I'll update it to BS01 right now to test at.

**Comment by UltrasonicNXT** [comment]
Colours are now much improved, and I've done those classes.

**Comment by georgebarnick** [comment]
Nice stuff. Only remaining issues are very minor style issues. I might see what it takes to set up gerrit on this computer and make some patches myself later.
