### ISSUE TITLE
HTML5 semantic elements in Refreshed

### ISSUE THREAD

**Issue by MtMNC** [Brickimedia/brickimedia#420]
Title says it all. If we drop IE8 support per https://github.com/Brickimedia/brickimedia/issues/407 switching to semantic elements shouldn't be a problem (see [Can I use...](http://caniuse.com/#feat=html5semantic)). It'd also be a good excuse to clean up the HTML a bit (for example there is a header and a header-inner element but there's no reason not to combine them).

Thoughts?

**Comment by georgebarnick** [comment]
Yes please

**Comment by codyn329** [comment]
Agreed with George and you too MtMNC. Semantic elements help with accessibility too and there's no downsides to using the good things that HTML5 provided, so this is a good move to make!

**Comment by MtMNC** [comment]
Started the switch on https://github.com/MtMNC/Refreshed/commit/5132607ee4e42173d9e0cdaab9fb6ee9f8059be5. Sometimes what element to use can be pretty subjective, any thoughts so far?

**Comment by georgebarnick** [comment]
Looks fine to me

**Comment by codyn329** [comment]
The sidebar's element should be an `<aside>` element, and since the footer has important links the `<ul>` should be wrapped inside a `<nav>` tag. Everything else so far looks good though :+1:

**Comment by MtMNC** [comment]
More changes... also fixed and reenabled the mobile logo that was disabled a while ago. It won't change anything unless a logo is defined in LocalSettings.php.

@codyn329 Good point about the sidebar, it's now an `<aside>`. According to [the spec](https://www.w3.org/wiki/HTML/Elements/nav), `<nav>` actually isn't needed if the links are inside a `<footer>`:
>The nav element is appropriate only for sections that consist of major navigation blocks. In particular, it is common for footers to have a short list of links to various pages of a site, such as the terms of service, the home page, and a copyright page. The footer element alone is sufficient for such cases, without a nav element.

I've left it out for now.

**Comment by MtMNC** [comment]
Just set up a pull request. The changes WILL break wikis' existing CSS. Any objections/suggestions?

**Comment by georgebarnick** [comment]
Oppose merging for now. All Brickimedia wikis currently have a caching issue to where any changes to MediaWiki:*.(css|js) pages do not take effect at all. I have asked @lewiscawte to debug and fix this as he set up the caching as it is, but as per usual, nothing that's asked of him ends up happening here. Maybe  @UltrasonicNXT can try to fix it, as it's clear it's not only holding back local communities from adding important features for their users, but also is holding back skin development now.

**Comment by MtMNC** [comment]
@lewiscawte @UltrasonicNXT @georgebarnick Any updates on the caching issue?

**Comment by georgebarnick** [comment]
Don't think anything has been done to fix it so I assume it's still a
present issue.

On Wed, Dec 16, 2015, 3:24 PM MtMNC <notifications@github.com> wrote:

> @lewiscawte <https://github.com/lewiscawte> @UltrasonicNXT
> <https://github.com/UltrasonicNXT> @georgebarnick
> <https://github.com/georgebarnick> Any updates on the caching issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brickimedia/brickimedia/issues/420#issuecomment-165229657>
> .
>
-- 
George Barnick
https://www.georgebarnick.photo

**Comment by MtMNC** [comment]
@georgebarnick Just tested some CSS on the dev wiki and it seems to work fine... or maybe it's the larger wikis that are having issues? If dev was affected before, I think it means we could safely pull https://github.com/Brickimedia/Refreshed/pull/39, close this, and then start on https://github.com/Brickimedia/brickimedia/issues/321.

**Comment by georgebarnick** [comment]
All I know is last time I tried to add useful CSS and JS on enbricki it didn't work. Even restarted memcached and everything and it was still stuck on the old revision. Same issue has been present at gbc ever since that wiki was opened, which is why http://greatballcontraption.com/wiki/MediaWiki:Common.js and http://greatballcontraption.com/wiki/MediaWiki:Refreshed.js loads everything from the user namespace instead. Haven't tried changing it since because right now it "works" and I don't want to risk making it completely not work.

**Comment by MtMNC** [comment]
Hmm... mind if I make a (small) CSS change to enbricki to see what happens? Like changing the line-height of the footer or something.

**Comment by georgebarnick** [comment]
Go for it. Need me to adjust your rights?

**Comment by MtMNC** [comment]
Wait actually I have the rights already since I'm in the sysadmin group, I'll do it right now

**Comment by MtMNC** [comment]
Didn't work. Created an issue for the caching problems at https://github.com/Brickimedia/brickimedia/issues/424.

**Comment by MtMNC** [comment]
It took a long time, but the changes to MediaWiki:Refreshed.css finally took effect on enbricki. Do you think we're good to pull https://github.com/Brickimedia/Refreshed/pull/39?

**Comment by georgebarnick** [comment]
Do we know how long it took for the cache to update the changed CSS? If we can isolate how long and at what time it reset, we could merge and pull Brickimedia/Refreshed#39 at a time where it would least disrupt viewers usage of the skin.

**Comment by MtMNC** [comment]
I edited the CSS at 3:44 PM EST yesterday, and I closed https://github.com/Brickimedia/brickimedia/issues/424 at 2:16 PM EST today, right after I noticed the CSS had updated. So, almost a day. But the CSS might have updated sooner and I just didn't see it until then... ¯\\\_(ツ)_/¯

**Comment by georgebarnick** [comment]
Let's go ahead and do that and do the merge and pull it by 3am tonight if possible

**Comment by MtMNC** [comment]
Alright, I'll change the CSS rn

**Comment by MtMNC** [comment]
I've made changes on all the wikis except:
* Stories (pretty sure that site isn't used anymore)
* Admin (don't have access)
* GBC (the CSS is in one of your user subpages so you're the only person who can change it--just add `#content-wrapper` to all rules with `#content` and `#header-wrapper)

So yeah. I'll be on the lookout for when it all propagates through and we can go from there.

**Comment by georgebarnick** [comment]
Stories can be skipped. Admin doesn't need any adjustments. I've updated GBC and transferred the CSS and JS out of my user CSS and JS. Once the text on http://greatballcontraption.com/wiki/User:ToaMeiko/Sandbox turns green it should have updated. Once that takes place I guess we'll pull the changes to the server.

**Comment by MtMNC** [comment]
The CSS has been updated on all sites, so whenever you have the chance you should be good to pull the changes. Merry Christmas btw. :)

**Comment by georgebarnick** [comment]
Merry Christmas! :christmas_tree: Pulled to the server but things aren't looking quite right at GBC:

![image](https://cloud.githubusercontent.com/assets/3800972/12004505/39789324-ab2c-11e5-81d3-a4ee62dce652.png)

Other wikis that I've checked seem fine though. A quick debugging would be good so that GBC can get back to normal operation.

**Comment by georgebarnick** [comment]
Scratch that, I've made the required changes to fix it (I suppose). Now just to wait till cache refreshes. Guess GBC is gonna be dealing with some glitchy skin for a few hours.

**Comment by codynguyen1116** [comment]
Is this supposed to happen?
![image](https://cloud.githubusercontent.com/assets/4723983/12004580/05adb814-ab2a-11e5-95e6-0b4248e353cb.png)

**Comment by georgebarnick** [comment]
Have you <a href="http://en.brickimedia.org/wiki/MediaWiki:Clearyourcache">cleared your cache</a>? I'm not having any display issues on enbricki

**Comment by codynguyen1116** [comment]
Ah it works now, thank you :)
