### ISSUE TITLE
Unable to create page with comments

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#422]
Trying to create a page which uses comments extension is producing a Server Error 500, and doesn't let you save the page. However, you can create a page without comments and then add the code for comments after.

As far as I know, this has only started in the last week or so.

**Comment by georgebarnick** [comment]
I had this happen as well.

**Comment by UltrasonicNXT** [comment]
@georgebarnick can you send me the url to SSH into the server? I've forgotten/can't find it

**Comment by georgebarnick** [comment]
@UltrasonicNXT ```ssh.brickimedia.org``` works I've been told. I have the IP in my hosts file and just do ```brickimedia```. If you need the actual URL just let me know.

**Comment by UltrasonicNXT** [comment]
Cheers

**Comment by UltrasonicNXT** [comment]
Can't replicate it on my local clone so this will be a tricky one.

**Comment by georgebarnick** [comment]
The issue kinda came out of nowhere. I don't think anything changed around the time that it started happening.

**Comment by NovaFlare** [comment]
This seems to have gone away for a while (I've been creating blogs and news reports without any problems, so I assumed this was fixed), but it's back now.

**Comment by UltrasonicNXT** [comment]
Hmm I just created a page in my userspace with comments fine.

**Comment by georgebarnick** [comment]
Can confirm that a user had an issue creating a blog yesterday until he
removed comments.

On Sun, Feb 7, 2016 at 10:34 AM Adam <notifications@github.com> wrote:

> Hmm I just created a page in my userspace with comments fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brickimedia/brickimedia/issues/422#issuecomment-181033502>
> .
>
-- 
George Barnick
https://www.georgebarnick.photo

**Comment by chriscook18** [comment]
I've got them working on both user and blog space.

**Comment by codynguyen1116** [comment]
http://meta.brickimedia.org/wiki/User:Codynguyen1116/test working now, so I'm closing
