### ISSUE TITLE
Cached PHP Breaks Refreshed for Anonymous Visitors

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#425]
This is what the site's looking like on Firefox on Mac OS:

![refreshedmacosfirefox](https://cloud.githubusercontent.com/assets/5195156/12033443/0606e984-ae77-11e5-8031-25f7ee991e2d.jpg)

An anonymous user reported this on our article feedback which is what alerted me to it- I don't have a modern version of Chrome or Safari so can't confirm that it's happening on these as well, but I think it's pretty safe to assume that it is.

**Comment by codynguyen1116** [comment]
Working fine on Chrome v47.0.2526.106. Went to the same page you were on also
![image](https://cloud.githubusercontent.com/assets/4723983/12035880/57e098de-ae06-11e5-9fd4-057939c5a031.png)

Can confirm the same issue on Firefox v39.
![image](https://cloud.githubusercontent.com/assets/4723983/12035931/f188b214-ae06-11e5-9d73-cd5e33ee0598.png)

However, logging in seems to do the trick ->
![image](https://cloud.githubusercontent.com/assets/4723983/12035944/179fc000-ae07-11e5-9df7-7d0d54560e76.png)

**Comment by georgebarnick** [comment]
Unable to replicate in Firefox 43.0.3:
![image](https://cloud.githubusercontent.com/assets/3800972/12036233/0e7e4c52-ae12-11e5-8f26-690d8da36f38.png)

**Comment by MtMNC** [comment]
Happened to me on FF 43.0.3 on the latest version of OS X (10.11.2--OS shouldn't make a difference though). Checked the HTML and it's a caching issue (it's loading the old PHP but the new CSS). Not sure how to fix it other than to just wait it out until the PHP propagates through though....

**Comment by georgebarnick** [comment]
Restarted memcached. May or may not have fixed it, but let me know if it did.  If not we just wait I suppose.

**Comment by NovaFlare** [comment]
I keep gettting 502/504'd, so can't check it :(

**Comment by codynguyen1116** [comment]
Nope, still hasn't worked in Chrome v47 and in Firefox v39. I'll update Firefox though to the latest version, and see if anything has changed

**Comment by MtMNC** [comment]
I think it has to do if you're logged in or not. Tested on Chrome, Safari, and FF and it's broken when I'm logged out and looks fine when I'm logged in. Based on the screenshots and descriptions above it sounds like it's the same for everyone else as well. So maybe the site is serving cached PHP to all anonymous users and when logging in it forces the site to use the up-to-date version?

**Comment by NovaFlare** [comment]
Seems to be working fine now for me (Firefox 40.0.3, Mac OS), as I said, I can't comment on the others though, sorry.

**Comment by georgebarnick** [comment]
Checked Edge and can replicate the issue. But anonymous caching is something we should investigate further than just the skin. Currently everything on the page is cached for anonymous users, including templates, which as an example on Brickipedia, means that the "On this day" is several days behind. Separate issue should be started for this to determine best caching options.

![image](https://cloud.githubusercontent.com/assets/3800972/12065699/ca6d2468-afa9-11e5-8a46-689a7c1e1771.png)

**Comment by codynguyen1116** [comment]
Same thing happening on Opera

**Comment by MtMNC** [comment]
Def not a browser/OS issue, it's a case of the wrong PHP being served to the user

**Comment by georgebarnick** [comment]
Cache should be good on this issue for now. Anons still get cached PHP but it's not completely broken anymore (some still get cached JS preventing dropdowns from working, but that'll resolve itself in a week or so).

**Comment by codynguyen1116** [comment]
Someone needs to reopen this as it is clearly still an issue for anonymous users

**Comment by MtMNC** [comment]
From #436

@codynguyen1116: 

>I was scrolling through meta, and I saw someone uploaded this image:

>![image](http://images.brickimedia.org/1/13/GBC_Site_Error_when_Logging_in_mainpage_Screenshot_2016-01-17_10.53.53.png)

>(source: 
http://meta.brickimedia.org/wiki/File:GBC_Site_Error_when_Logging_in_mainpage_Screenshot_2016-01-17_10.53.53.png)

>From what's been given through the screenshot: the MW skin is Refreshed, the browser being used is Chrome,  although I don't know what version nor the OS. I've asked the uploader ([Mjsweet](http://meta.brickimedia.org/wiki/User_talk:Mjsweet)) for more information and he/she hasn't responded yet although this is still an issue that should be fixed.

codynguyen1116:

>__UPDATE:__ I realized this issue relates to #425, meaning that the browser and OS doesn't matter in this situation. It's been said it'd resolve itself in about a week and it's been a week, however it's still a problem. I suggest #425 should be reopened and to be given more focus.

MtMNC:

>~~I noticed this one when the PHP was cached a while ago, but it's resolved itself for me at least. There are some other CSS problems (e.g., hamburger icon background is the wrong color) but I think that's an issue with local CSS (to be fixed by the site) rather than one with Refreshed.~~

>~~Here's a screenshot (logged out, which is where the PHP was broken before). Could you post a screenshot so we could see what other UI issues there might be?~~

>Actually that's because I was looking at the Recent Changes, but it's only happening on the main page. On the other wikis the main page stayed broken the longest. So at least most of the way through fixing itself? Also the IP address in the screenshot is the same one that shows up for me, so this is probably a CloudFlare issue. I'll reopen #425.

**Comment by codynguyen1116** [comment]
So like George said, this would eventually solve itself and it did, tested on browsers and wikis while logged out so I'm closing. 

If anyone still has issues then either re-open or comment and request for re-open, thanks!
