### ISSUE TITLE
Server timing out constantly (Error 502/504)

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#426]
^

**Comment by georgebarnick** [comment]
I've already tried to fix it several times over the past few hours and can't get the site to stay online. Rebooting it hasn't solved anything (except for one time when I got the site up for a minute or so before crashing again). Memory isn't being overloaded and server is up so I don't know what to do.

**Comment by georgebarnick** [comment]
@UltrasonicNXT @lewiscawte

**Comment by NovaFlare** [comment]
Been down for over a day now, not cool especially with the launch of a stack of new 2016 sets (thanks for trying to fix it though Meiko :)  )

**Comment by LK901** [comment]
Maybe it's just bad luck, but I've been unable to check the site the last four (4!) times I've tried visiting... :/

If this could be fixed ASAP, it would be great.

**Comment by lewiscawte** [comment]
I spent a good part or a rather sleepy hour before work trying to fix this
when it was first filed.

**Comment by UltrasonicNXT** [comment]
It's now up after I restarted php5-fpm, but I don't know how to stop it happening.

**Comment by UltrasonicNXT** [comment]
Think it's gone again

**Comment by ALittleSlow** [comment]
Any clues in the log files? If it's not memory, maybe it's some other critical resource that's missing or running out. If we're out of options, give me access and I'll take a look.

**Comment by georgebarnick** [comment]
I tried checking the error logs on day 1 and 2 of the downtime but couldn't find any clues. We get so many errors in that log it's hard to filter out which are critical and which aren't...

**Comment by georgebarnick** [comment]
Apparently this has been fixed. Any idea what fixed it or what the initial issue was?

**Comment by georgebarnick** [comment]
Down again. :/

**Comment by codynguyen1116** [comment]
Back up now

**Comment by georgebarnick** [comment]
I've been keeping an eye on ```htop``` and while it was working, it was easy to follow server activity, but then everything abruptly comes to a stop.

![image](https://cloud.githubusercontent.com/assets/3800972/12083838/4caef8b8-b278-11e5-9461-8b11b085a2ac.png)

CPU usage is at an absolute 0%. Nothing's taking place, and there's no identifiable reason why this is happening.

**Comment by georgebarnick** [comment]
And without changing or touching anything, it's started back up, about 45 mins to an hour later.

**Comment by chriscook18** [comment]
Not sure if related, but for a five minute period or so earlier, semantic #declares were showing up on the articles. Stopped happening a few minutes later.

**Comment by codynguyen1116** [comment]
So yeah the site used to be up but it's back down again

**Comment by ALittleSlow** [comment]
Frustrating. Could someone be messing with us?

-----
Nous sommes tous français.

**Comment by codynguyen1116** [comment]
Yeah that could be a possibility, but it doesn't seem like there's enough evidence for that. We can keep that option open up though

**Comment by UltrasonicNXT** [comment]
@ALittleSlow highly doubt it, we haven't seen any spike in request numbers or anything. However, I made some config changes today, and haven't seen an 502/4s since, so we might be finally getting close to fixing this.
