### ISSUE TITLE
MediaWikiChat Opera web notifications

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#427]
Since Opera supports web notifications this would be a nice feature. This is a __low priority__ and isn't important but would be great to have integrated into the extension eventually.

http://caniuse.com/#feat=notifications

**Comment by chriscook18** [comment]
Note: notifications occur on Windows 10, but through the inbuilt Windows 10 notifications system instead of the browser.

**Comment by codynguyen1116** [comment]
Does anyone have another operating system besides Windows 10 (besides the two of us) where they can test this?

**Comment by georgebarnick** [comment]
I have a remote linux server with a Unity GUI that I can test in next time
I'm at that computer which idk when it'll be

On Sat, Feb 20, 2016 at 2:18 PM Cody Nguyen <notifications@github.com>
wrote:

> Does anyone have another operating system besides Windows 10 (besides the
> two of us) where they can test this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brickimedia/brickimedia/issues/427#issuecomment-186668334>
> .
>
-- 
George Barnick
https://www.georgebarnick.photo

**Comment by UltrasonicNXT** [comment]
really, through the windows toast notifications that appear in the sidebar/taskbar? That's well cool if it is

**Comment by codynguyen1116** [comment]
Closing per https://phabricator.wikimedia.org/T134667
