### ISSUE TITLE
Refreshed dropdown menus don't work

### ISSUE THREAD

**Issue by UltrasonicNXT** [Brickimedia/brickimedia#428]
Since update to 1.26.

Sometimes they do work when editing pages

**Comment by UltrasonicNXT** [comment]
https://github.com/Brickimedia/Refreshed/blob/master/refreshed/refreshed.js#L174 is the offending line

**Comment by georgebarnick** [comment]
@UltrasonicNXT don't believe that was the issue

**Comment by chriscook18** [comment]
It seems to be namespace dependent? Search, dropdowns and notifications work fine on Special pages and Brickipedia namespace, but not on user talk pages

**Comment by georgebarnick** [comment]
@MtMNC are you able to help debug?

**Comment by UltrasonicNXT** [comment]
I think it's because the refreshed scripts (among others) seem to be loaded before jquery

**Comment by UltrasonicNXT** [comment]
https://github.com/Brickimedia/Refreshed/blob/master/Refreshed.skin.php#L27

**Comment by UltrasonicNXT** [comment]
Okay well the reason nothing is happening is because https://github.com/Brickimedia/Refreshed/blob/master/refreshed/refreshed.js#L124 isn't being triggered

**Comment by UltrasonicNXT** [comment]
JS needs rewrite though

**Comment by georgebarnick** [comment]
The Refreshed toolbar dropdown doesn't work though ("more" / "tools" button in the edit, history, etc tools bar)

**Comment by MtMNC** [comment]
Afraid I can't right now, my computer's in for repairs... I should get it back this weekend though.

**Comment by georgebarnick** [comment]
No worries. We're working to resolve any lingering bugs. Once you get back you can take a look at some of the code for Refreshed and maybe help clean it up and make it more efficient. :)
