### ISSUE TITLE
No users appear in chat, even when they are there

### ISSUE THREAD

**Issue by chriscook18** [Brickimedia/brickimedia#429]
In the chat itself, the sidebar is empty, although people (at least, the first time I loaded it) could talk. Despite this, people still show up in the sidebar on other pages as being in chat.

To see if this was a temporary thing, I refreshed the page, and now I just get a grey enter text box that won't let me send messages. 

I shall assume its related to the completion of #411

**Comment by UltrasonicNXT** [comment]
Looks like no javascript is running. Probably the same cause as #428

**Comment by UltrasonicNXT** [comment]
https://github.com/Brickimedia/Refreshed/blob/master/refreshed/refreshed.js#L174 is the offending line

**Comment by georgebarnick** [comment]
@UltrasonicNXT don't believe that was the issue

**Comment by UltrasonicNXT** [comment]
It works on vector you see (at least for me)

**Comment by UltrasonicNXT** [comment]
and vector doesn't have an error in the JS console caused by that line, that line gives a ```TypeError: $(...).parent(...).tap is not a function``` in the JS console on refreshed

**Comment by UltrasonicNXT** [comment]
It's working for me right now though, anybody else?

**Comment by chriscook18** [comment]
@UltrasonicNXT Working for me right now.

**Comment by georgebarnick** [comment]
Works for me. Can't say it's the same issue as #428 though even though they were happening simultaneously and were simultaneously fixed at the same time. Special:Chat used to have working dropdowns for me but they stopped working. online users in chat is still working for me though.
