### ISSUE TITLE
Thanking broken

### ISSUE THREAD

**Issue by Berrybrick** [Brickimedia/brickimedia#430]
I tried to thank Nova for an edit, and got an internal error. The page showed this:

a92eb6de] /wiki/Special:Thanks/990037 MWException from line 357 of /var/www/core/includes/htmlform/HTMLForm.php: Cannot change display format after creation, use HTMLForm::factory() instead

Backtrace:

#0 /var/www/core/extensions/Thanks/SpecialThanks.php(93): HTMLForm->setDisplayFormat(string)
#1 /var/www/core/includes/specialpage/FormSpecialPage.php(117): SpecialThanks->alterForm(HTMLForm)
#2 /var/www/core/includes/specialpage/FormSpecialPage.php(153): FormSpecialPage->getForm()
#3 /var/www/core/includes/specialpage/SpecialPage.php(384): FormSpecialPage->execute(string)
#4 /var/www/core/includes/specialpage/SpecialPageFactory.php(553): SpecialPage->run(string)
#5 /var/www/core/includes/MediaWiki.php(281): SpecialPageFactory::executePath(Title, RequestContext)
#6 /var/www/core/includes/MediaWiki.php(714): MediaWiki->performRequest()
#7 /var/www/core/includes/MediaWiki.php(508): MediaWiki->main()
#8 /var/www/core/index.php(41): MediaWiki->run()
#9 {main}

Thank you.

**Comment by chriscook18** [comment]
What edit where you trying to thank? I just thanked a few random edits and they all said seemed to work.

**Comment by UltrasonicNXT** [comment]
Just updated Thanks, I think that should fix it
