### ISSUE TITLE
Objects on brickimedia header don't respond to tap on mobile

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#431]
Whenever I tap on anything on the header such as:
- The hamburger icon which should pull up a sidebar
- The user avatar, which should pull up a user dropdown menu
- Magnifying glass icon, which should pull up a search box.

Nothing happens - a single tap doesn't do anything and a double tap just zooms the screen into that tapped area. 

![image](http://i.imgur.com/7hZumxe.png)

**Comment by georgebarnick** [comment]
Header scripts have been and still need rewriting for the most part.

@UltrasonicNXT @MtMNC

**Comment by chriscook18** [comment]
Doesn't seem to be an issue on Chrome on an S3. (Although there is a separate issue where the search box and notifications start off screen - I'll screenshot them at some point).

**Comment by georgebarnick** [comment]
@codynguyen1116 Also please try logging in to make sure you aren't being served an out of date cache of the skin.

**Comment by codynguyen1116** [comment]
Ah okay I logged in, it's just part of #425 but if the code for the headers still need rewriting, I'll keep this open. Although when I logged in, there are problems with echo on mobile which I'll put into a new issue.

**Comment by codynguyen1116** [comment]
Tested the site while logged out on Safari, Chrome, and Firefox for iOS on my iPhone 5S and everything worked fine. I'm assuming the bug is gone now but if people are still having issues, feel free to reopen this
