### ISSUE TITLE
Echo extension is not responsive

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#432]
The echo extension isn't responsive, such as when viewed on mobile like an iPhone 5S. The messages and alert boxes' heights also get taller when scrolling down
(screenshot of echo when scrolled to ~about the middle of the page)
![image](http://i.imgur.com/QqBq8wp.png)

**Comment by chriscook18** [comment]
I was going to screenshot the same message box size issue from Chrome/S3, although the content usually loads for me. Does a similar thing happen if you try and search @codynguyen1116 ?

**Comment by MtMNC** [comment]
The text might actually be there, just white. I'll try and take a look later today.

**Comment by codynguyen1116** [comment]
Yep content loads for me too it's just the fact that the message box is _covering_ the content. Also @chriscook18 there is a bug with the search issue where it gets overlapped by the hamburger icon (which should be separated into a new issue for organization) although I'll post a screenshot of it anyways. I'm thinking it could be fixed with a simple css property ```z-index``` fix. 

![image](http://i.imgur.com/RBqFDh1.png?1)

**Comment by chriscook18** [comment]
Okay, so that issue is the same as my search issue - by content though, I meant the notification drop-down having content.

**Comment by codynguyen1116** [comment]
Gotcha, moving the issue to #433. As far as the content it actually loads its just being pushed to the left  so much that it can't be seen

**Comment by georgebarnick** [comment]
Echo needs to be repositioned and probably re-engineered for our mobile skin anyways. Since it updated with 2 separate icons it's gonna take up valuable space in the mobile skin.

**Comment by chriscook18** [comment]
Okay, so Chrome/S3 we have 
![screenshot_2016-01-10-17-50-09](https://cloud.githubusercontent.com/assets/13189252/12223271/4d3a807a-b7ca-11e5-8a85-a73f30547ec1.png)

and 

![screenshot_2016-01-10-17-51-37](https://cloud.githubusercontent.com/assets/13189252/12223275/6560c664-b7ca-11e5-89d5-024e0d6490b7.png)

**Comment by codynguyen1116** [comment]
@chriscook18 Please move your comment to #433 since it's been created now, thanks ;) (although those are useful screenshots)

**Comment by MtMNC** [comment]
The version of Echo we have installed now is very different from what we had before. The problem is we probably need to support both....

For the old version we hid the icon on small, and instead a notifications item appeared in the user dropdown menu. There'd be a little red rectangle in the corner of the user's avatar to indicate there were new notifications. Would something similar to that be good for the new version do you think?

**Comment by codynguyen1116** [comment]
I'm sketching out some ideas that we can put into code but I think instead of just a box there should be a bell icon so it makes more sense to users (and then with WikiFont we can just use CSS to make it red). Then a small number on the upper right of the bell in a small rectangle (this is apparently called a badge according to Google Material Design, I never knew there was a term for this :P)

**Comment by codynguyen1116** [comment]
Actually haha sorry I misread your comment, I actually like your idea better than mine since it's better use of space :) should still be noticeable too

**Comment by codynguyen1116** [comment]
@MtMNC @georgebarnick We can also give feedback on the splits on https://www.mediawiki.org/wiki/Topic:Sw196pvf5vwt6pku and https://phabricator.wikimedia.org/T123018

(Not entirely related but since we're a wiki farm this is something we would be interested in: https://www.mediawiki.org/wiki/Help:Notifications/Cross-wiki)

**Comment by codynguyen1116** [comment]
Adding another reference @MtMNC @georgebarnick 
https://phabricator.wikimedia.org/T108190 - Cross wiki / global notifications

**Comment by MtMNC** [comment]
Put this on Phabricator: https://phabricator.wikimedia.org/T126106

**Comment by codynguyen1116** [comment]
Closing since moved upstream
