### ISSUE TITLE
Search box is overlapped by hamburger icon

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#433]
Search box is overlapped after tapping the magnifying glass icon. 
![image](http://i.imgur.com/RBqFDh1.png?1)

**Comment by chriscook18** [comment]
Okay, so Chrome/S3 we have 
![screenshot_2016-01-10-17-50-09](https://cloud.githubusercontent.com/assets/13189252/12223271/4d3a807a-b7ca-11e5-8a85-a73f30547ec1.png)

**Comment by codynguyen1116** [comment]
That's weird, not sure why the magnifying glass icon doesn't appear after tapped :S

**Comment by chriscook18** [comment]
strangely enough, I get something slightly different searching it again. (in terms of width, the X now shows up in the corner without having to scroll right.)
![screenshot_2016-01-10-19-01-29](https://cloud.githubusercontent.com/assets/13189252/12223358/e2c9dc56-b7cc-11e5-9761-0e9210236ebc.png)

**Comment by georgebarnick** [comment]
Mine looks about the same.

![image](https://cloud.githubusercontent.com/assets/3800972/12223394/49f13be6-b7a4-11e5-9498-c3a2e100a95a.png)

**Comment by MtMNC** [comment]
Should be fixed now.
