### ISSUE TITLE
WikiForum redesign and UX

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#437]
# About
The WikiForum extension has been poorly designed and needs to be revamped. It'll provide better consistency with MediaWiki overall and also better UX. (__NOTE:__ This issue I'd say IMO is almost high or as high as a priority as #434) Here are the issues, and here's how they can be improved. I'll also provide sketches/rough drafts of what new appearance pretty soon today.

Another __NOTE__: I greatly encourage for other people to provide feedback on each idea's, and to also provide rough drafts for a new look that fixes most of the issues listed below. Then, we can take the best of each one and combine to create a beautiful forum extension that's also functional :) :+1: 

# Issues
- [ ] Icons:
   - __Problem:__ All these icons have too much detail and thus distracting. 
   - __Solution:__ Replace all current icons with the WikiFont ([munmay/WikiFont](https://github.com/munmay/WikiFont)) icon set. Icons are simpler and to the point.
- [ ] Typography:
  - __Problem:__ An odd mixture of two different fonts, Arial and Verdana. Verdana is a poorly designed font and isn't very nice to read. 
  - __Solution:__ Make the base font just Arial so that other wikis can change it to what they like, and then with our local wiki CSS we can change it to "Lato" for headings, and "Lato Body" for the body to make it consistent with our typography at Brickimedia.
- [ ] Non-responsive UI:
    - __Problem:__ Doesn't degrade gracefully across devices. Was designed desktop first without consideration for phones and tablets. 
    - __Solution:__ Recode the entire thing basically, easier to start back from scratch.
- [ ] Search:
    - __Problem:__ It isn't functional at all. Tried searching up "LEGO" on the Brickipedia WikiForum and it said it popped up with 0 hits yet gave me one single random thread, instead of giving an actual list of threads in a search result format. 
   - __Solution:__ Like above, it's easier to start back from scratch.
- [ ] More functions please! As a user, I should be able to: (there's probably some other stuff that this extension needs but I can't think of too many so far, I'll edit when I come up more )
  - Permalink to comments
  - Like/dislike comments

# Rough draft
Starting on paper, then we get to a good rough draft we can move to the final draft which would be in code form. How's that transition idea? (this section will be updated later today)

**Comment by georgebarnick** [comment]
This would be better to submit upstream because Brickimedia is not the sole/primary developers for the extension nor the sole users of it.

**Comment by codynguyen1116** [comment]
Will do, I'll close this

**Comment by georgebarnick** [comment]
Please link to a Phabricator ticket once you create one

**Comment by codynguyen1116** [comment]
https://phabricator.wikimedia.org/T123881
