### ISSUE TITLE
Labels and milestones

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#438]
GitHub is an amazing website and company that gives many functions that we're not using as much as we should! Part of them are labels and milestones, and releases.   

# Labels
Sorting by color and with prefix helps, so you have a nice list of all the labels in an organized manner (plus prefixes help for knowing which is which for users who come from our community that might be color blind or some color deficiency). If people like this idea but don't want to do it I can reorganize the labels on this repository and re-label issues myself 

* Pink: For browser labels
* Pale blue: For device labels
* Blue: For extension labels
* Teal: For feedback labels
* Green: For improvement labels
* Red: For inactive labels
* Orange: For MediaWiki version labels
* Sky blue: For mediawiki skin labels
* Yellow: For wiki-specific labels

(__SOURCE__: https://github.com/codynguyen1116/repository-test/labels?sort=name-asc)

![image](https://cloud.githubusercontent.com/assets/4723983/12379503/13a57d4e-bd22-11e5-8610-3dd9f06c6727.png)
![image](https://cloud.githubusercontent.com/assets/4723983/12379506/232a13a6-bd22-11e5-9b3f-4c3ffbbc499a.png)
![image](https://cloud.githubusercontent.com/assets/4723983/12379509/29e1510a-bd22-11e5-9367-61b0c9afef19.png)
![image](https://cloud.githubusercontent.com/assets/4723983/12379571/d5da3738-bd22-11e5-82d6-3b079e4a5f8f.png)

# Milestones
Add a Q1 2016, Q2 2016, Q3 2016, and Q4 2016. Why not also maybe add Q1 2017, Q2 2017, Q3 2017, and Q4 2017? 

# Releases
We should take advantage of these more (unless if MediaWiki already handles this itself?) It'd be useful since it provides a history of all the major and minor release versions. Here's what it can look like ```x.y.z``` or ```[major].[minor].[release]```. It can follow the syntax by the top answer at http://stackoverflow.com/questions/615227/how-to-do-version-numbers

**Comment by codynguyen1116** [comment]
I'm going to wait a couple day for comments and if you guys are fine with this change then I'll reorganize every issue in this repo (will try my best to fit it in one of these school days if I have time, otherwise the organizing will take place on a weekend).

**Comment by codynguyen1116** [comment]
Adding a report from NovaHawk and CJC95, they said it looks good

**Comment by MtMNC** [comment]
Looks good, I say go for it.

**Comment by Berrybrick** [comment]
Okay, but don't value my opinion over a developer.

**Comment by UltrasonicNXT** [comment]
yeah sounds good

**Comment by codynguyen1116** [comment]
I've reorganized about 69 out of 360 issues so far, which is 19.16% of all the issues, I'll get some more in tomorrow.

**Comment by codynguyen1116** [comment]
One more thing, do you guys have any suggestions of what the labels in the general category (bug, splash, request, and API) should be separated into more specifically?

**Comment by codynguyen1116** [comment]
Didn't count this time, but I think I got around 100+ more issues cleaned up, also added SMW version labels, OS (operating systems) labels, and priority labels which we should definitely use.

**Comment by codynguyen1116** [comment]
Last two labels to clean up are 'bug' and 'global', after this I'll close this :)

**Comment by codynguyen1116** [comment]
Done! Everything looks great now
