### ISSUE TITLE
Global user stylesheets aren't being applied correctly

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#439]
Reports from users have said that personal CSS (such as user's global.css) isn't being applied while they view the website. Apparently it's already been noted but from what I know nothing has been done so far, and it's best to keep every problem noted on one site to centralize everything, so here's the issue.

**Comment by NovaFlare** [comment]
Just to clarify- local CSS is working fine (eg, en's User:username/deepsea.css / User:username/refreshed.css), it's just the global ones like meta's User:username/global.css. It's possible that it's something as simple as the [GlobalCssJs] (http://www.mediawiki.org/wiki/Extension:GlobalCssJs) extension needing an update.

**Comment by codynguyen1116** [comment]
I wish it was simple as that, but GlobalCssJs got updated https://github.com/Brickimedia/extensions/commit/77b0530235f32ab5cb148bd95a299ae9e5c51975

**Comment by georgebarnick** [comment]
```
[1/12/2016 3:33:42 PM] George Barnick: global JS (and I suppose CSS probably too) isn't working
[1/12/2016 6:20:02 PM] Adam Carter: If there's no bug report it didn't happen :)
[1/12/2016 6:20:50 PM] George Barnick: cba to put in a bug report for everything I find
[1/12/2016 6:21:09 PM] George Barnick: we'd get banned from GitHub for taking up too much space if I put in a bug report for everything I find
[1/12/2016 6:21:19 PM] Adrian: lololololo
```

so I'm glad someone put it here

**Comment by NovaFlare** [comment]
It appears that it may not just be global user files- I just checked en's main page appears to be messed up.

**Comment by codynguyen1116** [comment]
@NovaFlare I see what you mean, although I do say that all the main pages on every wiki need a revamp anyways. :P

**Comment by NovaFlare** [comment]
Please ignore anything related to the main page- turns out MeikoBot broke it, so this is completely unrelated.

**Comment by UltrasonicNXT** [comment]
okay cool, that was worrying me and I couldn't find the issue

**Comment by codynguyen1116** [comment]
working now [218637](http://meta.brickimedia.org/index.php?diff=218637), closing
