### ISSUE TITLE
Refreshed blogpage headers are shown as article headers

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#440]
Not sure why the refreshed article's header HTML is being replaced with BlogPage header's HTML, but it is. Here's a screenshot: (using Chrome 47.0.2526.111 on Windows 10) 

![image](https://cloud.githubusercontent.com/assets/4723983/12471281/b6fc1466-bfc1-11e5-9401-7155b2a11017.png)

**Comment by georgebarnick** [comment]
Kinda just want to get rid of BlogPage extension and maybe design something else. BlogPage just doesn't work for us. The only thing it does good for is make a special page to create a blog post, but not everyone uses that and it'd be easy enough to replace with my <a href="http://en.brickimedia.org/wiki/User:ToaMeiko/createpage.js">createpage script</a> I've been working on. I can envision a better blogpage system in Semantic MediaWiki if I could get with @NovaFlare or someone else proficient in SMW to actually put my ideas into code.

**Comment by NovaFlare** [comment]
Oh dear. Can confirm that this isn't localised to a certain browser, wiki or skin. What's interesting is that the blog header is appearing on all mainspace articles, but is not appearing on any blogs. So I'm guessing something's targeting the wrong namespace for some reason.

@georgebarnick: It should be very easy to just make a Semantic form for people to create blogs with, we really have no use for the blog extension at all these days- all we need is the comments extension.

**Comment by codynguyen1116** [comment]
Sounds easy enough - We should still be able to provide a page to view all blog pages, and being able to filter by date creation, author, least/most popular (done by number of comments), but I'm assuming we can do that with SMW already, right? Maybe there's more functions needed for blogs but I can't really think of anything else as of now.

**Comment by NovaFlare** [comment]
Yep, that can all be done with SMW.

However, this appears to be more serious than we thought- apparently [anons can't edit the mainspace] (http://en.brickimedia.org/index.php?title=User_talk:NovaHawk&diff=1025449&oldid=1025444) because they're being told that you have to log in to edit a blog, so this isn't just an aesthetic thing. Any chance we can just remove the extension now since it's only causing bugs and there's literally no reason for having it at the moment (assuming as we still keep the user blog namespace)?

**Comment by georgebarnick** [comment]
The page to view all blogs and put filters on it can be done with SMW and
will be less buggy than the existing BlogPage extension. I think it's about
time to get rid of it so I'll uninstall it ASAP and will see about
installing Semantic Forms.

On Thu, Jan 21, 2016 at 11:38 PM NovaFlare <notifications@github.com> wrote:

> Yep, that can all be done with SMW.
>
> However, this appears to be more serious than we thought- apparently anons
> can't edit the mainspace
> <http://en.brickimedia.org/index.php?title=User_talk:NovaHawk&diff=1025449&oldid=1025444>
> because they're being told that you have to log in to edit a blog, so this
> isn't just an aesthetic thing. Any chance we can just remove the extension
> now since it's only causing bugs and there's literally no reason for having
> it at the moment (assuming as we still keep the user blog namespace)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brickimedia/brickimedia/issues/440#issuecomment-173804548>
> .
>
-- 
George Barnick
https://www.georgebarnick.photo

**Comment by georgebarnick** [comment]
@NovaFlare do we <i>need</i> Semantic Forms or can it be built into the createpage script I'm working on? Minifying the amount of extensions we use isn't entirely necessary but something I've lightly been pushing towards for a while. Plus, it wouldn't be that hard to integrate. Right now I'm the only one developing for that script port to our wiki but if we could get it to a production state it'd be useful globally I'm sure.

![image](https://cloud.githubusercontent.com/assets/3800972/12503751/550bebd4-c0a5-11e5-9aa3-8dcb7515c306.png)

**Comment by NovaFlare** [comment]
Yep, that would be totally doable. I'd suggest a separate page though (without any options) and just creates a blog and preloads {{comments}}. Also, can we move "User blog" to "blog"? There's no real need to call it user blog is there?

**Comment by georgebarnick** [comment]
Keeps it familiar to those from Wikia and keeps it uniform with the User namespace. Also if we change it now, any search rankings for existing blogs would be lost.

**Comment by codynguyen1116** [comment]
This was closed via the commit summary wording, and technically since it's not a bug anymore that's acceptable, but there's still discussion so I'm reopening a new issue which is for planning the new blog system at #444

**Comment by georgebarnick** [comment]
It wasn't closed by the commit summary, I closed it myself since it was no longer an issue.
