### ISSUE TITLE
Extension:Thanks gone?

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#441]
Is there any reason why we no longer have this extension?

**Comment by georgebarnick** [comment]
Wasn't removed to my knowledge. @codynguyen1116 must have removed it.

**Comment by codynguyen1116** [comment]
@NovaFlare my bad, I wasn't aware I accidentally removed it. I'll push a commit to extensions repo to add it back

**Comment by UltrasonicNXT** [comment]
Done
