### ISSUE TITLE
Page history is broken

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#442]
Hitting "diff" or "hist" on anything loads a blank page (as does pressing the "history" tab on a page obviously). Tested on multiple skins and browsers.

**Comment by codynguyen1116** [comment]
Tested on the main pages of all wikis, and their history, I keep receiving a 500 in return in the console.

**Comment by georgebarnick** [comment]
```
2016/01/23 00:45:35 [error] 2222#2222: *4590945 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 4 passed to ThanksHooks::insertThankLink() must be an instance of User, none given in /var/www/core/extensions/Thanks/Thanks.hooks.php on line 43" while reading response header from upstream, client: 108.44.150.7, server: *.brickimedia.org, request: "GET /index.php?title=Main_Page&action=history HTTP/1.1", upstream: "fastcgi://unix:/tmp/php5-fpm.sock:", host: "en.brickimedia.org", referrer: "http://en.brickimedia.org/wiki/Main_Page"
```

**Comment by codynguyen1116** [comment]
Hey, maybe accidentally removing that thanks extension was a good thing. :P Although hey it's back again. Just checked and looks like this was the breaking change:

https://github.com/wikimedia/mediawiki-extensions-Thanks/commit/ee7ca911f226a15b0c3435d7036dbb32cdacb148

**Comment by UltrasonicNXT** [comment]
Corr that is a poor commit

**Comment by UltrasonicNXT** [comment]
https://phabricator.wikimedia.org/T124532

**Comment by UltrasonicNXT** [comment]
Fixed
