### ISSUE TITLE
Disable issues at SocialProfile repo

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#443]
The SocialProfile located at [Brickimedia/SocialProfile](https://github.com/Brickimedia/SocialProfile) shouldn't have issues enabled, all the issues should be centralized at this repository, [Brickimedia/brickimedia](https://github.com/Brickimedia/brickimedia). Whoever has access to that repo's settings should disable it

**Comment by UltrasonicNXT** [comment]
I've deleted it, it's unneeded
