### ISSUE TITLE
SyntaxHighlight GeSHi

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#445]
Is there any reason why the SyntaxHighlight GeSHi extension isn't working, and is it possible that it could be fixed?

**Comment by georgebarnick** [comment]
It was disabled due to breaking the site in Brickimedia/LocalSettings@7b3947a. It's current status is unknown to me.

**Comment by codynguyen1116** [comment]
Are we using the wrong branch for the syntax highlighter extension, ex we might be accidentally using a WMF or dev branch?

**Comment by georgebarnick** [comment]
We're on wikimedia/mediawiki-extensions-SyntaxHighlight_GeSHi@a15f02e which is REL1_26

**Comment by codynguyen1116** [comment]
Closing because we don't really even use this extension nor need it so :P
