### ISSUE TITLE
Install quiz extensions for Customs

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#446]
It looks like the quiz section on the revamped wiki is going ahead, would someone please be able to install [QuizGame] (https://www.mediawiki.org/wiki/Extension:QuizGame), [PictureGame] (https://www.mediawiki.org/wiki/Extension:PictureGame) and [PollNY] (https://www.mediawiki.org/wiki/Extension:PollNY) for customs?

**Comment by codynguyen1116** [comment]
Added labels for organising, although since I don't know to add extensions as git submodules I'm going to assign Adam (@UltrasonicNXT) to do this

**Comment by mary-kate** [comment]
"Given enough eyeballs, all bugs are shallow."

(And for any and all social issues, there are the respective thresholds to limit who can create polls/quizzes/etc. to prevent them from being abused by people who sign up solely to focus on the social aspect of the site as opposed to making edits, which is usually the main "goal" of a wiki.)

**Comment by codynguyen1116** [comment]
True true, I think we have a decent-sized community so hopefully it shouldn't be so bad

**Comment by UltrasonicNXT** [comment]
Done
