### ISSUE TITLE
Restyle CloudFlare error pages

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#452]
Was browsing some wikis while gaming and found out that Curse Network has customized CloudFlare error pages.

![image](https://cloud.githubusercontent.com/assets/3800972/12870819/094eb60a-cd24-11e5-9d01-81fe787a9dac.png)

It hadn't crossed my mind to do that, but since connection timeouts and other errors are more than too common on Brickimedia. we may as well make the error pages fit in to our site. We can style it to be more Brickimedia-esque, and perhaps make [notfound.html](http://www.brickimedia.org/notfound.html) a bit nicer too (since that page hasn't been touched since Brickimedia was first established). Thoughts? Ideas?

**Comment by codynguyen1116** [comment]
ooh looks lovely. This could fit nicely into the design guide :+1:

**Comment by MtMNC** [comment]
According to that article we would need a paid account unfortunately, which I don't believe we have...

**Comment by georgebarnick** [comment]
Depending the cost I think it'd be worthwhile. Unless it's some absurd
price. What are the other perks of a paid account?

On Sat, Feb 6, 2016, 11:45 PM MtMNC <notifications@github.com> wrote:

> According to that article we would need a paid account unfortunately,
> which I don't believe we have...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brickimedia/brickimedia/issues/452#issuecomment-180945623>
> .
>
-- 
George Barnick
https://www.georgebarnick.photo

**Comment by MtMNC** [comment]
The cheapest plan is $20/month. You can compare the plans [here](https://www.cloudflare.com/plans/). Things that jump out for the $20/month plan are mobile caching (for example it only sends CSS based on the user's device--not sure that would be helpful with Refreshed though), image optimization, more frequently updated analytics, and a [web application firewall](https://www.cloudflare.com/waf/).

**Comment by georgebarnick** [comment]
Those aren't bad features. Might hold off on this though until further notice for financial reasons.

**Comment by codynguyen1116** [comment]
@georgebarnick While CloudFlare pages are on hiatus I'll look into what our 404 page needs improvement on

**Comment by georgebarnick** [comment]
I'd suggest we put that off too until CloudFlare error pages are styled, that way we can give the 404 page a similar visual consistency

**Comment by codynguyen1116** [comment]
Hmm sounds like a good idea

**Comment by codynguyen1116** [comment]
Since I'm assuming we're moving off CloudFlare servers, would we be able to create our own 404 page?

**Comment by georgebarnick** [comment]
CloudFlare isn't our host. We'll still use CloudFlare...

**Comment by codynguyen1116** [comment]
My apologies, looks like I mixed up some terms together

**Comment by LegoFan4000** [comment]
I would support customizing theese pages.

**Comment by neoncitylights** [comment]
Moved to: https://phabricator.wikimedia.org/T151434
