### ISSUE TITLE
Repository naming conventions

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#453]
This repository naming conventions suggestion isn't actually *just* for organising everything but also to potentially help us gain more traffic. When people search up `mediawiki-extensions-*` or `mediawiki-skins-*`, they see all these wonderful coding projects made by many colalborators. However, ours aren't on the list. So, if we're textually consistent (consistency just in general is good), it could have a good chance of driving more users to see and maybe even contributors to our projects. This is what our new list of repos could look like based on the following rules:
- Use lowercase letters for prefixes, for a title by itself, or a mixture of lowercase and uppercase for the title if containing a prefix before.
- MediaWiki extensions need the `mediawiki-extensions-*` syntax and prefix.
- MediaWiki skins need the `mediawiki-skins-*` syntax and prefix.
- Anything _directly_ related to MediaWiki needs the `mediawiki-*` prefix.
- The github URL main directory needs to be completely lowercase, 'brickimedia' like 'wikimedia'. It should look like: 
  - `https://github.com/brickimedia`, similar to 
  - `https://github.com/wikimedia`

If this discussion thread passes a general consensus then @lewiscawte or @UltrasonicNXT can rename them. :+1:

# New repo names
These names are in alphabetical order.
- `brickimedia/brickimedia` (main brickimedia organisation is now lowercase)
- `brickimedia/living-style-guide` (that's what MediaWiki calls them)
- `brickimedia/general-scripts` (has a hyphen)
- `brickimedia/mediawiki-extensions`
- `brickimedia/mediawiki-extensions-Answers`
- `brickimedia/mediawiki-extensions-ARE`
- `brickimedia/mediawiki-extensions-GlobalContribs`
- `brickimedia/mediawiki-extensions-NumberOfComments`
- `brickimedia/mediawiki-extensions-Snippet`
- `brickimedia/mediawiki-extensions-USERNAME`
- `brickimedia/mediawiki-files-LocalSettings`
- `brickimedia/mediawiki-skins-Custard`
- `brickimedia/mediawiki-skins-DeepSea`
- `brickimedia/mediawiki-skins-Lia`
- `brickimedia/mediawiki-skins-Refreshed`
- `brickimedia/mediawiki-skins-Quartz`
- `brickimedia/splash` (stays the same, except brickimedia is lowercase)

__Notes__: This also means reconfiguring them again so they can still show up in IRC channels, I'm not sure how difficult that would be though, same with reconfiguring the live demo. I also don't know if the general scripts should be renamed to `mediawiki-files-GeneralScripts` or not *shrugs*

**Comment by codynguyen1116** [comment]
Note: If we were to move to Wikimedia we would have to follow that naming convention (I think?) but on GitHub we have our own freedom to name, follow up the discussion for that here or at #454

**Comment by georgebarnick** [comment]
I guess

**Comment by codynguyen1116** [comment]
Closing since we've moved
