### ISSUE TITLE
Test mw.skin Refreshed for bidirectionality (RTL) support 

### ISSUE THREAD

**Issue by SamanthaNguyen** [Brickimedia/brickimedia#455]
We already iterate tests for LTR without thinking, which is pretty much stable - but we don't do much testing for RTL (right to left) support, which we should. There's a great tool called CSSJanus, located at https://cssjanus.github.io/. 

Note: This isn't of a high priority because currently no wikis in languages that are read RTL are using Refreshed but it'd still be nice to look into. It'd be great for in the future if we ever gain multilingual users however :+1:

**Comment by mary-kate** [comment]
MediaWiki already internally uses CSSJanus to flip properties for automagic RTL support, and [the result is pretty spiffy](http://social-tools.wmflabs.org/w/index.php?title=Main_Page&useskin=refreshed&uselang=ar), and quite unlike during the Dark Ages when you had to manually write RTL CSS (which meant that custom skins really didn't support RTL languages unless they were developed by and for a RTL wiki).

I'm not sure what, if anything, needs to be done here skin-wise -- as far as I can see, Refreshed is doing everything by the book: there are no inline styles, not in the main PHP file nor in the JS file, and CSSJanus takes care of flipping the *.css files' contents automagically.

I believe that we should focus more on the overall User Experience, which is a combination of multiple things, some within our control (our tools & other code and how they handle things like CSS, etc.) and some not (user's browser & OS & their versions).
So while Refreshed as a skin is very RTL and mobile-friendly, [SocialProfile](https://www.mediawiki.org/wiki/Extension:SocialProfile) for example has some [inline styles](https://phabricator.wikimedia.org/T87148) which might hinder both RTL and mobile support, not to mention the need for [mobile-specific optimizations and tweaks](https://phabricator.wikimedia.org/T106268).

Of course what I wrote above is written from a certain point of view related to [a certain "family" of MediaWiki extensions](https://www.mediawiki.org/wiki/Social_tools), but essentially we should do a similar review on _all_ currently deployed extensions (not to mention any and all extensions we want to deploy in the future -- RTL and mobile are definitely something to take into account, but they aren't _always_ a showstopper, i.e. an admin-only tool might not need perfect mobile support).

**Comment by codynguyen1116** [comment]
Hmm everything looks great actually! There's just two things:
- The wiki logo is too large and should be adjusted
- The sidebar won't show up in mobile

However I do agree, UX is important, it's just that b14y/bidi happens to be (an albeit specific) part of that :) But yeah, there's more things that are of higher priority - what you listed is a good example. Hopefully if I ever learn how to get around with Gerrit I'll contribute :+1:

**Comment by MtMNC** [comment]
Looks like the sidebar doesn't show up since it uses a CSS transition of the `right` property and CSSJanus doesn't flip that to `left`. Also the logo is too big on the [English version](http://social-tools.wmflabs.org/w/index.php?title=Main_Page&useskin=refreshed) as well, so I don't think it's an RTL issue luckily. :) Self-assigning, I'll try and figure out a fix to the sidebar issue when I have time.

**Comment by codynguyen1116** [comment]
Opened in https://github.com/cssjanus/cssjanus/issues/39 for the mean time but thanks for your willing to help out, I greatly appreciate it :D :+1:

**Comment by codynguyen1116** [comment]
This issue will be on hold (and labeled) until there's some solution/discussion in https://github.com/cssjanus/cssjanus/issues/39

**Comment by neoncitylights** [comment]
Moved to https://phabricator.wikimedia.org/T151142
