### ISSUE TITLE
Install mw.ext MassMessage on wikis

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#456]
Was searching around MediaWiki.org, and came across this wonderful and absolutely beautiful extension called [MassMessage](https://www.mediawiki.org/wiki/Extension:MassMessage). This would be a great tool for us, we could set up a mini-newsletter or weekly updates on forums saying "Hey, go vote on this!" or "Hey, here's some ideas of what you can edit on the wiki!" Also works great because there's support for wikifarms for the times we want to send a message to across __all__ of our wikis. We just set this line up:
```php
$wgAllowGlobalMessaging = true;
```
(note: it'd be better if there's a checkbox so we can decide when to send each specific message globally)
Check out the official MediaWiki article -> https://www.mediawiki.org/wiki/Extension:MassMessage

**Comment by codynguyen1116** [comment]
Assigning Adam to this ticket

**Comment by georgebarnick** [comment]
This is done. Please make a blog post announcing the feature and explaining its usage so that local administrators know how to take advantage of it.
