### ISSUE TITLE
LSW and Customs Wiki to do list

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#460]
__Note__: Creating this to do list just so we make sure everything is cleaned up, the process is smooth as possible, and we're not using unnecessary lines of code. Most of these tasks are set in LocalSettings repo, but include other things too.

Eventually, once all the content has been transported from LEGO Stories Wiki to Brickimedia Customs Wiki, the following things should be updated (mostly if it gets renamed):

# Technical 
## LocalSettings
- [ ] [/LocalSettings_stories.php](https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings_stories.php) needs to be deleted.
- [ ] [/LocalSettings_customs.php](https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings_customs.php) needs to be renamed to it's new wiki name
- [ ] the subdomain, `customs` should either be deleted or redirected to the new subdomain
- [ ] the subdomain, `stories` should either be deleted or redirected to the new subdomain
- [ ] Rewrite URLs subdomain of new site for all and each of the following configurations...
  - [ ] `wgRefreshedHeader` (mw.skin.Refreshed) configuration of each local wiki
  - [ ] `wgSiteMatrixSites` (mw.ext.SiteMatrix) in [/LocalSettings_ext.php line 268](https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings_ext.php#L268)
  - [ ] `newTalkGlobalDatabases` (mw.ext.NewTalkGlobal) in [LocalSettings_ext.php line 227](https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings_ext.php#L227)
  - [ ] `wgLocalDatabases` in [/LocalSettings_ext.php line 295](https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings_ext.php#L295)
- [ ] Rename permissions for customs rights and customs namespace in Admin Wiki at [/LocalSettings_admin.php](https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings_admin.php)
- [ ] Rename `refreshedCustoms` variable used for `wgRefreshedHeader` configuring in Refreshed skin
- [ ] Reconfigure customs switch case in [LocalSettings.php line 107](https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings.php#L107)
- [ ] Rename local namespace for the new wiki 

## Splash
- [ ] Rewrite to new wiki URLs in [splash/index.html](https://github.com/Brickimedia/splash/blob/master/index.html)

## General scripts
- [ ] Rewrite to new wiki name in the scripts at [brickimedia/generalscripts](https://github.com/Brickimedia/generalscripts)

# Meta
- [x] Regarding interwiki links: Create new interwiki prefix for the interwiki table. Then..either change the URLs of the `customs` and `stories` prefix to the new subdomain,or delete the existing prefixes and get a bot to rename all the old prefixes to the new prefixes. (I like the first option better)

# Logos
- [ ] DeepSea logo with "Fanatics Wiki" - http://images.brickimedia.org/4/4e/Customs-Logo.png
- [ ] Refreshed logo with "Fanatics Wiki" - https://github.com/Brickimedia/Refreshed/blob/master/refreshed/images/customs.svg

**Comment by codynguyen1116** [comment]
Putting this on hold until consensus is reached for the new wiki name

**Comment by SirComputer1** [comment]
New wiki name to be LEGO Fanatics Wiki, relaunch wanted to be March 1 - eek deadlines.

Why the heck am I still here?

**Comment by codynguyen1116** [comment]
Good question. :+1: Now that's a real mystery

**Comment by NovaFlare** [comment]
Just a minor thing- would someone who can edit http://customs.brickimedia.org/load.php?debug=false&lang=en&modules=site&only=styles&skin=deepsea be able to remove the following line, or at least just the "!important"? It's what appears to be preventing the ability to change the text color on the Fanatics Deep Sea skin.

#p-personal li,#p-media li,div.vectorTabs li,div.vectorMenu,#p-search,div#mw-panel div.portal div.body ul li,.vectorMenu li,#p-search-mobile{background-color:#FF6F6F}div.vectorTabs li.selected{background-color:#FFFFFF}div.vectorMenu ul{border:solid 1px #FF6F6F}div#mw-panel div.portal div.body ul li a,#p-media a,#p-personal a,div.vectorTabs li a,div.vectorMenu li a,div#mw-panel div.portal div.body ul li a{color:#720000!important}

Thanks!

**Comment by codynguyen1116** [comment]
@NovaFlare: I'll ping @georgebarnick to do this task since I'm not a local wiki Customs administrator

**Comment by georgebarnick** [comment]
What needs doing? @NovaFlare has permission to edit local CSS

**Comment by codynguyen1116** [comment]
Ah forgot he's admin, it's an easy task though. A simple CSS block needs removing in MediaWiki:DeepSea.css

**Comment by NovaFlare** [comment]
.....

I thought that was a separate stylesheet overruling the CSS, not the local CSS itself. And for some reason it wasn't changing before when I tried changing the color, but it's fine now. Sorry.

**Comment by codynguyen1116** [comment]
It's fine, don't worry about it :) @novaflare

**Comment by codynguyen1116** [comment]
@georgebarnick @MtMNC 
The following logos also need updating: (adding this up in the tracking to do list also)
- DeepSea logo - http://images.brickimedia.org/4/4e/Customs-Logo.png
- Refreshed logo -https://github.com/Brickimedia/Refreshed/blob/master/refreshed/images/customs.svg

(again, the refreshed images should eventually be defined by a variable in LocalSettings files, refers to #451)

**Comment by codynguyen1116** [comment]
@georgebarnick @lewiscawte @UltrasonicNXT 
Do any of you have server-side access to reconfigure the sub domains, to rename `custom.brickimedia` to `fanatics.brickimedia`?

**Comment by codynguyen1116** [comment]
We'll need that done first so all the other tasks can be done

**Comment by georgebarnick** [comment]
That's done through LocalSettings

On Sun, Feb 28, 2016, 11:21 AM Cody Nguyen <notifications@github.com> wrote:

> We'll need that done first so all the other tasks can be done
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brickimedia/brickimedia/issues/460#issuecomment-189898965>
> .
>
-- 
George Barnick
https://www.georgebarnick.photo

**Comment by codynguyen1116** [comment]
How does one change the main URL's subdomain of Brickimedia Customs Wiki with LocalSettings? (I don't mean all the sub-settings)

**Comment by codynguyen1116** [comment]
Wait, do you mean this? 
https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings.php#L107

**Comment by georgebarnick** [comment]
Yes

On Sun, Feb 28, 2016, 3:14 PM Cody Nguyen <notifications@github.com> wrote:

> Wait, do you mean this?
>
> https://github.com/Brickimedia/LocalSettings/blob/master/LocalSettings.php#L107
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brickimedia/brickimedia/issues/460#issuecomment-189936628>
> .
>
-- 
George Barnick
https://www.georgebarnick.photo

**Comment by codynguyen1116** [comment]
Messed up twice today trying to do this task but I think I almost got it, I'll link the commit once I'm done :+1:

**Comment by georgebarnick** [comment]
Feel free to just make a pull request and we can double check it before
it's committed

On Sun, Feb 28, 2016 at 6:40 PM Cody Nguyen <notifications@github.com>
wrote:

> Messed up twice today trying to do this task but I think I almost got it,
> I'll link the commit once I'm done [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brickimedia/brickimedia/issues/460#issuecomment-189966872>
> .
>
-- 
George Barnick
https://www.georgebarnick.photo

**Comment by codynguyen1116** [comment]
Woops sorry! I made a commit at https://github.com/Brickimedia/LocalSettings/commit/e135a6220a0b7862fbcbc450c5907606df8f3084 and https://github.com/Brickimedia/Refreshed/commit/e94d989fe510fd2e2f05f03f73c670a5d189b35d and already pushed it, could you check just in case though?

**Comment by codynguyen1116** [comment]
http://meta.brickimedia.org/wiki/Special:Log/interwiki done

**Comment by codynguyen1116** [comment]
reverted the following changes, someone else who has access to the server database and is also better at reviewing code should probably do this..
 -https://github.com/Brickimedia/Refreshed/commit/87d690043138e348ab4f842db1fdc1bcbca0ee91
-https://github.com/Brickimedia/generalscripts/commit/2eb71ae98fd7e2035b01d778c4dc5d3a7ba3e323
-https://github.com/Brickimedia/LocalSettings/commit/e0cc2e232f47faa701cf30af88a623acd161acac
-https://github.com/Brickimedia/LocalSettings/commit/bcccf0e3515ee1241cf4620eaca1a6f7d2a03768

**Comment by mary-kate** [comment]
Maybe this time around we'll first revert the reverts (above), _then_ rename the database "customs" to "fanatics" and _then_ update the site to the latest codebase. (I tried dumping the customs DB into a .sql file and creating the new fanatics database, but apparently our database user -- the one set in `LocalSettings_private.php` -- doesn't have `CREATE DATABASE` privileges, so that obviously didn't work out as intended.)

Looking at the last diff @codynguyen1116 linked to above, I get the feeling that the real culprit was `LocalSettings_ext.php` and its `$newTalkGlobalDatabases` global variable, which also contains database name definitions. There's also a definition of the `$wgLocalDatabases` global on line 295 (why is this global being defined in two different files? what things use it, even?). Finally it also seems that `LocalSettings_meta.php` _also_ defines `$wgLocalDatabases`...I think this is unnecessarily messy and we could come up with a slightly less ugly solution.

**Comment by georgebarnick** [comment]
Why not just rename the site and leave the file names as they are right now? LocalSettings_customs can stay customs, the database can stay customs. All that is backend stuff that isn't really necessary to go and change. The front-end is all that really needs changing and that shouldn't be very difficult.

**Comment by codynguyen1116** [comment]
This issue will be put on hold until votes have been closed for http://en.brickimedia.org/wiki/Brickipedia:2016_Changes

**Comment by SirComputer1** [comment]
In consolidation of the wikis this will never happen, so I'll close this for you guys.
