### ISSUE TITLE
Site backups size and space

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#461]
@UltrasonicNXT, out of curiosity how big are our backups? We're still hosting them on Dropbox correct? How much space is that taking up? On each backup it's gzipping the server files and the databases correct?

**Comment by UltrasonicNXT** [comment]
Yeah, they're on dropbox, each database is exported and gzipped. About 870 MB

**Comment by georgebarnick** [comment]
Dang only 870? Even with images?

**Comment by UltrasonicNXT** [comment]
images are not backed up onto dropbox

**Comment by UltrasonicNXT** [comment]
that would be many many many bytes

**Comment by georgebarnick** [comment]
What would we do if we lost our images and needed to restore them?

**Comment by UltrasonicNXT** [comment]
(sorry must have missed that). Hmm, probably panic

**Comment by georgebarnick** [comment]
Yeah, let's avoid that. Whether or not we move to a new host I'd propose backing them up. Pretty sure your free Dropbox plan won't cover the space it needs to backup images so I would suggest [an unlimited plan](https://www.harrellsecurities.com). A little more monthly expense than we're paying now, but at least we don't have to worry about losing something as major as all of our images (especially considering it's already happened once before on our current host)

**Comment by UltrasonicNXT** [comment]
Nah we can't back up the images to your server if the images are hosted on your server... That defeats the point of backing them up...

**Comment by georgebarnick** [comment]
Yeah that makes sense but they're on different drives which is why I
suggested it.

On Tue, Mar 15, 2016 at 1:05 PM Adam <notifications@github.com> wrote:

> Nah we can't back up the images to your server if the images are hosted on
> your server... That defeats the point of backing them up...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/Brickimedia/brickimedia/issues/461#issuecomment-196925103
>
-- 
George Barnick
https://www.georgebarnick.photo

**Comment by neoncitylights** [comment]
Moved to https://phabricator.wikimedia.org/T151141
