### ISSUE TITLE
Redirects and performance

### ISSUE THREAD

**Issue by SamanthaNguyen** [Brickimedia/brickimedia#462]
Each time a user tries to go to a redirect, it adds an extra request called a HTTP request-response, and that slows down the rendering of a page. Meaning, the process of getting from point A to point B will be slower than normal. It has to reload not only the HTML, but CSS, JS, images, and then also from the _server-side_ (PHP). (Correct me if I'm wrong)
# Data

Let's look at the data and see how many redirects we have per wiki as of 11:51 CST 02/26/2016 (mm/dd/yyyy)

| Wiki | Redirects | Redirect chains | Broken redirects |
| --- | --- | --- | --- |
| LEGO Ideas | 163 | 0 | 0 |
| Meta | 344 | 3 | 0 |
| Customs | 83 | 6 | 2 |
| Great Ball Contraption | 45 | 0 | 0 |
| Brickipedia | 1000+ | 0 | 2 |

Some things to note:
- GBCW has 46, not [45](http://greatballcontraption.com/index.php?title=Special:ListRedirects&limit=500&offset=0) because `gbc.brickimedia.org` also acts as a redirect to `greatballcontraption.com`
- Admin and Dev aren't included because they're not used considerably as much as the others
# Reasons

I did research on why we use redirects, so here are the reasons:
- To avoid common misspellings. 
  - _Template:Welcomea_ → _Template:Welcome_
- Has alternative names. /
  - _Green Ninja_ → _Lloyd Garmadon_
- Has an ID. For example, sets have sets ID, and parts have part IDs (only applies to us)
  - _21109_ → _21109 Exo Suit_
- It can be abbreviated/use of shortcut. 
  - _Project:AFD_ → _Project:Articles for Deletion_
- Alternative capitalizing method. 
  - _10665 spider-man: spider-car pursuit_ →‎ _10665 Spider-Man: Spider-Car Pursuit_
- Alternative spelling method by dialect (British English vs American English) 
  -  _Color Palette_ → _Colour Palette_
- More sensible name.
  - _File:$(KGrHqV,!lcE8MfFpM,5BPD6EKZLZQ~~60 57.JPG_ →‎ _File:5590-5.jpg_
- User was renamed. 
  - _User:CzechMate_ →‎ _User:TheNightingale_
- Plurals / Singular 
  - _System Administrator_ →‎ _System Administrators_
- It should be in a different namespace.
  - _GitHub_ →‎ _Help:GitHub_
# How to minimize the number of redirects
1. We can install mw.ext [CirrusSearch](https://www.mediawiki.org/wiki/Extension:CirrusSearch), a MediaWiki search extension utilizing the ElasticSearch engine. Here's some documentation on it and what it's about: https://www.mediawiki.org/wiki/Help:CirrusSearch. What's nice is that it can detect misspellings and also suggest similar names to what you type, and doesn't just take the exact value of what's typed.
2. Create a global redirect policy/guideline, and tutorials on redirects (or we could link to the mediawiki site about it?) We should define...
   - what a redirect actually is first in user-friendly text (so its understandable.)
   - what redirects are acceptable, and what aren't. 
   - how many redirects each page can have at the max, (the minimum is 0 obviously). 
   - tell why and how it's important and how it doesn't concern just developers and sysadmins, but the community also.
   - consider how to enforce it.
3. Currently, there's no third suggestion. This is where you guys come in! What do you think? Comment below.

**Comment by mary-kate** [comment]
IMO redirects aren't that much of an issue and quite frankly, I think this sounds like a micro-optimization rather than anything else. If you have data to the contrary, I'm happy to be proven wrong. :)

That said, out of the reasons for using redirects that you listed, I think the "more sensible name" is one that we could and should weed out. Looking at [Special:AllPages/File: on Meta](http://meta.brickimedia.org/wiki/Special:AllPages/File:), there are quite a few files named as such on the very first page of results. I wonder if the [filename prefix blacklist](http://meta.brickimedia.org/wiki/MediaWiki:Filename-prefix-blacklist) could be of use in weeding out useless file names?

**Comment by chriscook18** [comment]
Pedantic note: Welcomea is a different template to Welcome (at least at en. Not sure on other wikis).
Pretty much the only one you could easily get rid of is the more sensible name file one. They shouldn't be redirected, but just renamed and changed on all uses.

**Comment by Edward-Nigma** [comment]
Point A "To avoid common misspellings", and Point E "Alternative capitalizing method" really shouldn't be in usage in the first place. They have no good reason to exist, especially the alternatively capitalised article redirect. They are incorrect, and generally, are not typed in that fashion.

**Comment by NovaFlare** [comment]
CirrusSearch sounds great- I miss having a dropdown menu with results coming up as I type. I don't like the idea of removing redirects though, as far as I'm concerned, the more the better (within reason). They help get people to where they need to be. And most of the time, the results that come up when you search for something are ridiculous- if I ever need to search for something on our site, I  just use Google (<search term> site:en.brickimedia.org), which is partly why I'm so big on having redirects.

**Comment by codynguyen1116** [comment]
@NovaFlare: Yeah, I agree with the CirrusSearch part. As for Google: What's nice is that their AI engine has learned over many years and can return results itself that's lowercase and/or uppercase, and can easily detect misspellings in many many different languages. 

Once the site is back up, we could at least try and weed out the unnecessary ones:
- The redirects that have alternative casing (lower/upper) (google fixes it and so does CirrusSearch on the wiki)
- Delete non-sensible ones
- Misspellings

Then we can go from there, sound good?

**Comment by neoncitylights** [comment]
Move to a community discussion at some point later on
