### ISSUE TITLE
Page goes black after closing an enlarged image

### ISSUE THREAD

**Issue by Edward-Nigma** [Brickimedia/brickimedia#463]
After enlarging any image in any article by clicking it, attempting to close it will cause the entire page to go black.
<img width="1440" alt="screen shot 2016-02-28 at 18 39 57" src="https://cloud.githubusercontent.com/assets/6055805/13383158/ba3f7d8c-de4a-11e5-85b6-15c48245e88a.png">

**Comment by georgebarnick** [comment]
Please check the JavaScript consoles for errors. Is it in specific skins or across all skins?

**Comment by codynguyen1116** [comment]
@georgebarnick It's across all skins. Can I move this to Phabricator?

**Comment by Edward-Nigma** [comment]
@georgebarnick This occurs on the Refreshed and DeepSea skins. On the other hand, MonoBook and Vector take the user to the file page on Meta, so the issue is not present on those.

**Comment by NovaFlare** [comment]
@georgebarnick: "load.php:5:Error: Invalid callback. Function or method name expected", occurs after

new Error('constructor must be a function, cannot be a '+typeof

on

http://en.brickimedia.org/load.php?debug=false&lang=en&modules=mediawiki.ui.button%2Cicon%7Cmmv.bootstrap%7Cmmv.bootstrap.autostart%7Coojs%2Csite%7Cskins.refreshed.js&skin=refreshed&version=b6dbba7b0e76


and "load.php:20Syntax Error: Expected token ')'" after

{makeList(lists[i]);}moment.normalizeUnits=function(units){return normalizeUnits

on 

http://en.brickimedia.org/load.php?debug=false&lang=en&modules=moment&skin=refreshed&version=22c589d9ef75

Don't know if that helps

**Comment by mary-kate** [comment]
@NovaFlare You'll usually want to append `debug=true` to the URL to make [ResourceLoader](https://www.mediawiki.org/wiki/ResourceLoader) load all the JS in the so-called "debug mode", which produces (hopefully) slightly more readable stack traces and whatnot.

The actual JS error, which is breaking things, is "jQuery is not defined"...which is bizarre, to say the least. The code where it's not defined is apparently injected by the [CSS extension](https://www.mediawiki.org/wiki/Extension:CSS). I spoke with @MatmaRex about this:
```
[21:46:12]	<MatmaRex>	https://github.com/wikimedia/mediawiki-extensions-CSS/blob/master/CSS.php#L105
[21:46:13]	<MatmaRex>	yeah
[21:46:21]	<MatmaRex>	just use ResourceLoader::makeInlineScript there and it might work
[21:46:29]	<MatmaRex>	(right now it definitely won't)
```

I live-hacked that into `/var/www/core/extensions/CSS/CSS.php` (inb4 "live hacking is bad"; yes, obviously it is) and while I can't really say anything about whether it works or not, now I'm getting a different error at least on pages like [this](http://en.brickimedia.org/wiki/5870_Pretty_Playland?debug=true) after opening up MultimediaViewer and closing it:
```
Invalid callback. Function or method name expected.
File: http://en.brickimedia.org/resources/libs/oojs/oojs.jquery.js, line: 30, column: 139
```

(Using Internet Explorer 11 on Windows 7, FWIW.)

**Comment by codynguyen1116** [comment]
Moving to phab because of agreement to move platforms, listed at https://phabricator.wikimedia.org/T134648
