### ISSUE TITLE
Emojis instead of WikiFont icons appearing

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#465]
So, I think this might be the most interesting bug we've found yet.

OK, so the search icon doesn't appear - pretty normal bug.
![image](https://cloud.githubusercontent.com/assets/4723983/13394829/89dc3f0c-deb0-11e5-9062-6959d55ecc57.png)

But you can still tap it, it's just that an iOS emoji bear appears. I don't even know how..
![image](https://cloud.githubusercontent.com/assets/4723983/13394870/baddda70-deb0-11e5-9631-00b01b6c6fa0.png)

**Comment by codynguyen1116** [comment]
Nvm I know it's because one of the recent commits but I don't know the source of the bug (what file / what line)

**Comment by codynguyen1116** [comment]
OK actually I thinks it's because of conflicting existing unicodes, can someone confirm this?

**Comment by codynguyen1116** [comment]
Reported from CJC95: Doesn't appear on Chrome on Galaxy Tab

**Comment by chriscook18** [comment]
Neither seems to be an issue on Android.

**Comment by codynguyen1116** [comment]
Moved upstream: https://phabricator.wikimedia.org/T128604
