### ISSUE TITLE
Browsers, operating systems, and device

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#467]
@Brickimedia/developers 

Can we get a real quick list of what everyone uses mainly? Its nice to know so when there's a problem that pertains to one of the specific things we can ping that certain dev, and also to know what our full testing environment as a whole team looks like as a whole, and see if we need to expand it (our team is pretty small, only about 10-15)

Note: I'll close this issue once everyone / majority of everyone has commented and added

**Comment by codynguyen1116** [comment]
Adding mine:
* Operating system: Windows 10
* Browser, version: Chrome v48
* Device: Laptop

**Comment by codynguyen1116** [comment]
We should also try to request this data from the community (not force, though). This kind of user data is helpful and lets us know what we need to focus on

**Comment by georgebarnick** [comment]
Guess I should just list my primary devices

- Device: Laptop
  - Intel i5-3210M (4 CPUs) @ 2.50GHz -> 3.10GHz
  - NVIDIA GeForce GT 640M LE (1GB VRAM)
  - 16GB DDR3 RAM
- Operating system: Windows 10
- Browser, version: Chrome v48
- JS enabled: Yes
- Cookies enabled: Yes
- Flash version: 20
- Java version: Version 8 Update 71
- Browser size: 1903x979
- Screen size: 1920x1080
- Color depth: 24 bit

Mobile
- Operating system: Android 6.0.1
- Browser, version: Chrome v48
- JS enabled: Yes
- Cookies enabled: Yes
- Browser size: 412x660 (Retina), 1080x1730
- Screen size: 412x732 (Retina), 1080x1920
- Color depth: 32 bit

Make a survey or something for the community

**Comment by mary-kate** [comment]
@codynguyen1116 It's 2016, I think it's more than safe to assume that mobile devices have JS enabled. :-) Excluding NoScript users, we probably don't care about devices/OSes which don't have a browser that supports JS. (For "fun", you can try browsing the Internet with NoScript and be amazed at how many sites just don't work at all with JS disabled.)

As for the actual matter at hand, I have access to plenty of hardware, but most of these devices aren't exactly cutting-edge...far from it, actually. HD screens at most, for example. Anyway, here are some possibly relevant devices that I use:

Laptop
- Lenovo ThinkPad T400
  - Intel(R) Core(TM)2 Duo CPU P8400  @ 2.26GHz, 2267 Mhz
  - Switchable Graphics with Intel GMA 4500MHD and ATI Mobility Radeon HD 3470 (256 MB)
  - 3GB DDR3 RAM
- Operating system: Windows 7 Ultimate (for now)
- Browser, version: Internet Explorer 11
- Screen size: 14", 1440 x 900 px
- Color depth: 24 bit

Tablet
- Asus Fonepad 7 (ME372CG)
  - More detailed specs are available [here](http://www.devicespecifications.com/en/model/cf452957)
- Operating system: Android KitKat (4.4.2)
- Browser, version: Firefox for Android (latest version, currently 44.0)

[2-in-1 PC](https://en.wikipedia.org/wiki/2-in-1_PC)
- Microsoft Surface Pro 2
  - Intel Haswell i5-4300U CPU, 1.9–2.9 GHz
  - 128 GB SSD
  - 4 GB DDR3 RAM
  - more detailed specs available on [Wikipedia](https://en.wikipedia.org/wiki/Microsoft_Surface#Surface_Pro_line)
- Operating system: Windows 10 Education (for now)
- Browser: Microsoft Edge

Mobile
- lots of devices; Nokia N900 (find specs on [Wikipedia](https://en.wikipedia.org/wiki/Nokia_N900), as usual) continues to serve as my daily driver
- also lots of older Nokias as well as other unusual/indie devices (i.e. Firefox OS phones, a [Jolla](https://en.wikipedia.org/wiki/Jolla_(mobile_phone)), etc.)

Yeah, I got lazy, sorry about that. Anyway, if you're looking for unusual mobile devices or older laptops, let me know -- while I don't have the latest flagships from Samsung et al., I do have quite a few older laptops and such.

**Comment by MtMNC** [comment]
Laptop:
MacBook Pro (Retina, 15-inch, Early 2013)
* Operating system: OS X 10.11.3
* IP address: 76.91.4.133
* Javascript enabled: Yes
* Cookies enabled: Yes
* Flash version: 20.0.0
* Java version: Not installed
* Websockets supported: Yes
* Browser size: 1241 x 751
* Screen size: 1440 x 900 (Retina)
* Color depth: 24 bit

My primary mobile device is an iPhone 5. I can also test other iOS devices with Xcode's iOS Simulator though. (if there are any other Mac users here I highly recommend it.)
