### ISSUE TITLE
Refreshed Icons replaced by Emoji on iOS

### ISSUE THREAD

**Issue by SirComputer1** [Brickimedia/brickimedia#468]
On Chrome 48, iOS 9. I think the picture will say enough.

![image](https://cloud.githubusercontent.com/assets/5190450/13520308/448404a6-e1d7-11e5-9636-0f31b444a6f3.png)

**Comment by georgebarnick** [comment]
Duplicate of #465

**Comment by codynguyen1116** [comment]
@SirComputer1 Check https://phabricator.wikimedia.org/T128604 if you're interested
