### ISSUE TITLE
522 error: Time out 

### ISSUE THREAD

**Issue by codynguyen1116** [Brickimedia/brickimedia#474]
Could someone reboot the server again? I keep receiving 522 errors "time out".

**Comment by georgebarnick** [comment]
Server is currently shut off by Ramnode for using too many CPUs and
resources

On Fri, Apr 8, 2016, 7:22 AM Cody Nguyen <notifications@github.com> wrote:

> Could someone reboot the server again? I keep receiving 522 errors "time
> out".
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Brickimedia/brickimedia/issues/474>
>
-- 
George Barnick
https://www.georgebarnick.photo

**Comment by MtMNC** [comment]
It was briefly up again, but now it's back down. Since we can't discuss on the site, what are everyone's thoughts on moving forward with rehosting? @georgebarnick How long would that process take?

**Comment by georgebarnick** [comment]
Waiting on the new business internet to be set up and for the server to be relocated to the new location. Then would need @UltrasonicNXT to finish with importing, then finalize configuration, and then test it out for a period of time to ensure it's production-ready.

**Comment by LegoFan4000** [comment]
ok

**Comment by LegoFan4000** [comment]
https:georgebarnick.xyz still seems to work.

**Comment by codynguyen1116** [comment]
@MtMNC Rehosting sounds good :)

**Comment by NovaFlare** [comment]
Support moving ASAP :) This 522 garbage needs to stop

**Comment by UltrasonicNXT** [comment]
@georgebarnick what's the current status for me?

**Comment by LegoFan4000** [comment]
I also support rehosting.

**Comment by georgebarnick** [comment]
@UltrasonicNXT need to get images working primarily and make sure they're all imported (which I think you've done).

Also on the new server need to make LocalSettings a git clone inside of mediawiki-core but idk how to do that like we did on our Ramnode server so if you can do that it'd be good. Right now all the LocalSettings files aren't downloaded via git

**Comment by Ajraddatz** [comment]
Why are we using so many cores though? What has changed in the last two days?

**Comment by Ajraddatz** [comment]
I have the site back up in read-only, but it's still using too much. Can we just disable everything non-essential?

**Comment by codynguyen1116** [comment]
Site's back up (although I don't know if the hosting has switched yet?)
