### ISSUE TITLE
Toolbar icons appear as emoticons in iOS

### ISSUE THREAD

**Issue by lachlanshanks** [Brickimedia/brickimedia#475]
I am currently in an Apple Store and have realised the toolbar in the Refreshed skin shows up as emojis in Safari on iOS.

**Comment by lachlanshanks** [comment]
![image](https://cloud.githubusercontent.com/assets/7083224/17020022/4f35b1e2-4f37-11e6-877c-f7f6f80dd1d6.png)

**Comment by lachlanshanks** [comment]
I have this problem in both Brickipedia and Coasterpedia.

**Comment by SamanthaNguyen** [comment]
Ah my apologizes - haven't edited this repository's README yet but we switched to Phabricator Wikimedia, sorry about that! The issue is currently located at https://phabricator.wikimedia.org/T128604 :)
