### ISSUE TITLE
Refreshed not working on miraheze

### ISSUE THREAD

**Issue by MacFan4000** [Brickimedia/brickimedia#476]
We have tried to install refreshed on miraheze but have not been successful. Wikifont does not seem to exist, and as we use puppet to clone the GitHub repos to the server ,downloading it and adding it on the server is not an option, as it would get reverted when puppet runs.

**Comment by MacFan4000** [comment]
@mary-kate @SamanthaNguyen

**Comment by MtMNC** [comment]
On Phabricator we were discussing including the current version of WikiFont with every build of Refreshed. Thoughts? @mary-kate @SamanthaNguyen

**Comment by MtMNC** [comment]
The Brickimedia GitHub repo is no longer maintained, so please report issues on Phabricator instead.
