### ISSUE TITLE
Suggestions for updates to the "social" extensions (not socialprofile)

### ISSUE THREAD

**Issue by NovaFlare** [Brickimedia/brickimedia#53]
Comments:
- Add a section so that users can edit their own comments
- ^ This has been said by many people around the wiki, I just thought I may as well put it down here.
- Also, being allowed to revoke your vote on the comments would be nice, if you accidentally hit a thumbs down instead of a thumbs up, it'd be good to be able to correct that instead of it being locked in.

Wikiforum:
- A few people last time said they were missing the "kudos" button in the forums from Wikia, a thumbs up icon like on the blog extension would be nice.
- It may be good to be able to see who voted on a comment as well (maybe for the comments and voteny extensions too). However, this would probably require a whole extra table in the database for each extension, and I doubt it would be worth the effort.

Obviously, there's probably a lot of work to get this going, it's just a wishlist for things that people may want to take a look at way down the track, it's not urgent or anything.

**Comment by UltrasonicNXT** [comment]
Revoking comment votes is coming with https://gerrit.wikimedia.org/r/#/c/182361/

**Comment by UltrasonicNXT** [comment]
Revoking done.

**Comment by neoncitylights** [comment]
Ability to edit comment feature has been superseded by https://phabricator.wikimedia.org/T146589

**Comment by neoncitylights** [comment]
Brickimedia no longer uses GitHub as an issue tracker.
