### ISSUE TITLE
Special:ArticlesHome shows incorrect stats

### ISSUE THREAD

**Issue by georgebarnick** [Brickimedia/brickimedia#81]
<a href="http://meta.brickimedia.org/wiki/Special:ArticlesHome">Special:ArticlesHome</a> shows incorrect statistics on some entries (i.e. incorrect number of comments or votes).

To be honest, I think we could remove this special page, and make our own that works nicer.

**Comment by codynguyen1116** [comment]
We disabled this extension but I'll still report this as a bug on Phabricator for those who are interested (if you are just subscribe) in help improving BlogPage extension, it is located at https://phabricator.wikimedia.org/T126109
